import {InputError} from './officeAddons';
export class PlanError extends InputError{constructor(message:string,public status=400){super(message);}}
export function planDay(v:any,optional=false):Date|null{if(optional&&(v===null||v===undefined||v===''))return null;if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}(T.*)?$/.test(v))throw new InputError('Datum YYYY-MM-DD erforderlich.');const d=new Date(v.slice(0,10)+'T12:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v.slice(0,10)||(v.length>10&&!Number.isFinite(Date.parse(v))))throw new InputError('Ungültiges Kalenderdatum.');return d;}
function number(v:any,max:number,integer=false){if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max||(integer&&!Number.isInteger(v)))throw new InputError('Zahl außerhalb des gültigen Bereichs.');return v;}
function text(v:any,max:number,required=false){if(v==null&&!required)return '';if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw new InputError('Ungültiger Text.');return v.trim();}
function resources(v:any,max=1000){if(!v||typeof v!=='object'||Array.isArray(v))throw new InputError('Ressourcenobjekt erforderlich.');const entries=Object.entries(v);if(entries.length>max)throw new InputError('Zu viele Ressourcen.');const result:any={};for(const [key,value]of entries){if(!key||key!==key.trim()||key.length>120||['__proto__','prototype','constructor'].includes(key))throw new InputError('Ressourcenname ungültig.');Object.defineProperty(result,key,{value:number(value,100000),enumerable:true,writable:true,configurable:true});}return result;}
export function planInput(b:any){if(!b||typeof b!=='object'||!Array.isArray(b.tasks)||b.tasks.length>5000)throw new InputError('Aktivitätenliste erforderlich, maximal 5000 Vorgänge.');if(JSON.stringify(b).length>2*1024*1024)throw new InputError('Plan zu groß.');const start=planDay(b.start)!.toISOString().slice(0,10),ids=new Set<string>();
 const tasks=b.tasks.map((t:any)=>{if(!t||typeof t!=='object'||Array.isArray(t)||typeof t.id!=='string'||!/^[A-Za-z0-9_-]{1,120}$/.test(t.id)||ids.has(t.id))throw new InputError('Vorgangs-ID fehlt oder ist mehrfach vorhanden.');ids.add(t.id);const name=text(t.name,250,true),a=planDay(t.start,true),z=planDay(t.end,true);if(Boolean(a)!==Boolean(z)||a&&z&&z<a)throw new InputError(name+': Beginn und Ende prüfen.');const duration=number(t.dauerTage,36500,true);if(a&&z&&duration!==Math.round((z.getTime()-a.getTime())/86400000)+1)throw new InputError(name+': Dauer widerspricht Kalenderdaten.');if(typeof t.milestone!=='boolean')throw new InputError('Meilenstein muss Ja oder Nein sein.');if(t.milestone&&a&&z&&a.getTime()!==z.getTime())throw new InputError(name+': Meilenstein benötigt ein einzelnes Datum.');if(!Array.isArray(t.deps)||t.deps.length>5000||t.deps.some((x:any)=>typeof x!=='string')||new Set(t.deps).size!==t.deps.length)throw new InputError('Abhängigkeiten ungültig.');return {id:t.id,name,dauerTage:duration,start:a?.toISOString()||null,end:z?.toISOString()||null,progress:number(t.progress,100,true),notes:text(t.notes,5000),assignee:text(t.assignee,250),milestone:t.milestone,deps:t.deps,ressourcen:resources(t.ressourcen,100)};});
 const indegrees=new Map<string,number>(),edges=new Map<string,string[]>();for(const t of tasks){indegrees.set(t.id,t.deps.length);for(const id of t.deps){if(id===t.id||!ids.has(id))throw new InputError(t.name+': Abhängigkeit fehlt oder verweist auf sich selbst.');const e=edges.get(id)||[];e.push(t.id);edges.set(id,e);}}const queue=tasks.filter((t:any)=>!t.deps.length).map((t:any)=>t.id);for(let i=0;i<queue.length;i++)for(const id of edges.get(queue[i])||[]){const n=indegrees.get(id)!-1;indegrees.set(id,n);if(n===0)queue.push(id);}if(queue.length!==tasks.length)throw new InputError('Abhängigkeiten enthalten einen Kreis.');return {start,tasks,capacity:resources(b.capacity)};
}
