import crypto from 'crypto';
import {InputError} from './officeAddons';
export class DiaryExportError extends InputError{constructor(message:string,public status=400){super(message);}}
export function diaryMonth(v:any){if(v===undefined||v==='')return '';if(typeof v!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(v))throw new InputError('Monat YYYY-MM erforderlich.');return v;}
function day(v:any){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))throw new InputError('Berichtsdatum ungültig.');const d=new Date(v+'T12:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v)throw new InputError('Berichtsdatum ungültig.');return v;}
export function normalizeDiaryReport(raw:any,filename?:string){const r=Array.isArray(raw?.rows)&&raw.rows.length===1&&raw.rows[0]&&typeof raw.rows[0]==='object'?raw.rows[0]:raw;return {...raw,...r,filename:filename||raw.filename,sourceDocId:String(raw.sourceDocId||r.sourceDocId||raw.id||r.id||''),date:raw.date||r.date||r.datum,workflowStatus:raw.workflowStatus||r.workflowStatus,reportId:raw.reportId||r.reportId,evidenceLock:raw.evidenceLock||r.evidenceLock,pdfUrl:raw.pdfUrl||r.pdfUrl,lines:Array.isArray(r.lines)?r.lines:Array.isArray(raw.lines)?raw.lines:[],workDone:r.workDone||r.taetigkeiten||r.arbeiten||r.taetigkeit||'',notes:r.notes||r.bemerkungen||r.notizen||raw.notes||''};}
function text(v:any,max=5000){if(v==null)return '';if(typeof v!=='string'||v.length>max)throw new InputError('Text ungültig.');return v.trim();}
function decimal(v:any,max:number){if(typeof v!=='string'&&typeof v!=='number')throw new InputError('Zahl erforderlich.');const s=String(v).trim().replace(',','.');if(!/^\d{1,5}(\.\d{1,6})?$/.test(s))throw new InputError('Zahl ungültig.');const [a,b='']=s.split('.');const n=BigInt(a)*1000000n+BigInt(b.padEnd(6,'0'));if(n>BigInt(max)*1000000n)throw new InputError('Zahl zu groß.');return n;}
function clock(v:string){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw new InputError('Uhrzeit HH:mm erforderlich.');return Number(v.slice(0,2))*60+Number(v.slice(3));}
export function diaryTimeRows(reports:any[],type:any){
 const rows:any[]=[],issues:any[]=[],skipped:any[]=[],seen=new Set<string>();let lineCount=0;
 for(const report of reports){const ref=String(report.filename||report.sourceDocId||report.id||''),sourceId=String(report.sourceDocId||report.id||ref);
  if(seen.has(sourceId)){issues.push({report:ref,line:null,error:'Quelle mehrfach freigegeben. Berichte prüfen.'});continue;}seen.add(sourceId);
  let date:string;try{date=day(String(report.date||'').slice(0,10));}catch(e:any){issues.push({report:ref,line:null,error:e.message});continue;}
  const lines=Array.isArray(report.lines)?report.lines:[];if(!lines.length){skipped.push({report:ref,reason:'Keine strukturierten Zeitzeilen; Fließtext wird nicht als Arbeitszeit interpretiert.'});continue;}
  if(lines.length>1000)throw new InputError('Zu viele Zeitzeilen in einem Bericht.');lineCount+=lines.length;if(lineCount>10000)throw new InputError('Zu viele Zeitzeilen. Monat auswählen.');
  for(let i=0;i<lines.length;i++)try{const l=lines[i];if(!l||typeof l!=='object'||Array.isArray(l))throw new InputError('Zeitzeile ungültig.');
   const employee=text(l.mitarbeiter??l.employeeName??l.worker??l.employee,250);if(!employee){if(l.maschine||l.machine){skipped.push({report:ref,line:i+1,reason:'Maschinenzeile ohne Mitarbeiter.'});continue;}throw new InputError('Mitarbeiter fehlt.');}
   const start=text(l.von??l.start??l.arbeitsbeginn,5),end=text(l.bis??l.end??l.arbeitsende,5),pause=decimal(l.pauseMin??l.breakMinutes??l.pauseMinutes??0,1440);if(pause%1000000n)throw new InputError('Pause muss ganze Minuten enthalten.');
   const h=l.stunden??l.hours??l.netHours,has=h!==null&&h!==undefined&&h!=='',hours=has?decimal(h,24):null;let net:number,basis:string,from:number|null=null,to:number|null=null;
   if(start||end){if(!start||!end)throw new InputError('Beginn und Ende zusammen erforderlich.');from=clock(start);to=clock(end);if(to<=from){if(l.overnight!==true)throw new InputError('Nachtschicht muss ausdrücklich gekennzeichnet sein.');to+=1440;}else if(l.overnight===true)throw new InputError('Nachtschichtkennzeichen widerspricht Uhrzeiten.');net=to-from-Number(pause/1000000n);if(net<=0||net>1440)throw new InputError('Nettozeit ungültig.');if(hours!==null){const d=hours*60n-BigInt(net)*1000000n;if((d<0n?-d:d)>300000n)throw new InputError('Stundenangabe widerspricht Uhrzeiten und Pause.');}basis='Uhrzeiten abzüglich Pause';}
   else{if(hours===null||hours===0n)throw new InputError('Positive Netto-Stunden oder Uhrzeiten erforderlich.');if(pause!==0n)throw new InputError('Pause ohne Uhrzeiten nicht eindeutig.');net=Number((hours*60n+500000n)/1000000n);if(net<=0||net>1440)throw new InputError('Nettozeit ungültig.');basis='Netto-Stundenangabe, auf ganze Minuten gerundet';}
   rows.push({date,employee,employeeId:text(l.employeeId,120),start,end,breakMinutes:Number(pause/1000000n),netMinutes:net,hours:(net/60).toFixed(6),timeType:type.code,timeTypeLabel:type.label,activity:text(l.taetigkeit??l.activity??l.notiz),location:text(l.ort??l.location,500),report:ref,sourceDocId:sourceId,line:i+1,basis,from,to});
  }catch(e:any){issues.push({report:ref,line:i+1,error:e.message});}
 }
 if(rows.length>10000)throw new InputError('Zu viele Zeitzeilen. Monat auswählen.');
 const groups=new Map<string,any[]>();for(const r of rows){const k=r.employee.toLocaleLowerCase('de-DE'),a=groups.get(k)||[];a.push(r);groups.set(k,a);}
 for(const group of groups.values()){const intervals=group.filter(r=>r.from!==null).map(r=>({...r,begin:Date.parse(r.date+'T00:00Z')/60000+r.from,finish:Date.parse(r.date+'T00:00Z')/60000+r.to})).sort((a,b)=>a.begin-b.begin);let latest:any;for(const r of intervals){if(latest&&r.begin<latest.finish)issues.push({report:r.report,line:r.line,error:'Zeitüberschneidung für '+r.employee+' mit '+latest.report+' / Zeile '+latest.line+'.'});if(!latest||r.finish>latest.finish)latest=r;}
  const totals=new Map<string,number>();for(const r of group)totals.set(r.date,(totals.get(r.date)||0)+r.netMinutes);for(const [date,n] of totals)if(n>1440)issues.push({report:group[0].report,line:null,error:'Mehr als 24 Nettostunden für '+group[0].employee+' am '+date+'.'});
 }
 return {rows:rows.map(({from,to,...r})=>r),issues,skipped,totalMinutes:rows.reduce((n,r)=>n+r.netMinutes,0)};
}
export function exportFingerprint(refs:any[],type:any){return crypto.createHash('sha256').update(JSON.stringify({refs,type:{id:type.id,code:type.code,label:type.label,updatedAt:type.updatedAt}})).digest('hex');}
export function diaryTimeCsv(project:any,rows:any[]){const cell=(v:any)=>{const s=String(v??'');return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';};return '\uFEFF'+[['Projekt-ID','Projektcode','Datum','Mitarbeiter','Mitarbeiter-ID laut Quelle','Beginn','Ende','Pause Minuten','Netto Minuten','Netto Stunden','Zeitart','Zeitart Bezeichnung','Tätigkeit','Ort','Bericht','Quell-ID','Zeile','Berechnungsbasis'],...rows.map(r=>[project.id,project.code,r.date,r.employee,r.employeeId,r.start,r.end,r.breakMinutes,r.netMinutes,r.hours.replace('.',','),r.timeType,r.timeTypeLabel,r.activity,r.location,r.report,r.sourceDocId,r.line,r.basis])].map(r=>r.map(cell).join(';')).join('\r\n')+'\r\n';}
