import {InputError} from './officeAddons';
export const NON_WORKING_DAY='COMPANY_NON_WORKING_DAY',ARCHIVED_NON_WORKING_DAY='COMPANY_NON_WORKING_DAY_ARCHIVED';
export class NonWorkingDayError extends InputError{constructor(message:string,public status=400){super(message);}}
export function calendarDay(value:any):string{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new InputError('Datum muss JJJJ-MM-TT sein.');const d=new Date(value+'T12:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==value||Number(value.slice(0,4))<1900||Number(value.slice(0,4))>2199)throw new InputError('Kalenderdatum ungültig.');return value;}
export function nextCalendarDay(day:string){const d=new Date(calendarDay(day)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10);}
export function berlinDay(value:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(value);}
export function berlinMidnight(day:string){const base=Date.parse((day==='2200-01-01'?day:calendarDay(day))+'T00:00:00Z');let instant=base;const formatter=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});for(let i=0;i<3;i++){const parts=Object.fromEntries(formatter.formatToParts(new Date(instant)).map(p=>[p.type,p.value]));const local=Date.parse(`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}Z`);instant+=base-local;}return new Date(instant);}
export function nonWorkingRange(from:any,to:any=from){const a=calendarDay(from),b=calendarDay(to);if(b<a)throw new InputError('Enddatum liegt vor Beginn.');const result:string[]=[];for(let d=a;d<=b;d=nextCalendarDay(d)){result.push(d);if(result.length>366)throw new InputError('Höchstens 366 Tage pro Zeitraum.');}return result;}
export function nonWorkingInput(body:any,old:any={}){
 if(!body||typeof body!=='object'||Array.isArray(body))throw new InputError('Ungültiger Kalendereintrag.');
 const text=(key:string,fallback:string,max:number,required=false)=>{const raw=body[key]===undefined?fallback:body[key];if(raw!=null&&typeof raw!=='string')throw new InputError(key+': Text erforderlich.');const s=String(raw??'').trim();if((required&&!s)||s.length>max)throw new InputError(key+': ungültige Länge.');return s;};
 const title=text('title',old.title||'',250,true),location=text('location',old.location||'',150),notes=text('notes',old.notes||'',5000),kind=text('kind',old.category||'FEIERTAG',50,true);if(!['FEIERTAG','BETRIEBSFERIEN','BETRIEBSRUHE'].includes(kind))throw new InputError('Art des Ruhetags ungültig.');
 const date=calendarDay(body.date===undefined&&old.start?berlinDay(old.start):body.date);return {title,location:location||null,notes:notes||null,category:kind,start:berlinMidnight(date),end:berlinMidnight(nextCalendarDay(date)),allDay:true,busyStatus:'free',reminderMinutes:null,attendees:[] as string[],source:'RLC_STAMMDATEN',sourceId:kind};
}
export function nonWorkingOutput(row:any){return {id:row.id,date:berlinDay(row.start),title:row.title,kind:row.category,location:row.location||'',notes:row.notes||'',active:row.sourceType===NON_WORKING_DAY,updatedAt:row.updatedAt};}
