import {Router} from 'express';import {prisma} from '../lib/prisma';import {InputError,expiryStatus} from '../domain/officeAddons';import {contactInput,ContactError} from '../domain/businessContacts';import {planVersion} from '../services/constructionPlan';
const router=Router(),cid=(r:any)=>String(r.auth?.companyId||'').trim(),uid=(r:any)=>String(r.auth?.sub||r.auth?.userId||'').trim(),role=(r:any)=>String(r.auth?.companyRole||r.auth?.role||'').trim().toUpperCase();
const canWrite=(r:any)=>['ADMIN','ADMINISTRATOR','BUCHHALTUNG'].includes(role(r));
router.use((req:any,res,next)=>{if(!cid(req)||!uid(req))return res.status(401).json({ok:false,error:'Anmeldung erforderlich.'});if(!['ADMIN','ADMINISTRATOR','BUCHHALTUNG','BAULEITER','KALKULATOR'].includes(role(req)))return res.status(403).json({ok:false,error:'Kontaktverzeichnis nicht freigegeben.'});res.setHeader('Cache-Control','private, no-store');next();});
function write(req:any,res:any,next:any){if(!canWrite(req))return res.status(403).json({ok:false,error:'Kontaktpflege nur für Administration und Buchhaltung.'});next();}
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});console.error('Business contacts failed',e?.code||e?.name);return res.status(503).json({ok:false,error:'Kontaktdaten derzeit nicht verfügbar.'});}
const snapshot=(r:any)=>JSON.parse(JSON.stringify(r));
const readInclude={contactProfile:true,_count:{select:{invoicesAsCustomer:true,vendorBillsAsSupplier:true}}} as const;
function dto(row:any){const {contactProfile,_count,...party}=row;return {...party,profile:contactProfile||{website:'',trade:'',notes:'',subcontractor:false,contacts:[],sites:[],archived:false},version:planVersion(snapshot({contactProfile,...party})),linkedToAccounting:Boolean(_count?.invoicesAsCustomer||_count?.vendorBillsAsSupplier),legacyAddress:row.address!=null&&(typeof row.address!=='object'||Array.isArray(row.address))};}
async function audit(tx:any,req:any,action:string,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action,resource:'business-contact:'+after.id,meta:{before:before?snapshot(before):null,after:snapshot(after)}}});}
router.get('/',async(req:any,res)=>{try{const q=req.query.q??'';if(typeof q!=='string'||q.length>200)throw new InputError('Suchbegriff zu lang.');const type=req.query.type??'';if(type&&!['CUSTOMER','SUPPLIER','PARTNER'].includes(type))throw new InputError('Kontaktart ungültig.');const items=await prisma.party.findMany({where:{companyId:cid(req),...(type?{type}:{}),AND:[...(q?[{OR:[{name:{contains:q,mode:'insensitive' as const}},{email:{contains:q,mode:'insensitive' as const}}]}]:[]),...(req.query.includeArchived==='true'?[]:[{OR:[{contactProfile:{is:null}},{contactProfile:{is:{archived:false}}}]}])]},include:readInclude,orderBy:[{name:'asc'},{id:'asc'}],take:2001});if(items.length>2000)throw new InputError('Mehr als 2000 Kontakte. Suche oder Kontaktart eingrenzen.');res.json({ok:true,items:items.map(dto),canEdit:canWrite(req),canReadCertificates:['ADMIN','ADMINISTRATOR','BUCHHALTUNG','BAULEITER'].includes(role(req))});}catch(e){fail(res,e);}});

router.get('/:id/certificates',async(req:any,res)=>{
 try {
  if(!['ADMIN','ADMINISTRATOR','BUCHHALTUNG','BAULEITER'].includes(role(req)))return res.status(403).json({ok:false,error:'Nachweise nicht freigegeben.'});
  const supplier=await prisma.party.findFirst({where:{id:req.params.id,companyId:cid(req),type:'SUPPLIER'},select:{id:true,name:true}});
  if(!supplier)throw new ContactError('Lieferant nicht verfügbar.',404);
  const items=await prisma.contractCertificate.findMany({where:{companyId:cid(req),supplierPartyId:supplier.id,...(req.query.includeArchived==='true'?{}:{status:{not:'Archiviert'}}),project:{companyId:cid(req),...(role(req)==='BAULEITER'?{projectMembers:{some:{userId:uid(req)}}}:{})}},select:{id:true,title:true,issuer:true,type:true,status:true,validFrom:true,validUntil:true,revision:true,project:{select:{id:true,code:true,name:true}},contract:{select:{title:true,partner:true}},document:{select:{name:true,deletedAt:true}}},orderBy:[{validUntil:'asc'},{id:'asc'}],take:2001});
  if(items.length>2000)throw new InputError('Mehr als 2000 Nachweise. Bitte in der Projektansicht prüfen.');
  res.json({ok:true,supplier,items:items.map(({document,...item}:any)=>({...item,document:document&&!document.deletedAt?{name:document.name}:null,expiry:expiryStatus(item.validUntil)}))});
 }catch(e){fail(res,e);}
});

router.get('/:id/history',async(req:any,res)=>{try{if(!await prisma.party.findFirst({where:{id:req.params.id,companyId:cid(req)}}))throw new ContactError('Kontakt nicht verfügbar.',404);const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:'business-contact:'+req.params.id},select:{id:true,createdAt:true,action:true,meta:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});res.json({ok:true,items,limit:100});}catch(e){fail(res,e);}});
router.post('/',write,async(req:any,res)=>{try{const input=contactInput(req.body);const row=await prisma.$transaction(async tx=>{const company=await tx.$queryRaw<any[]>`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;if(!company.length)throw new ContactError('Firma nicht verfügbar.',403);if(await tx.party.findFirst({where:{companyId:cid(req),type:input.party.type,name:{equals:input.party.name,mode:'insensitive' as const}}}))throw new ContactError('Kontakt mit gleichem Namen und gleicher Art vorhanden. Bestehenden Eintrag prüfen.',409);const row=await tx.party.create({data:{companyId:cid(req),...input.party,contactProfile:{create:input.profile}},include:readInclude});await audit(tx,req,'BUSINESS_CONTACT_CREATE',null,row);return row;});res.status(201).json({ok:true,item:dto(row)});}catch(e){fail(res,e);}});
async function mutate(req:any,res:any,action:string){try{const row=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;await tx.$queryRaw`SELECT id FROM "Party" WHERE id=${req.params.id} AND "companyId"=${cid(req)} FOR UPDATE`;const old=await tx.party.findFirst({where:{id:req.params.id,companyId:cid(req)},include:readInclude});if(!old)throw new ContactError('Kontakt nicht verfügbar.',404);if(typeof req.body?.expectedVersion!=='string'||req.body.expectedVersion!==dto(old).version)throw new ContactError('Kontakt inzwischen geändert. Aktuellen Stand laden.',409);
 if(action==='UPDATE'){if(old.contactProfile?.archived)throw new ContactError('Archivierten Kontakt vor Bearbeitung wieder aktivieren.',409);const data=contactInput(req.body,old);if(data.party.name!==old.name&&(old._count.invoicesAsCustomer||old._count.vendorBillsAsSupplier))throw new ContactError('Name eines Kontakts mit Belegen bleibt unverändert.',409);if(data.party.name!==old.name&&await tx.party.findFirst({where:{companyId:cid(req),type:old.type,id:{not:old.id},name:{equals:data.party.name,mode:'insensitive' as const}}}))throw new ContactError('Name für diese Kontaktart bereits vorhanden.',409);await tx.party.update({where:{id:old.id},data:{...data.party,contactProfile:{upsert:{create:data.profile,update:{...data.profile,updatedAt:new Date(Math.max(Date.now(),(old.contactProfile?.updatedAt.getTime()||0)+1))}}}}});}
 else await tx.partyContactProfile.upsert({where:{partyId:old.id},create:{partyId:old.id,archived:action==='ARCHIVE'},update:{archived:action==='ARCHIVE',updatedAt:new Date(Math.max(Date.now(),(old.contactProfile?.updatedAt.getTime()||0)+1))}});
 const after=await tx.party.findUnique({where:{id:old.id},include:readInclude});await audit(tx,req,'BUSINESS_CONTACT_'+action,old,after);return after;
 });res.json({ok:true,item:dto(row)});}catch(e){fail(res,e);}}
router.put('/:id',write,(req,res)=>mutate(req,res,'UPDATE'));router.post('/:id/archive',write,(req,res)=>mutate(req,res,'ARCHIVE'));router.post('/:id/restore',write,(req,res)=>mutate(req,res,'RESTORE'));
export default router;
