import {Router} from 'express';
import {prisma} from '../lib/prisma';
import {InputError} from '../domain/officeAddons';
import {assignmentKind,assignmentInput,AssignmentError} from '../domain/catalogAssignment';
import {certificateExpiry} from '../domain/personnelCertificate';
const router=Router();
const cid=(r:any)=>String(r.auth?.companyId||'').trim(),uid=(r:any)=>String(r.auth?.sub||r.auth?.userId||'').trim();
const role=(r:any)=>String(r.auth?.companyRole||r.auth?.role||'').trim().toUpperCase();
const privileged=(r:any)=>['ADMIN','ADMINISTRATOR','BUCHHALTUNG'].includes(role(r));
function access(req:any,kind:string,write=false){const roles=kind==='LICENSE_CLASS'?['ADMIN','ADMINISTRATOR','BAULEITER']:write?['ADMIN','ADMINISTRATOR','BAULEITER','CAPOCANTIERE','KALKULATOR','BUCHHALTUNG']:null;if(roles&&!roles.includes(role(req)))throw new AssignmentError('ACCESS_FORBIDDEN',403);}
router.use((req:any,res,next)=>{if(!cid(req)||!uid(req))return res.status(403).json({ok:false,error:'COMPANY_AND_USER_REQUIRED'});next();});
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});if(e?.code==='P2002')return res.status(409).json({ok:false,error:'Zuordnung existiert bereits. Bestehenden Eintrag öffnen.'});console.error('Catalog assignment failed',e?.code||e?.name);return res.status(500).json({ok:false,error:'Zuordnung konnte nicht verarbeitet werden.'});}
async function materialScope(db:any,req:any){if(privileged(req))return {};const projects=await db.project.findMany({where:{companyId:cid(req),projectMembers:{some:{userId:uid(req)}}},select:{id:true,code:true}});return {OR:[{projectId:null},{projectId:''},{projectId:{in:projects.flatMap((x:any)=>[x.id,x.code]).filter(Boolean)}}]};}
const includes={catalog:{select:{code:true,label:true,active:true}},employee:{select:{id:true,name:true,active:true}},material:{select:{id:true,name:true,code:true,projectId:true,active:true}}};
async function scope(db:any,req:any,kind:string){return {companyId:cid(req),kind,...(kind==='HAZARD_CLASS'?{material:{companyId:cid(req),...await materialScope(db,req)}}:{employee:{companyId:cid(req)}})};}
function output(row:any){return {...row,expiry:row.kind==='LICENSE_CLASS'?certificateExpiry(row.validUntil):null};}
const snap=(v:any)=>JSON.parse(JSON.stringify(v));
async function audit(tx:any,req:any,action:string,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action,resource:'catalog-assignment:'+after.id,meta:{kind:'COMPANY_CATALOG_ASSIGNMENT',before:before?snap(before):null,after:snap(after)}}});}
async function target(tx:any,req:any,kind:string,id:string,requireActive:boolean){
 if(kind==='LICENSE_CLASS'){await tx.$queryRaw`SELECT id FROM "CompanyEmployee" WHERE id=${id} AND "companyId"=${cid(req)} FOR UPDATE`;const row=await tx.companyEmployee.findFirst({where:{id,companyId:cid(req),...(requireActive?{active:true}:{})}});if(!row)throw new AssignmentError('Mitarbeiter nicht verfügbar.',404);return row;}
 await tx.$queryRaw`SELECT id FROM "CompanyMaterial" WHERE id=${id} AND "companyId"=${cid(req)} FOR UPDATE`;const row=await tx.companyMaterial.findFirst({where:{id,companyId:cid(req),...await materialScope(tx,req),...(requireActive?{active:true}:{})}});if(!row)throw new AssignmentError('Material nicht verfügbar.',404);return row;
}
router.get('/',async(req:any,res)=>{try{const kind=assignmentKind(req.query.kind);access(req,kind);const items=await prisma.companyCatalogAssignment.findMany({where:{...await scope(prisma,req,kind),...(req.query.includeInactive==='true'?{}:{active:true})},include:includes,orderBy:[{active:'desc'},{createdAt:'desc'}]});let canEdit=true;try{access(req,kind,true);}catch{canEdit=false;}res.json({ok:true,items:items.map(output),canEdit});}catch(e){fail(res,e);}});
router.get('/resources',async(req:any,res)=>{try{const kind=assignmentKind(req.query.kind);access(req,kind);const targets=kind==='LICENSE_CLASS'?await prisma.companyEmployee.findMany({where:{companyId:cid(req),active:true},select:{id:true,name:true},orderBy:{name:'asc'}}):await prisma.companyMaterial.findMany({where:{companyId:cid(req),active:true,...await materialScope(prisma,req)},select:{id:true,name:true,code:true,projectId:true},orderBy:{name:'asc'}});const catalog=await prisma.companyMasterCatalog.findMany({where:{companyId:cid(req),kind,active:true},select:{id:true,code:true,label:true},orderBy:{code:'asc'}});res.json({ok:true,targets,catalog});}catch(e){fail(res,e);}});
router.get('/:id/history',async(req:any,res)=>{try{const row=await prisma.companyCatalogAssignment.findFirst({where:{id:req.params.id,companyId:cid(req)}});if(!row)throw new AssignmentError('NOT_FOUND',404);access(req,row.kind);if(!await prisma.companyCatalogAssignment.findFirst({where:{id:row.id,...await scope(prisma,req,row.kind)}}))throw new AssignmentError('NOT_FOUND',404);const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:'catalog-assignment:'+row.id,action:{in:['CATALOG_ASSIGNMENT_CREATE','CATALOG_ASSIGNMENT_UPDATE','CATALOG_ASSIGNMENT_ARCHIVE','CATALOG_ASSIGNMENT_RESTORE']}},select:{id:true,createdAt:true,action:true,meta:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});res.json({ok:true,items,limit:100});}catch(e){fail(res,e);}});
router.post('/',async(req:any,res)=>{try{const b=req.body||{},kind=assignmentKind(b.kind);access(req,kind,true);const targetId=kind==='LICENSE_CLASS'?b.employeeId:b.materialId;if(typeof targetId!=='string'||!targetId||typeof b.catalogId!=='string'||!b.catalogId)throw new InputError('Ziel und Katalogeintrag erforderlich.');if(kind==='LICENSE_CLASS'?b.materialId!=null:b.employeeId!=null)throw new InputError('Ungültiges Zuordnungsziel.');const data=assignmentInput(b,kind);if(!data.active)throw new InputError('Neue Zuordnung muss aktiv sein.');const item=await prisma.$transaction(async tx=>{
 await tx.$queryRaw`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;
 await target(tx,req,kind,targetId,true);
 await tx.$queryRaw`SELECT id FROM "CompanyMasterCatalog" WHERE id=${b.catalogId} AND "companyId"=${cid(req)} FOR UPDATE`;
 const catalog=await tx.companyMasterCatalog.findFirst({where:{id:b.catalogId,companyId:cid(req),kind,active:true}});if(!catalog)throw new AssignmentError('Katalogeintrag nicht verfügbar.',404);
 const old=await tx.companyCatalogAssignment.findFirst({where:{catalogId:catalog.id,...(kind==='LICENSE_CLASS'?{employeeId:targetId}:{materialId:targetId})}});if(old)throw new AssignmentError('Zuordnung existiert bereits. Auch archivierte Einträge berücksichtigen.',409);
 const row=await tx.companyCatalogAssignment.create({data:{companyId:cid(req),catalogId:catalog.id,kind,employeeId:kind==='LICENSE_CLASS'?targetId:null,materialId:kind==='HAZARD_CLASS'?targetId:null,codeSnapshot:catalog.code,labelSnapshot:catalog.label,...data},include:includes});await audit(tx,req,'CATALOG_ASSIGNMENT_CREATE',null,row);return row;});res.status(201).json({ok:true,item:output(item)});}catch(e){fail(res,e);}});
async function mutate(req:any,res:any,archive=false){try{const b=req.body||{};const item=await prisma.$transaction(async tx=>{
 await tx.$queryRaw`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;
 await tx.$queryRaw`SELECT id FROM "CompanyCatalogAssignment" WHERE id=${req.params.id} AND "companyId"=${cid(req)} FOR UPDATE`;
 const old=await tx.companyCatalogAssignment.findFirst({where:{id:req.params.id,companyId:cid(req)},include:includes});if(!old)throw new AssignmentError('NOT_FOUND',404);access(req,old.kind,true);
 for(const key of ['kind','catalogId','employeeId','materialId','codeSnapshot','labelSnapshot'])if(b[key]!==undefined&&b[key]!==(old as any)[key])throw new InputError('Zuordnungsidentität kann nicht geändert werden.');
 if(typeof b.expectedUpdatedAt!=='string'||!Number.isFinite(Date.parse(b.expectedUpdatedAt)))throw new InputError('Versionsangabe erforderlich.');if(Date.parse(b.expectedUpdatedAt)!==old.updatedAt.getTime())throw new AssignmentError('Zuordnung inzwischen geändert. Bitte neu laden.',409);
 const data=archive?{active:false}:assignmentInput(b,old.kind,old);await target(tx,req,old.kind,old.employeeId||old.materialId!,data.active===true);
 if(!old.active&&data.active){await tx.$queryRaw`SELECT id FROM "CompanyMasterCatalog" WHERE id=${old.catalogId} FOR UPDATE`;if(!await tx.companyMasterCatalog.findFirst({where:{id:old.catalogId,companyId:cid(req),kind:old.kind,active:true}}))throw new AssignmentError('Archivierter Katalogeintrag kann nicht erneut zugeordnet werden.',409);}
 const row=await tx.companyCatalogAssignment.update({where:{id:old.id},data:{...data,updatedAt:new Date(Math.max(Date.now(),old.updatedAt.getTime()+1))},include:includes});await audit(tx,req,old.active&&!row.active?'CATALOG_ASSIGNMENT_ARCHIVE':!old.active&&row.active?'CATALOG_ASSIGNMENT_RESTORE':'CATALOG_ASSIGNMENT_UPDATE',old,row);return row;});res.json({ok:true,item:output(item)});}catch(e){fail(res,e);}}
router.put('/:id',(req,res)=>mutate(req,res));router.delete('/:id',(req,res)=>mutate(req,res,true));export default router;
