import {Router} from 'express';import {prisma} from '../lib/prisma';import {InputError} from '../domain/officeAddons';import {ContactError} from '../domain/businessContacts';
const router=Router({mergeParams:true}),cid=(r:any)=>String(r.auth?.companyId||'').trim(),uid=(r:any)=>String(r.auth?.sub||r.auth?.userId||'').trim(),pid=(r:any)=>String(r.params.partyId||''),role=(r:any)=>String(r.auth?.companyRole||r.auth?.role||'').trim().toUpperCase();
const admin=(r:any)=>['ADMIN','ADMINISTRATOR'].includes(role(r)),editable=(r:any)=>admin(r)||role(r)==='BUCHHALTUNG';
const projectScope=(r:any)=>({companyId:cid(r),...(admin(r)?{}:{projectMembers:{some:{userId:uid(r)}}})});
const summary={id:true,subject:true,participants:true,updatedAt:true,project:{select:{id:true,code:true,name:true}},_count:{select:{messages:true,attachments:true}}} as const;
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});console.error('Contact communication failed',e?.code||e?.name);return res.status(503).json({ok:false,error:'Kommunikationszuordnung derzeit nicht verfügbar.'});}
function write(req:any,res:any,next:any){if(!editable(req))return res.status(403).json({ok:false,error:'Kontaktzuordnung nur für Administration und Buchhaltung.'});next();}
async function owner(tx:any,req:any,lock=false){if(lock){await tx.$queryRawUnsafe('SELECT id FROM "Company" WHERE id=$1 FOR UPDATE',cid(req));await tx.$queryRawUnsafe('SELECT id FROM "Party" WHERE id=$1 AND "companyId"=$2 FOR UPDATE',pid(req),cid(req));}const p=await tx.party.findFirst({where:{id:pid(req),companyId:cid(req)},select:{id:true,contactProfile:{select:{archived:true}}}});if(!p)throw new ContactError('Kontakt nicht verfügbar.',404);return p;}
async function thread(tx:any,req:any,id:string,lock=false){if(lock)await tx.$queryRawUnsafe('SELECT id FROM "CommunicationThread" WHERE id=$1 AND "companyId"=$2 FOR UPDATE',id,cid(req));const row=await tx.communicationThread.findFirst({where:{id,companyId:cid(req),project:projectScope(req)},select:summary});if(!row)throw new ContactError('Konversation nicht verfügbar.',404);return row;}
async function link(tx:any,req:any,id:string){await owner(tx,req);const t=await thread(tx,req,id);const row=await tx.partyCommunicationLink.findFirst({where:{companyId:cid(req),partyId:pid(req),threadId:id}});if(!row)throw new ContactError('Zuordnung nicht verfügbar.',404);return {row,t};}
const snapshot=(r:any)=>JSON.parse(JSON.stringify(r));
async function audit(tx:any,req:any,action:string,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action,resource:'contact-communication:'+pid(req)+':'+after.threadId,meta:{before:before?snapshot(before):null,after:snapshot(after)}}});}
router.get('/',async(req:any,res)=>{try{await owner(prisma,req);const items=await prisma.partyCommunicationLink.findMany({where:{companyId:cid(req),partyId:pid(req),...(req.query.includeArchived==='true'?{}:{archived:false}),thread:{companyId:cid(req),project:projectScope(req)}},select:{threadId:true,revision:true,archived:true,createdAt:true,updatedAt:true,thread:{select:summary}},orderBy:[{updatedAt:'desc'},{threadId:'asc'}],take:2001});if(items.length>2000)throw new InputError('Mehr als 2000 Zuordnungen. Projektkommunikation verwenden.');res.json({ok:true,items,canEdit:editable(req)});}catch(e){fail(res,e);}});
router.get('/candidates',async(req:any,res)=>{try{await owner(prisma,req);const id=req.query.projectId;if(typeof id!=='string'||!id.trim()||id.length>100)throw new InputError('Projekt auswählen.');const p=await prisma.project.findFirst({where:{...projectScope(req),OR:[{id},{code:id}]},select:{id:true}});if(!p)throw new ContactError('Projekt nicht verfügbar.',404);const items=await prisma.communicationThread.findMany({where:{companyId:cid(req),projectId:p.id},select:{...summary,contactLinks:{where:{partyId:pid(req),companyId:cid(req)},select:{archived:true,revision:true}}},orderBy:[{updatedAt:'desc'},{id:'asc'}],take:2001});if(items.length>2000)throw new InputError('Mehr als 2000 Konversationen. Projektkommunikation verwenden.');res.json({ok:true,items:items.map(({contactLinks,...item})=>({...item,link:contactLinks[0]||null}))});}catch(e){fail(res,e);}});
router.get('/:id/history',async(req:any,res)=>{try{await link(prisma,req,req.params.id);const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:'contact-communication:'+pid(req)+':'+req.params.id},select:{id:true,createdAt:true,action:true,meta:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});res.json({ok:true,items});}catch(e){fail(res,e);}});
router.get('/:id',async(req:any,res)=>{try{const data=await prisma.$transaction(async tx=>{const {row,t}=await link(tx,req,req.params.id);const messages=await tx.communicationMessage.findMany({where:{threadId:t.id},select:{id:true,fromName:true,toList:true,ccList:true,subject:true,body:true,createdAt:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});const attachments=await tx.communicationAttachment.findMany({where:{threadId:t.id},select:{id:true,name:true,document:{select:{name:true,projectId:true,deletedAt:true}}},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});return {link:row,thread:t,messages:messages.reverse().map(m=>({...m,body:m.body.slice(0,20000),bodyTruncated:m.body.length>20000})),attachments:attachments.map(({document,...a})=>({...a,name:document&&document.projectId===t.project.id&&!document.deletedAt?document.name:!document?a.name:'Dokument nicht verfügbar',documentAvailable:!!document&&document.projectId===t.project.id&&!document.deletedAt})),messageLimit:100,attachmentLimit:100};},{isolationLevel:'RepeatableRead'});res.json({ok:true,...data});}catch(e){fail(res,e);}});
router.post('/',write,async(req:any,res)=>{try{const id=req.body?.threadId;if(typeof id!=='string'||!id.trim()||id.length>100)throw new InputError('Konversation auswählen.');const item=await prisma.$transaction(async tx=>{const p=await owner(tx,req,true);if(p.contactProfile?.archived)throw new ContactError('Archivierten Kontakt für neue Zuordnungen zunächst aktivieren.',409);const t=await thread(tx,req,id,true);const old=await tx.partyCommunicationLink.findUnique({where:{partyId_threadId:{partyId:pid(req),threadId:t.id}}});if(old&&!old.archived)throw new ContactError('Konversation bereits zugeordnet.',409);if(old&&(!Number.isSafeInteger(req.body?.revision)||req.body.revision!==old.revision))throw new ContactError('Zuordnung inzwischen geändert. Aktuellen Stand laden.',409);const after=old?await tx.partyCommunicationLink.update({where:{partyId_threadId:{partyId:pid(req),threadId:t.id}},data:{archived:false,revision:{increment:1}}}):await tx.partyCommunicationLink.create({data:{partyId:pid(req),threadId:t.id,companyId:cid(req)}});await audit(tx,req,old?'CONTACT_COMMUNICATION_RESTORE':'CONTACT_COMMUNICATION_LINK',old,after);return after;});res.status(201).json({ok:true,item});}catch(e){fail(res,e);}});
router.delete('/:id',write,async(req:any,res)=>{try{const item=await prisma.$transaction(async tx=>{await owner(tx,req,true);await thread(tx,req,req.params.id,true);const old=await tx.partyCommunicationLink.findFirst({where:{companyId:cid(req),partyId:pid(req),threadId:req.params.id}});if(!old)throw new ContactError('Zuordnung nicht verfügbar.',404);if(old.archived||!Number.isSafeInteger(req.body?.revision)||req.body.revision!==old.revision)throw new ContactError('Zuordnung inzwischen geändert. Aktuellen Stand laden.',409);const after=await tx.partyCommunicationLink.update({where:{partyId_threadId:{partyId:pid(req),threadId:old.threadId}},data:{archived:true,revision:{increment:1}}});await audit(tx,req,'CONTACT_COMMUNICATION_UNLINK',old,after);return after;});res.json({ok:true,item});}catch(e){fail(res,e);}});
export default router;
