import {Router} from 'express';import {prisma} from '../lib/prisma';import {InputError,expiryStatus} from '../domain/officeAddons';import {ContactError} from '../domain/businessContacts';import {insuranceInput,insuranceTransition} from '../domain/contactInsurance';import {berlinToday} from '../domain/machineUsage';
const router=Router({mergeParams:true}),cid=(r:any)=>String(r.auth?.companyId||'').trim(),uid=(r:any)=>String(r.auth?.sub||r.auth?.userId||'').trim(),partyId=(r:any)=>String(r.params.partyId||'');
router.use((req:any,res,next)=>{const role=String(req.auth?.companyRole||req.auth?.role||'').trim().toUpperCase();if(!cid(req)||!uid(req))return res.status(401).json({ok:false,error:'Anmeldung erforderlich.'});if(!['ADMIN','ADMINISTRATOR','BUCHHALTUNG'].includes(role))return res.status(403).json({ok:false,error:'Policenverwaltung nur für Administration und Buchhaltung.'});res.setHeader('Cache-Control','private, no-store');next();});
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});if(e?.code==='P2002')return res.status(409).json({ok:false,error:'Policennummer bei diesem Versicherer bereits vorhanden.'});console.error('Contact insurance failed',e?.code||e?.name);res.status(503).json({ok:false,error:'Policenverwaltung derzeit nicht verfügbar.'});}
async function owner(tx:any,req:any,lock=false){if(lock){await tx.$queryRawUnsafe('SELECT id FROM "Company" WHERE id=$1 FOR UPDATE',cid(req));await tx.$queryRawUnsafe('SELECT id FROM "Party" WHERE id=$1 AND "companyId"=$2 FOR UPDATE',partyId(req),cid(req));}const row=await tx.party.findFirst({where:{id:partyId(req),companyId:cid(req)},select:{id:true,contactProfile:{select:{archived:true}}}});if(!row)throw new ContactError('Kontakt nicht verfügbar.',404);return row;}
function dto(r:any){const today=new Date(berlinToday()+'T00:00:00Z');return {...r,coverage:r.coverage==null?null:String(r.coverage),annualPremium:r.annualPremium==null?null:String(r.annualPremium),expiry:r.validFrom>today?'Beginn in Zukunft':expiryStatus(r.validUntil,today),cancellation:expiryStatus(r.cancellationUntil,today)};}
const snapshot=(r:any)=>JSON.parse(JSON.stringify(r));
async function audit(tx:any,req:any,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action:before?'CONTACT_INSURANCE_UPDATE':'CONTACT_INSURANCE_CREATE',resource:'contact-insurance:'+after.id,meta:{partyId:partyId(req),before:before?snapshot(before):null,after:snapshot(after)}}});}
async function duplicate(tx:any,req:any,data:any,id?:string){if(await tx.partyInsurancePolicy.findFirst({where:{companyId:cid(req),partyId:partyId(req),...(id?{id:{not:id}}:{}),insurer:{equals:data.insurer,mode:'insensitive'},policyNumber:{equals:data.policyNumber,mode:'insensitive'}}}))throw new ContactError('Policennummer bei diesem Versicherer bereits vorhanden. Bestehende Police prüfen.',409);}
router.get('/',async(req:any,res)=>{try{await owner(prisma,req);const rows=await prisma.partyInsurancePolicy.findMany({where:{companyId:cid(req),partyId:partyId(req)},orderBy:[{validUntil:'asc'},{id:'asc'}],take:2001});if(rows.length>2000)throw new InputError('Mehr als 2000 Policen. Verwaltung separat prüfen.');res.json({ok:true,items:rows.map(dto)});}catch(e){fail(res,e);}});
router.get('/:id/history',async(req:any,res)=>{try{await owner(prisma,req);if(!await prisma.partyInsurancePolicy.findFirst({where:{id:req.params.id,companyId:cid(req),partyId:partyId(req)}}))throw new ContactError('Police nicht verfügbar.',404);const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:'contact-insurance:'+req.params.id},select:{id:true,action:true,createdAt:true,meta:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});res.json({ok:true,items});}catch(e){fail(res,e);}});
router.post('/',async(req:any,res)=>{try{const data=insuranceInput(req.body);if(data.status!=='Entwurf')throw new InputError('Neue Police zunächst als Entwurf speichern.');const row=await prisma.$transaction(async tx=>{const p=await owner(tx,req,true);if(p.contactProfile?.archived)throw new ContactError('Archivierten Kontakt für neue Policen zunächst aktivieren.',409);await duplicate(tx,req,data);const row=await tx.partyInsurancePolicy.create({data:{companyId:cid(req),partyId:partyId(req),...data}});await audit(tx,req,null,row);return row;});res.status(201).json({ok:true,item:dto(row)});}catch(e){fail(res,e);}});
router.put('/:id',async(req:any,res)=>{try{const row=await prisma.$transaction(async tx=>{await owner(tx,req,true);const old=await tx.partyInsurancePolicy.findFirst({where:{id:req.params.id,companyId:cid(req),partyId:partyId(req)}});if(!old)throw new ContactError('Police nicht verfügbar.',404);if(!Number.isSafeInteger(req.body?.revision)||req.body.revision!==old.revision)throw new ContactError('Police inzwischen geändert. Aktuellen Stand laden.',409);if(old.status==='Archiviert')throw new InputError('Archivierte Policen sind gesperrt.');const data=insuranceInput(req.body);insuranceTransition(old.status,data.status);await duplicate(tx,req,data,old.id);const row=await tx.partyInsurancePolicy.update({where:{id:old.id},data:{...data,revision:{increment:1}}});await audit(tx,req,old,row);return row;});res.json({ok:true,item:dto(row)});}catch(e){fail(res,e);}});
export default router;
