import {Router} from "express";
import {prisma} from "../lib/prisma";
import {InputError} from "../domain/officeAddons";
import {costCenterInput,checkCostCenterRevision,CostCenterError} from "../domain/costCenter";
const router=Router();
const cid=(req:any)=>String(req.auth?.companyId||req.auth?.company||"").trim();
const uid=(req:any)=>String(req.auth?.sub||req.auth?.userId||"").trim();
const role=(req:any)=>String(req.auth?.companyRole||req.auth?.role||"").trim().toUpperCase();
const privileged=(req:any)=>["ADMIN","ADMINISTRATOR","BUCHHALTUNG"].includes(role(req));
async function project(req:any,token:string,db:any=prisma){return db.project.findFirst({where:{companyId:cid(req),OR:[{id:token},{code:token}],...(privileged(req)?{}:{projectMembers:{some:{userId:uid(req)}}})},select:{id:true,code:true}});}
router.use((req:any,res,next)=>{if(!cid(req)||!uid(req))return res.status(403).json({ok:false,error:"COMPANY_AND_USER_REQUIRED"});next();});
function write(req:any,res:any,next:any){if(!["ADMIN","ADMINISTRATOR","BAULEITER","BUCHHALTUNG"].includes(role(req)))return res.status(403).json({ok:false,error:"COST_CENTER_WRITE_FORBIDDEN"});next();}
const snapshot=(x:any)=>JSON.parse(JSON.stringify(x));
const output=(x:any)=>({...x,budget:Number(x.budget),budgetText:String(x.budget)});
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});if(e?.code==="P2002")return res.status(409).json({ok:false,error:"Kostenstellen-Code bereits vorhanden. Bestehende Kostenstelle öffnen."});console.error("Cost center operation failed",e?.code||e?.name);return res.status(500).json({ok:false,error:"Kostenstelle konnte nicht verarbeitet werden."});}
async function audit(tx:any,req:any,action:string,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action,resource:after.id,meta:{kind:"PROJECT_COST_CENTER",projectId:after.projectId,before:before?snapshot(before):null,after:snapshot(after)}}});}
router.get("/",async(req:any,res)=>{try{const token=String(req.query.projectId||"").trim();if(!token)throw new CostCenterError("PROJECT_REQUIRED");const p=await project(req,token);if(!p)return res.status(403).json({ok:false,error:"PROJECT_FORBIDDEN"});const items=await prisma.projectCostCenter.findMany({where:{companyId:cid(req),projectId:p.id,...(req.query.includeInactive==="true"?{}:{active:true})},orderBy:{code:"asc"}});res.json({ok:true,projectId:p.id,items:items.map(output)});}catch(e){fail(res,e);}});
router.get("/:id/history",async(req:any,res)=>{try{const item=await prisma.projectCostCenter.findFirst({where:{id:req.params.id,companyId:cid(req)}});if(!item)return res.status(404).json({ok:false,error:"NOT_FOUND"});if(!await project(req,item.projectId))return res.status(403).json({ok:false,error:"PROJECT_FORBIDDEN"});const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:item.id,action:{in:["COST_CENTER_CREATE","COST_CENTER_UPDATE","COST_CENTER_ARCHIVE","COST_CENTER_RESTORE"]}},orderBy:[{createdAt:"desc"},{id:"desc"}],take:100,select:{id:true,createdAt:true,action:true,meta:true}});res.json({ok:true,items,limit:100});}catch(e){fail(res,e);}});
router.post("/",write,async(req:any,res)=>{try{const body=req.body||{},token=String(body.projectId||"").trim();if(!token)throw new CostCenterError("PROJECT_REQUIRED");const p=await project(req,token);if(!p)return res.status(403).json({ok:false,error:"PROJECT_FORBIDDEN"});const data=costCenterInput(body);const item=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Project" WHERE id=${p.id} AND "companyId"=${cid(req)} FOR UPDATE`;if(!await project(req,p.id,tx))throw new CostCenterError("PROJECT_FORBIDDEN",403);const found=await tx.projectCostCenter.findUnique({where:{companyId_projectId_code:{companyId:cid(req),projectId:p.id,code:data.code}}});if(found)throw new CostCenterError("Kostenstellen-Code bereits vorhanden. Bestehende Kostenstelle öffnen.",409);const next=await tx.projectCostCenter.create({data:{companyId:cid(req),projectId:p.id,...data}});await audit(tx,req,"COST_CENTER_CREATE",null,next);return next;});res.status(201).json({ok:true,item:output(item)});}catch(e){fail(res,e);}});
async function mutate(req:any,res:any,archive=false){try{const body=req.body||{},item=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "ProjectCostCenter" WHERE id=${req.params.id} AND "companyId"=${cid(req)} FOR UPDATE`;const old=await tx.projectCostCenter.findFirst({where:{id:req.params.id,companyId:cid(req)}});if(!old)throw new CostCenterError("NOT_FOUND",404);if(!await project(req,old.projectId,tx))throw new CostCenterError("PROJECT_FORBIDDEN",403);if(body.projectId!==undefined){const p=await project(req,String(body.projectId),tx);if(!p||p.id!==old.projectId)throw new CostCenterError("Kostenstelle gehört zu einem anderen Projekt.",409);}checkCostCenterRevision(body,old);const data=archive?{active:false}:costCenterInput(body,old);const next=await tx.projectCostCenter.update({where:{id:old.id},data:{...data,updatedAt:new Date(Math.max(Date.now(),old.updatedAt.getTime()+1))}});const action=old.active&&!next.active?"COST_CENTER_ARCHIVE":!old.active&&next.active?"COST_CENTER_RESTORE":"COST_CENTER_UPDATE";await audit(tx,req,action,old,next);return next;});res.json({ok:true,item:output(item)});}catch(e){fail(res,e);}}
router.put("/:id",write,(req,res)=>mutate(req,res));
router.delete("/:id",write,(req,res)=>mutate(req,res,true));
export default router;
