import {Router} from 'express';import {prisma} from '../lib/prisma';import {InputError} from '../domain/officeAddons';import {catalogKind,catalogInput,CatalogError} from '../domain/masterCatalog';
const router=Router();const cid=(req:any)=>String(req.auth?.companyId||'').trim(),uid=(req:any)=>String(req.auth?.sub||req.auth?.userId||'').trim();
const admin=(req:any)=>['ADMIN','ADMINISTRATOR'].includes(String(req.auth?.companyRole||req.auth?.role||'').trim().toUpperCase());
router.use((req:any,res,next)=>{if(!cid(req)||!uid(req))return res.status(403).json({ok:false,error:'COMPANY_AND_USER_REQUIRED'});next();});
function write(req:any,res:any,next:any){if(!admin(req))return res.status(403).json({ok:false,error:'CATALOG_ADMIN_REQUIRED'});next();}
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});if(e?.code==='P2002')return res.status(409).json({ok:false,error:'Code bereits vorhanden. Bestehenden Eintrag öffnen.'});console.error('Master catalog operation failed',e?.code||e?.name);return res.status(500).json({ok:false,error:'Katalog konnte nicht verarbeitet werden.'});}
const snapshot=(x:any)=>JSON.parse(JSON.stringify(x));
async function audit(tx:any,req:any,action:string,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action,resource:'master-catalog:'+after.id,meta:{kind:'COMPANY_MASTER_CATALOG',before:before?snapshot(before):null,after:snapshot(after)}}});}
router.get('/',async(req:any,res)=>{try{const kind=catalogKind(req.query.kind);const items=await prisma.companyMasterCatalog.findMany({where:{companyId:cid(req),kind,...(req.query.includeInactive==='true'?{}:{active:true})},orderBy:{code:'asc'}});res.json({ok:true,items,canEdit:admin(req)});}catch(e){fail(res,e);}});
router.get('/:id/history',async(req:any,res)=>{try{const old=await prisma.companyMasterCatalog.findFirst({where:{id:req.params.id,companyId:cid(req)}});if(!old)throw new CatalogError('NOT_FOUND',404);const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:'master-catalog:'+old.id,action:{in:['MASTER_CATALOG_CREATE','MASTER_CATALOG_UPDATE','MASTER_CATALOG_ARCHIVE','MASTER_CATALOG_RESTORE']}},select:{id:true,createdAt:true,action:true,meta:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100});res.json({ok:true,items,limit:100});}catch(e){fail(res,e);}});
router.post('/',write,async(req:any,res)=>{try{const data=catalogInput(req.body),item=await prisma.$transaction(async tx=>{const company=await tx.$queryRaw<any[]>`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;if(!company.length)throw new CatalogError('COMPANY_REQUIRED',403);const old=await tx.companyMasterCatalog.findUnique({where:{companyId_kind_code:{companyId:cid(req),kind:data.kind,code:data.code}}});if(old)throw new CatalogError('Code bereits vorhanden. Bestehenden Eintrag öffnen.',409);const row=await tx.companyMasterCatalog.create({data:{companyId:cid(req),...data}});await audit(tx,req,'MASTER_CATALOG_CREATE',null,row);return row;});res.status(201).json({ok:true,item});}catch(e){fail(res,e);}});
async function mutate(req:any,res:any,archive=false){try{const b=req.body||{};const item=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "CompanyMasterCatalog" WHERE id=${req.params.id} AND "companyId"=${cid(req)} FOR UPDATE`;const old=await tx.companyMasterCatalog.findFirst({where:{id:req.params.id,companyId:cid(req)}});if(!old)throw new CatalogError('NOT_FOUND',404);if(typeof b.expectedUpdatedAt!=='string'||!Number.isFinite(Date.parse(b.expectedUpdatedAt)))throw new InputError('Versionsangabe erforderlich.');if(Date.parse(b.expectedUpdatedAt)!==old.updatedAt.getTime())throw new CatalogError('Eintrag wurde inzwischen geändert. Bitte neu laden.',409);const data=archive?{active:false}:catalogInput(b,old);const row=await tx.companyMasterCatalog.update({where:{id:old.id},data:{...data,updatedAt:new Date(Math.max(Date.now(),old.updatedAt.getTime()+1))}});const action=old.active&&!row.active?'MASTER_CATALOG_ARCHIVE':!old.active&&row.active?'MASTER_CATALOG_RESTORE':'MASTER_CATALOG_UPDATE';await audit(tx,req,action,old,row);return row;});res.json({ok:true,item});}catch(e){fail(res,e);}}
router.put('/:id',write,(req,res)=>mutate(req,res));router.delete('/:id',write,(req,res)=>mutate(req,res,true));export default router;
