import {Router} from 'express';
import {prisma} from '../lib/prisma';
import {InputError} from '../domain/officeAddons';
import {NON_WORKING_DAY,ARCHIVED_NON_WORKING_DAY,NonWorkingDayError,nonWorkingRange,nonWorkingInput,nonWorkingOutput,berlinMidnight,nextCalendarDay,berlinDay} from '../domain/nonWorkingDay';
const router=Router();const types=[NON_WORKING_DAY,ARCHIVED_NON_WORKING_DAY];
const cid=(req:any)=>String(req.auth?.companyId||'').trim(),uid=(req:any)=>String(req.auth?.sub||req.auth?.userId||'').trim();
const admin=(req:any)=>['ADMIN','ADMINISTRATOR'].includes(String(req.auth?.companyRole||req.auth?.role||'').toUpperCase());
router.use((req:any,res,next)=>{if(!cid(req)||!uid(req))return res.status(403).json({ok:false,error:'COMPANY_AND_USER_REQUIRED'});next();});
function write(req:any,res:any,next:any){if(!admin(req))return res.status(403).json({ok:false,error:'COMPANY_CALENDAR_ADMIN_REQUIRED'});next();}
function fail(res:any,e:any){if(e instanceof InputError)return res.status((e as any).status||400).json({ok:false,error:e.message});console.error('Non-working calendar operation failed',e?.code||e?.name);return res.status(500).json({ok:false,error:'Ruhetag konnte nicht verarbeitet werden.'});}
const snap=(x:any)=>JSON.parse(JSON.stringify(nonWorkingOutput(x)));
async function audit(tx:any,req:any,action:string,before:any,after:any){await tx.auditLog.create({data:{companyId:cid(req),userId:uid(req),action,resource:'non-working-day:'+after.id,meta:{kind:'COMPANY_NON_WORKING_DAY',before:before?snap(before):null,after:snap(after)}}});}
router.get('/',async(req:any,res)=>{try{let from:string,to:string;if(req.query.from!==undefined||req.query.to!==undefined){const days=nonWorkingRange(req.query.from,req.query.to);from=days[0];to=days[days.length-1];}else{const year=String(req.query.year||berlinDay(new Date()).slice(0,4));if(!/^\d{4}$/.test(year)||Number(year)<1900||Number(year)>2199)throw new InputError('Jahr ungültig.');from=year+'-01-01';to=year+'-12-31';}const items=await prisma.officeCalendarEvent.findMany({where:{companyId:cid(req),projectId:null,sourceType:{in:req.query.includeArchived==='true'?types:[NON_WORKING_DAY]},start:{gte:berlinMidnight(from),lt:berlinMidnight(nextCalendarDay(to))}},orderBy:[{start:'asc'},{title:'asc'}]});res.json({ok:true,items:items.map(nonWorkingOutput),canEdit:admin(req),from,to});}catch(e){fail(res,e);}});
router.get('/:id/history',async(req:any,res)=>{try{const old=await prisma.officeCalendarEvent.findFirst({where:{id:req.params.id,companyId:cid(req),projectId:null,sourceType:{in:types}}});if(!old)throw new NonWorkingDayError('NOT_FOUND',404);const items=await prisma.auditLog.findMany({where:{companyId:cid(req),resource:'non-working-day:'+old.id,action:{in:['NON_WORKING_DAY_CREATE','NON_WORKING_DAY_UPDATE','NON_WORKING_DAY_ARCHIVE','NON_WORKING_DAY_RESTORE']}},orderBy:[{createdAt:'desc'},{id:'desc'}],take:100,select:{id:true,action:true,createdAt:true,meta:true}});res.json({ok:true,items,limit:100});}catch(e){fail(res,e);}});
router.post('/',write,async(req:any,res)=>{try{const body=req.body||{},days=nonWorkingRange(body.date,body.toDate===undefined?body.date:body.toDate);const input=days.map(date=>nonWorkingInput({...body,date}));const items=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;const result:any[]=[];for(const data of input){const duplicate=await tx.officeCalendarEvent.findFirst({where:{companyId:cid(req),projectId:null,sourceType:NON_WORKING_DAY,start:data.start,location:data.location}});if(duplicate)throw new NonWorkingDayError('Für Datum und Geltungsbereich existiert bereits ein aktiver Ruhetag.',409);const row=await tx.officeCalendarEvent.create({data:{companyId:cid(req),projectId:null,sourceType:NON_WORKING_DAY,...data}});await audit(tx,req,'NON_WORKING_DAY_CREATE',null,row);result.push(row);}return result;},{timeout:30000});res.status(201).json({ok:true,items:items.map(nonWorkingOutput)});}catch(e){fail(res,e);}});
async function mutate(req:any,res:any,archive=false){try{const body=req.body||{};const row=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Company" WHERE id=${cid(req)} FOR UPDATE`;const old=await tx.officeCalendarEvent.findFirst({where:{id:req.params.id,companyId:cid(req),projectId:null,sourceType:{in:types}}});if(!old)throw new NonWorkingDayError('NOT_FOUND',404);if(typeof body.expectedUpdatedAt!=='string'||!Number.isFinite(Date.parse(body.expectedUpdatedAt)))throw new InputError('Versionsangabe erforderlich.');if(Date.parse(body.expectedUpdatedAt)!==old.updatedAt.getTime())throw new NonWorkingDayError('Ruhetag wurde inzwischen geändert. Bitte neu laden.',409);if(body.toDate!==undefined&&body.toDate!==body.date)throw new InputError('Mehrere Tage werden einzeln bearbeitet.');if(body.active!==undefined&&typeof body.active!=='boolean')throw new InputError('Aktiv muss Ja oder Nein sein.');const active=archive?false:body.active===undefined?old.sourceType===NON_WORKING_DAY:body.active;const data=nonWorkingInput(body,old);if(active){const duplicate=await tx.officeCalendarEvent.findFirst({where:{id:{not:old.id},companyId:cid(req),projectId:null,sourceType:NON_WORKING_DAY,start:data.start,location:data.location}});if(duplicate)throw new NonWorkingDayError('Für Datum und Geltungsbereich existiert bereits ein aktiver Ruhetag.',409);}const next=await tx.officeCalendarEvent.update({where:{id:old.id},data:{...data,sourceType:active?NON_WORKING_DAY:ARCHIVED_NON_WORKING_DAY,updatedAt:new Date(Math.max(Date.now(),old.updatedAt.getTime()+1))}});const action=old.sourceType===NON_WORKING_DAY&&!active?'NON_WORKING_DAY_ARCHIVE':old.sourceType===ARCHIVED_NON_WORKING_DAY&&active?'NON_WORKING_DAY_RESTORE':'NON_WORKING_DAY_UPDATE';await audit(tx,req,action,old,next);return next;});res.json({ok:true,item:nonWorkingOutput(row)});}catch(e){fail(res,e);}}
router.put('/:id',write,(req,res)=>mutate(req,res));router.delete('/:id',write,(req,res)=>mutate(req,res,true));export default router;
