import React from 'react';import {Link} from 'react-router-dom';import {officeAddonRequest as request} from './OfficeAddons';
const kinds:Record<string,string>={CUSTOMER:'Kunde',SUPPLIER:'Lieferant',PARTNER:'Partner'};
const blank=()=>({type:'CUSTOMER',name:'',vatId:'',email:'',phone:'',website:'',trade:'',notes:'',subcontractor:false,address:{street:'',postalCode:'',city:'',country:''},contacts:[] as any[],sites:[] as any[]});
function formOf(x:any){return {...blank(),type:x.type,name:x.name,vatId:x.vatId||'',email:x.email||'',phone:x.phone||'',...x.profile,address:x.legacyAddress?blank().address:{...blank().address,...(x.address||{})}};}
export default function BusinessContacts(){
 const [data,setData]=React.useState<any>(),[selected,setSelected]=React.useState<any>(),[form,setForm]=React.useState(blank()),[query,setQuery]=React.useState(''),[kind,setKind]=React.useState(''),[archived,setArchived]=React.useState(false),[busy,setBusy]=React.useState(false),[dirty,setDirty]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[history,setHistory]=React.useState<any>();
 const generation=React.useRef(0),guard=React.useRef(false),historyGeneration=React.useRef(0),live=React.useRef(true);
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);setError('');try{const d=await request('/api/business-contacts?includeArchived=true&q='+encodeURIComponent(query)+'&type='+kind);if(live.current&&n===generation.current)setData(d);}catch(e:any){if(live.current&&n===generation.current){setData(undefined);setError(e.message);}}finally{if(live.current&&n===generation.current)setBusy(false);}},[query,kind]);
 React.useEffect(()=>{live.current=true;void load();return()=>{live.current=false;generation.current++;historyGeneration.current++;};},[load]);
 React.useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 const rows=(data?.items||[]).filter((x:any)=>archived||!x.profile.archived);
 function choose(x?:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setSelected(x);setForm(x?formOf(x):blank());setDirty(false);setHistory(undefined);historyGeneration.current++;setError('');setMessage('');}
 function field(k:string,v:any){setForm(f=>({...f,[k]:v}));setDirty(true);}
 async function write(path:string,body:any,method='POST'){if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');try{const d=await request(path,{method,body:JSON.stringify(body)});if(!live.current)return;setSelected(d.item);setForm(formOf(d.item));setDirty(false);setHistory(undefined);await load();if(live.current)setMessage('Kontaktdaten gespeichert.');}catch(e:any){if(live.current)setError(e.message);}finally{guard.current=false;if(live.current)setBusy(false);}}
 function save(e:React.FormEvent){e.preventDefault();const body={...form,...(selected?.legacyAddress?{address:undefined}:{}),...(selected?{expectedVersion:selected.version}:{})};void write('/api/business-contacts'+(selected?'/'+encodeURIComponent(selected.id):''),body,selected?'PUT':'POST');}
 function archive(x:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;if(!window.confirm(x.profile.archived?'Kontakt wieder aktivieren?':'Kontakt im Verzeichnis archivieren? Buchhalterische Verknüpfungen bleiben erhalten.'))return;void write('/api/business-contacts/'+encodeURIComponent(x.id)+(x.profile.archived?'/restore':'/archive'),{expectedVersion:x.version});}
 async function showHistory(x:any){const n=++historyGeneration.current;setError('');try{const d=await request('/api/business-contacts/'+encodeURIComponent(x.id)+'/history');if(live.current&&n===historyGeneration.current)setHistory({name:x.name,...d});}catch(e:any){if(live.current&&n===historyGeneration.current)setError(e.message);}}
 function csv(){const cell=(v:any)=>{const s=String(v??'');return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';};const body=[['Art','Name','USt-IdNr.','E-Mail','Telefon','Straße','PLZ','Ort','Land','Website','Gewerk','Nachunternehmer','Status'],...rows.map((x:any)=>[kinds[x.type],x.name,x.vatId,x.email,x.phone,x.address?.street,x.address?.postalCode,x.address?.city,x.address?.country,x.profile.website,x.profile.trade,x.profile.subcontractor?'Ja':'Nein',x.profile.archived?'Archiviert':'Aktiv'])].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+body],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Kontakte.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="card"><header className="rlc-page-hero rlc-page-hero--split"><div><div className="rlc-page-hero__eyebrow">Büro & Verwaltung · Firmenstammdaten</div><h1>Adressen & Kontakte</h1><p>Kunden, Lieferanten und Partner aus den vorhandenen Firmenstammdaten</p></div><button className="rlc-page-hero__button" disabled={busy||!data?.canEdit} onClick={()=>choose()}>+ Kontakt</button></header>
 <p className="muted">Bestehende buchhalterische Kontakte werden wiederverwendet. Referenten und Standorte werden manuell gepflegt. Archivierung blendet den Kontakt in diesem Verzeichnis aus; bestehende Belege und andere Module bleiben erhalten. Administration und Buchhaltung pflegen, Bauleitung und Kalkulation lesen.</p>
 <div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><Link className="btn" to="/kalkulation/crm">Angebotsverfolgung</Link><Link className="btn" to="/buro/nachunternehmer">Nachunternehmernachweise</Link><Link className="btn" to="/buro/stammdaten">Stammdaten-Kataloge</Link></div>
 {error&&<div className="card" role="alert">{error}</div>}{message&&<div className="card" role="status">{message}</div>}
 <div className="rlc-page-toolbar"><input value={query} maxLength={200} placeholder="Name / E-Mail suchen" disabled={busy||dirty} onChange={e=>setQuery(e.target.value)}/><select value={kind} disabled={busy||dirty} onChange={e=>setKind(e.target.value)}><option value="">Alle Kontaktarten</option>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Archivierte anzeigen</label><button className="btn" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen und aktuellen Stand laden?'))return;setDirty(false);setSelected(undefined);setForm(blank());void load();}}>Aktualisieren</button><button className="btn" disabled={busy||!data} onClick={csv}>CSV</button></div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Name','Art / Gewerk','Kontakt','Adresse','Status','Aktion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td>{x.name}</td><td>{kinds[x.type]}{x.profile.subcontractor?' · Nachunternehmer':''}<div>{x.profile.trade}</div></td><td>{x.email}<div>{x.phone}</div></td><td>{x.legacyAddress?'Ältere Adressstruktur':Object.values({street:x.address?.street,postalCode:x.address?.postalCode,city:x.address?.city,country:x.address?.country}).filter(Boolean).join(' · ')}</td><td>{x.profile.archived?'Archiviert':'Aktiv'}</td><td><button className="btn" disabled={busy} onClick={()=>choose(x)}>{data.canEdit?'Öffnen / bearbeiten':'Öffnen'}</button>{data.canEdit&&<button className="btn" disabled={busy} onClick={()=>archive(x)}>{x.profile.archived?'Aktivieren':'Archivieren'}</button>}<button className="btn" disabled={busy} onClick={()=>void showHistory(x)}>Verlauf</button></td></tr>)}{!rows.length&&<tr><td colSpan={6}>{busy?'Wird geladen …':data?'Keine Kontakte für diesen Filter.':'Verzeichnis nicht verfügbar.'}</td></tr>}</tbody></table></div>
 {(selected||data?.canEdit)&&<form onSubmit={save} className="card" style={{marginTop:16}}><h2>{selected?selected.name:'Neuer Kontakt'}</h2><fieldset disabled={busy||!data?.canEdit||!!selected?.profile.archived} style={{border:0,padding:0}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>
 <label>Art <select value={form.type} disabled={!!selected} onChange={e=>{field('type',e.target.value);if(e.target.value!=='SUPPLIER')field('subcontractor',false);}}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {([['name','Firma / Name'],['vatId','USt-IdNr.'],['email','E-Mail'],['phone','Telefon'],['website','Website'],['trade','Gewerk / Kategorie']] as const).map(([k,label])=><label key={k}>{label}<input style={{width:'100%'}} required={k==='name'} readOnly={k==='name'&&!!selected?.linkedToAccounting} type={k==='email'?'email':'text'} value={form[k]} onChange={e=>field(k,e.target.value)}/></label>)}
 {form.type==='SUPPLIER'&&<label><input type="checkbox" checked={form.subcontractor} onChange={e=>field('subcontractor',e.target.checked)}/> Nachunternehmer</label>}
 {(['street','postalCode','city','country'] as const).map(k=><label key={k}>{({street:'Straße',postalCode:'PLZ',city:'Ort',country:'Land'} as any)[k]}<input style={{width:'100%'}} disabled={selected?.legacyAddress} value={form.address[k]} onChange={e=>field('address',{...form.address,[k]:e.target.value})}/></label>)}
 <label>Bemerkung<textarea rows={3} style={{width:'100%'}} value={form.notes} onChange={e=>field('notes',e.target.value)}/></label></div>
 {selected?.linkedToAccounting&&<p className="muted">Name und buchhalterische Kontaktart bleiben wegen vorhandener Belegverknüpfungen unverändert.</p>}{selected?.legacyAddress&&<p className="muted">Ältere Adressstruktur bleibt erhalten: {JSON.stringify(selected.address)}</p>}
 <h3>Ansprechpartner ({form.contacts.length}/20)</h3>{form.contacts.map((x:any,i:number)=><div key={i} style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:8}}>{['name','role','email','phone'].map(k=><label key={k}>{({name:'Name',role:'Funktion',email:'E-Mail',phone:'Telefon'} as any)[k]}<input required={k==='name'} type={k==='email'?'email':'text'} value={x[k]} onChange={e=>field('contacts',form.contacts.map((r,n)=>n===i?{...r,[k]:e.target.value}:r))}/></label>)}<button type="button" className="btn" onClick={()=>field('contacts',form.contacts.filter((_,n)=>n!==i))}>Entfernen</button></div>)}<button type="button" className="btn" disabled={form.contacts.length>=20} onClick={()=>field('contacts',[...form.contacts,{name:'',role:'',email:'',phone:''}])}>+ Ansprechpartner</button>
 <h3>Standorte ({form.sites.length}/20)</h3>{form.sites.map((x:any,i:number)=><div key={i} style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:8}}>{['name','street','postalCode','city','country'].map(k=><label key={k}>{({name:'Standort',street:'Straße',postalCode:'PLZ',city:'Ort',country:'Land'} as any)[k]}<input required={k==='name'} value={x[k]} onChange={e=>field('sites',form.sites.map((r,n)=>n===i?{...r,[k]:e.target.value}:r))}/></label>)}<button type="button" className="btn" onClick={()=>field('sites',form.sites.filter((_,n)=>n!==i))}>Entfernen</button></div>)}<button type="button" className="btn" disabled={form.sites.length>=20} onClick={()=>field('sites',[...form.sites,{name:'',street:'',postalCode:'',city:'',country:''}])}>+ Standort</button>
 {data?.canEdit&&<button className="btn btn-primary" type="submit" disabled={!!selected&&!dirty}>Speichern</button>}</fieldset><button type="button" className="btn" disabled={busy} onClick={()=>choose()}>Schließen / zurücksetzen</button>{selected?.profile.archived&&<p>Kontakt archiviert; zum Bearbeiten zuerst aktivieren.</p>}</form>}
 {history&&<section className="card"><h2>Änderungsverlauf · {history.name}</h2><button className="btn" onClick={()=>setHistory(undefined)}>Schließen</button><p className="muted">Bis zu 100 Änderungen ab der ersten Pflege in diesem Verzeichnis. Kommunikationsprotokolle werden hier noch nicht erfasst.</p>{history.items.map((h:any)=><details key={h.id}><summary>{new Date(h.createdAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})} · {({'BUSINESS_CONTACT_CREATE':'Angelegt','BUSINESS_CONTACT_UPDATE':'Geändert','BUSINESS_CONTACT_ARCHIVE':'Archiviert','BUSINESS_CONTACT_RESTORE':'Aktiviert'} as any)[h.action]}</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12}}>{[['Vorher',h.meta?.before],['Nachher',h.meta?.after]].map(([label,row]:any)=><div key={label}><strong>{label}</strong>{row?<><p>{row.name} · {kinds[row.type]}</p><p>{row.email} · {row.phone} · {row.vatId}</p><p>{row.address&&typeof row.address==='object'?Object.values(row.address).filter(v=>typeof v==='string').join(' · '):String(row.address||'')}</p><p>{row.contactProfile?.trade} · {row.contactProfile?.website}</p><p>{row.contactProfile?.notes}</p><p>{row.contactProfile?.archived?'Archiviert':'Aktiv'}{row.contactProfile?.subcontractor?' · Nachunternehmer':''}</p>{row.contactProfile?.contacts?.map((x:any,i:number)=><p key={'c'+i}>{[x.name,x.role,x.email,x.phone].filter(Boolean).join(' · ')}</p>)}{row.contactProfile?.sites?.map((x:any,i:number)=><p key={'s'+i}>{[x.name,x.street,x.postalCode,x.city,x.country].filter(Boolean).join(' · ')}</p>)}</>:<p>–</p>}</div>)}</div></details>)}</section>}
 </div>;
}
