import React from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {officeAddonRequest as request} from './OfficeAddons';
const labels:Record<string,string>={ABGELAUFEN:'Abgelaufen',BALD_FAELLIG:'Innerhalb von 30 Tagen',GUELTIG:'Datum gültig',OHNE_DATUM:'Ohne Ablaufdatum'};
const empty=()=>({targetId:'',catalogId:'',validUntil:'',checkedAt:'',notes:''});
export default function CatalogAssignments(){
 const [params,setParams]=useSearchParams();const kind=params.get('art')==='HAZARD_CLASS'?'HAZARD_CLASS':'LICENSE_CLASS',license=kind==='LICENSE_CLASS',targetFilter=params.get('targetId')||'';
 const [data,setData]=React.useState<any>(),[selected,setSelected]=React.useState<any>(),[form,setForm]=React.useState(empty()),[dirty,setDirty]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[query,setQuery]=React.useState(''),[status,setStatus]=React.useState(''),[archives,setArchives]=React.useState(false),[history,setHistory]=React.useState<any>();
 const generation=React.useRef(0),historyGeneration=React.useRef(0),guard=React.useRef(false),owner=React.useRef(kind+targetFilter);owner.current=kind+targetFilter;
 function populate(row?:any){setSelected(row);setForm(row?{targetId:row.employeeId||row.materialId,catalogId:row.catalogId,validUntil:row.validUntil?.slice(0,10)||'',checkedAt:row.checkedAt?.slice(0,10)||'',notes:row.notes||''}:{...empty(),targetId:targetFilter});setDirty(false);setHistory(undefined);historyGeneration.current++;}
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);try{const [rows,resources]=await Promise.all([request('/api/catalog-assignments?kind='+kind+'&includeInactive=true'),request('/api/catalog-assignments/resources?kind='+kind)]);if(n===generation.current)setData({...rows,...resources,kind});}catch(e:any){if(n===generation.current){setData(undefined);setError(e.message);}}finally{if(n===generation.current)setBusy(false);}},[kind]);
 React.useEffect(()=>{populate();setData(undefined);setError('');setMessage('');setStatus('');void load();return()=>{generation.current++;historyGeneration.current++;};},[load,targetFilter]);
 React.useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 const current=data?.kind===kind?data:undefined;
 const visible=(current?.items||[]).filter((r:any)=>(archives||r.active)&&(!targetFilter||r.employeeId===targetFilter||r.materialId===targetFilter)&&(!status||r.expiry?.status===status)&&[r.employee?.name,r.material?.name,r.material?.code,r.codeSnapshot,r.labelSnapshot,r.notes].join(' ').toLocaleLowerCase('de-DE').includes(query.toLocaleLowerCase('de-DE')));
 function choose(row?:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;populate(row);setError('');setMessage('');}
 async function write(fn:()=>Promise<any>,after:(d:any)=>void){if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');const k=kind+targetFilter;try{const d=await fn();if(owner.current===k){after(d);await load();setMessage('Zuordnung gespeichert.');}}catch(e:any){if(owner.current===k)setError(e.message);}finally{guard.current=false;setBusy(false);}}
 function save(e:React.FormEvent){e.preventDefault();void write(()=>request('/api/catalog-assignments'+(selected?'/'+encodeURIComponent(selected.id):''),{method:selected?'PUT':'POST',body:JSON.stringify({validUntil:license?form.validUntil||null:null,checkedAt:form.checkedAt||null,notes:form.notes,...(selected?{expectedUpdatedAt:selected.updatedAt}:{kind,catalogId:form.catalogId,[license?'employeeId':'materialId']:form.targetId})})}),d=>populate(d.item));}
 function archive(row:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;if(!window.confirm(row.active?'Zuordnung archivieren?':'Zuordnung wieder aktivieren?'))return;void write(()=>request('/api/catalog-assignments/'+encodeURIComponent(row.id),{method:row.active?'DELETE':'PUT',body:JSON.stringify({expectedUpdatedAt:row.updatedAt,...(!row.active?{active:true}:{})})}),()=>populate());}
 async function showHistory(row:any){const n=++historyGeneration.current;try{const d=await request('/api/catalog-assignments/'+encodeURIComponent(row.id)+'/history');if(n===historyGeneration.current)setHistory({title:row.codeSnapshot,...d});}catch(e:any){if(n===historyGeneration.current)setError(e.message);}}
 function csv(){const cell=(v:any)=>{const s=String(v??'');return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';};const rows=[['Ziel','Code','Bezeichnung bei Zuordnung','Gültig bis','Sichtung am','Datumsstatus','Bemerkung','Status'],...visible.map((r:any)=>[r.employee?.name||r.material?.name,r.codeSnapshot,r.labelSnapshot,r.validUntil?.slice(0,10),r.checkedAt?.slice(0,10),labels[r.expiry?.status]||'',r.notes,r.active?'Aktiv':'Archiviert'])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=(license?'Fuehrerschein':'Gefahrenklassen')+'-Zuordnungen.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const targets=current?.targets||[],catalog=current?.catalog||[];
 function field(key:string,value:string){setForm({...form,[key]:value});setDirty(true);}
 return <div className="card"><header className="rlc-page-hero rlc-page-hero--split"><div><div className="rlc-page-hero__eyebrow">Büro & Verwaltung · Zuordnungen</div><h1>{license?'Führerscheine & Fristen':'Gefahrenklassen · Material'}</h1><p>{license?'Führerscheintypen einzelnen Mitarbeitern zuordnen':'Gefahrenklassen einzelnen Materialien zuordnen'}</p></div><button className="rlc-page-hero__button" disabled={busy||!current?.canEdit} onClick={()=>choose()}>+ Zuordnung</button></header>
 <div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><button className="btn" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setParams({art:license?'HAZARD_CLASS':'LICENSE_CLASS'});}}>{license?'Gefahrenklassen':'Führerscheine'}</button><Link className="btn" to={'/buro/stammdaten?art='+kind}>Katalog pflegen</Link><Link className="btn" to={license?'/buro/personalnachweise':'/buro/materialverwaltung?bereich=material'}>{license?'Personalnachweise':'Materialverwaltung'}</Link><button className="btn" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;populate();void load();}}>Aktualisieren</button><button className="btn" disabled={busy||!current} onClick={csv}>CSV</button></div>
 <p className="muted">Manuell gepflegtes Register. Das Sichtungsdatum dokumentiert eine interne Sichtung; es bestätigt keine behördliche Prüfung oder Einsatzfreigabe. Code und Bezeichnung werden bei der Zuordnung gespeichert. Änderungen am Katalog schreiben bestehende Zuordnungen nicht um.</p>
 {error&&<div className="card" role="alert">{error}</div>}{message&&<div className="card" role="status">{message}</div>}
 {current?.canEdit&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:14,display:'grid',gap:12,gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'}}><label>{license?'Mitarbeiter':'Material'}<select style={{width:'100%'}} required disabled={!!selected} value={form.targetId} onChange={e=>field('targetId',e.target.value)}><option value="">Auswählen</option>{selected&&!targets.some((r:any)=>r.id===form.targetId)&&<option value={form.targetId}>{selected.employee?.name||selected.material?.name} (inaktiv)</option>}{targets.map((r:any)=><option key={r.id} value={r.id}>{r.name}{r.code?' · '+r.code:''}</option>)}</select></label>
 <label>{license?'Führerscheintyp':'Gefahrenklasse'}<select style={{width:'100%'}} required disabled={!!selected} value={form.catalogId} onChange={e=>field('catalogId',e.target.value)}><option value="">Auswählen</option>{selected&&<option value={selected.catalogId}>{selected.codeSnapshot} · {selected.labelSnapshot} (bei Zuordnung)</option>}{catalog.filter((r:any)=>r.id!==selected?.catalogId).map((r:any)=><option key={r.id} value={r.id}>{r.code} · {r.label}</option>)}</select></label>
 {license&&<label>Gültig bis<input style={{width:'100%'}} type="date" value={form.validUntil} onChange={e=>field('validUntil',e.target.value)}/></label>}<label>Sichtung am<input style={{width:'100%'}} type="date" value={form.checkedAt} onChange={e=>field('checkedAt',e.target.value)}/></label><label>Bemerkung<textarea style={{width:'100%'}} maxLength={5000} value={form.notes} onChange={e=>field('notes',e.target.value)}/></label><div><button className="btn btn-primary" type="submit">Speichern</button><button className="btn" type="button" onClick={()=>choose()}>Abbrechen</button>{selected&&!selected.active&&<p>Zuordnung bleibt archiviert.</p>}</div></fieldset></form>}
 <div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><input aria-label="Zuordnungen suchen" placeholder="Name, Code, Bemerkung …" value={query} onChange={e=>setQuery(e.target.value)}/>{license&&<select aria-label="Datumsstatus" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle Fristen</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>}<label><input type="checkbox" checked={archives} onChange={e=>setArchives(e.target.checked)}/> Archivierte anzeigen</label>{targetFilter&&<button className="btn" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setParams({art:kind});}}>Alle Ziele anzeigen</button>}<span>{visible.length} Zuordnungen</span></div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Ziel','Klasse bei Zuordnung','Frist / Sichtung','Status','Bemerkung','Aktion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((r:any)=><tr key={r.id}><td>{r.employee?.name||r.material?.name}{!(r.employee?.active??r.material?.active)&&<div className="muted">Ziel inaktiv</div>}</td><td>{r.codeSnapshot} · {r.labelSnapshot}{!r.catalog?.active&&<div className="muted">Katalogeintrag archiviert</div>}{r.catalog?.label!==r.labelSnapshot&&<div className="muted">Aktuell im Katalog: {r.catalog?.label}</div>}</td><td>{license&&<div>{r.validUntil?.slice(0,10)||'Kein Ablaufdatum'} · {labels[r.expiry?.status]}</div>}Sichtung: {r.checkedAt?.slice(0,10)||'Nicht erfasst'}</td><td>{r.active?'Aktiv':'Archiviert'}</td><td title={r.notes||''}>{r.notes?.slice(0,120)||'–'}</td><td>{current?.canEdit&&<><button className="btn" disabled={busy} onClick={()=>choose(r)}>Bearbeiten</button><button className="btn" disabled={busy} onClick={()=>archive(r)}>{r.active?'Archivieren':'Aktivieren'}</button></>}<button className="btn" onClick={()=>void showHistory(r)}>Verlauf</button></td></tr>)}{!visible.length&&<tr><td colSpan={6}>{busy?'Wird geladen …':!current?'Register nicht verfügbar.':'Keine Zuordnungen für diese Auswahl.'}</td></tr>}</tbody></table></div>
 {history&&<section className="card"><h2>Verlauf · {history.title}</h2><button className="btn" onClick={()=>{setHistory(undefined);historyGeneration.current++;}}>Schließen</button><p className="muted">Bis zu 100 Änderungen.</p>{history.items.map((h:any)=><div key={h.id} style={{padding:8,borderBottom:'1px solid var(--line)'}}><strong>{new Date(h.createdAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})}</strong> · {h.action.replace('CATALOG_ASSIGNMENT_','')}<p>Gültig bis: {h.meta?.before?.validUntil?.slice(0,10)||'–'} → {h.meta?.after?.validUntil?.slice(0,10)||'–'} · Sichtung: {h.meta?.before?.checkedAt?.slice(0,10)||'–'} → {h.meta?.after?.checkedAt?.slice(0,10)||'–'}</p><p>Bemerkung: {h.meta?.before?.notes||'–'} → {h.meta?.after?.notes||'–'}</p></div>)}</section>}
 </div>;
}
