import React from 'react';import {Link} from 'react-router-dom';import {officeAddonRequest as request} from './OfficeAddons';
const types=['Betriebshaftpflicht','Berufshaftpflicht','Bauleistung','Kfz / Geräte','Unfall','Sonstige'],statuses=['Entwurf','Aktiv','Beendet','Archiviert'];
const blank=()=>({title:'',insurer:'',policyNumber:'',type:types[0],status:'Entwurf',validFrom:'',validUntil:'',cancellationUntil:'',coverage:'',annualPremium:'',notes:''});
const labels:Record<string,string>={title:'Bezeichnung',insurer:'Versicherer',policyNumber:'Policennummer',type:'Versicherungsart',status:'Status',validFrom:'Beginn',validUntil:'Vertragsende',cancellationUntil:'Kündigung bis',coverage:'Versicherungssumme EUR',annualPremium:'Jahresprämie EUR',notes:'Bemerkung'};
function formOf(x:any){return {...blank(),...x,validFrom:x.validFrom?.slice(0,10)||'',validUntil:x.validUntil?.slice(0,10)||'',cancellationUntil:x.cancellationUntil?.slice(0,10)||'',coverage:x.coverage??'',annualPremium:x.annualPremium??''};}
export default function ContactInsurance({party,onDirtyChange,onBusyChange}:{party:any;onDirtyChange:(v:boolean)=>void;onBusyChange:(v:boolean)=>void}){
 const base='/api/business-contacts/'+encodeURIComponent(party.id)+'/insurance';
 const [items,setItems]=React.useState<any[]>([]),[selected,setSelected]=React.useState<any>(),[form,setForm]=React.useState(blank()),[dirty,setDirty]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[query,setQuery]=React.useState(''),[archived,setArchived]=React.useState(false),[history,setHistory]=React.useState<any>();
 const live=React.useRef(true),generation=React.useRef(0),historyGeneration=React.useRef(0),guard=React.useRef(false);
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);setError('');try{const d=await request(base);if(live.current&&n===generation.current)setItems(d.items);}catch(e:any){if(live.current&&n===generation.current){setItems([]);setError(e.message);}}finally{if(live.current&&n===generation.current)setBusy(false);}},[base]);
 React.useEffect(()=>{live.current=true;void load();return()=>{live.current=false;generation.current++;historyGeneration.current++;};},[load]);
 React.useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 React.useEffect(()=>{onBusyChange(busy);return()=>onBusyChange(false);},[busy,onBusyChange]);
 React.useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 function choose(x?:any){if(dirty&&!window.confirm('Ungespeicherte Policenänderungen verwerfen?'))return false;setSelected(x);setForm(x?formOf(x):blank());setDirty(false);setHistory(undefined);historyGeneration.current++;setError('');setMessage('');return true;}
 function field(k:string,v:string){setForm(f=>({...f,[k]:v}));setDirty(true);setMessage('');}
 async function save(e:React.FormEvent){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');try{const d=await request(base+(selected?'/'+encodeURIComponent(selected.id):''),{method:selected?'PUT':'POST',body:JSON.stringify({...form,...(selected?{revision:selected.revision}:{})})});if(!live.current)return;setSelected(d.item);setForm(formOf(d.item));setDirty(false);setHistory(undefined);await load();if(live.current)setMessage('Police gespeichert.');}catch(e:any){if(live.current)setError(e.message);}finally{guard.current=false;if(live.current)setBusy(false);}}
 async function showHistory(x:any){const n=++historyGeneration.current;setError('');try{const d=await request(base+'/'+encodeURIComponent(x.id)+'/history');if(live.current&&n===historyGeneration.current)setHistory({title:x.title,...d});}catch(e:any){if(live.current&&n===historyGeneration.current)setError(e.message);}}
 const rows=items.filter(x=>(archived||x.status!=='Archiviert')&&(!query||[x.title,x.insurer,x.policyNumber,x.type].join(' ').toLowerCase().includes(query.toLowerCase())));
 function csv(){const cell=(v:any)=>{const s=String(v??'');return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';};const cols=Object.keys(labels).filter(x=>x!=='notes');const text=[cols.map(k=>labels[k]),...rows.map(x=>cols.map(k=>k.endsWith('Until')||k==='validFrom'?x[k]?.slice(0,10)||'':x[k]))].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Versicherungen.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const transitions:Record<string,string[]>={Entwurf:['Entwurf','Aktiv','Archiviert'],Aktiv:['Aktiv','Beendet','Archiviert'],Beendet:['Beendet','Archiviert'],Archiviert:['Archiviert']};
 return <section className="card" style={{marginTop:16}}><h2>Versicherungen · {party.name}</h2><p className="muted">Policen, Versicherungssummen und Jahresprämien in EUR. Vertragsende und Kündigungstermin werden manuell gepflegt; Status und Fristen sind getrennt. Die Erfassung löst keine Zahlung oder Kündigung aus. Nachweisdokumente bleiben im NU-Management.</p><div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><button className="btn" disabled={busy||party.profile.archived} onClick={()=>choose()}>+ Police</button><input aria-label="Policen suchen" placeholder="Police / Versicherer suchen" value={query} disabled={busy||dirty} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Archivierte anzeigen</label><button className="btn" disabled={busy} onClick={()=>{if(choose())void load();}}>Aktualisieren</button><button className="btn" disabled={busy||!rows.length} onClick={csv}>CSV</button><Link className="btn" to="/buro/nachunternehmer">Versicherungsnachweise im NU-Management</Link></div>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Police / Versicherer','Art / Status','Versicherungssumme EUR','Jahresprämie EUR','Vertragsende','Kündigung bis','Aktion'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.title}<div>{x.insurer} · {x.policyNumber}</div></td><td>{x.type}<div>{x.status}</div></td><td>{x.coverage==null?'—':Number(x.coverage).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{x.annualPremium==null?'—':Number(x.annualPremium).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{x.validUntil?.slice(0,10)||'Ohne Termin'}<div>{x.expiry}</div></td><td>{x.cancellationUntil?.slice(0,10)||'Ohne Termin'}<div>{x.cancellation}</div></td><td><button className="btn" disabled={busy} onClick={()=>choose(x)}>Öffnen</button><button className="btn" disabled={busy} onClick={()=>void showHistory(x)}>Verlauf</button></td></tr>)}{!rows.length&&<tr><td colSpan={7}>{busy?'Wird geladen …':'Keine Policen für diesen Filter.'}</td></tr>}</tbody></table></div>
 {(selected||!party.profile.archived)&&<form onSubmit={save} style={{marginTop:16}}><h3>{selected?selected.title:'Neue Police'}</h3><fieldset disabled={busy||selected?.status==='Archiviert'} style={{border:0,padding:0,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>
 {(['title','insurer','policyNumber'] as const).map(k=><label key={k}>{labels[k]}<input style={{width:'100%'}} required maxLength={k==='policyNumber'?100:250} value={form[k]} onChange={e=>field(k,e.target.value)}/></label>)}
 <label>Versicherungsart<select style={{width:'100%'}} value={form.type} onChange={e=>field('type',e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Status<select style={{width:'100%'}} value={form.status} disabled={!selected} onChange={e=>field('status',e.target.value)}>{(selected?transitions[selected.status]||statuses:['Entwurf']).map(t=><option key={t}>{t}</option>)}</select></label>
 {(['validFrom','validUntil','cancellationUntil'] as const).map(k=><label key={k}>{labels[k]}<input style={{width:'100%'}} type="date" required={k==='validFrom'} min={k==='validUntil'?form.validFrom:undefined} max={k==='cancellationUntil'&&form.validUntil?form.validUntil:undefined} value={form[k]} onChange={e=>field(k,e.target.value)}/></label>)}
 {(['coverage','annualPremium'] as const).map(k=><label key={k}>{labels[k]}<input style={{width:'100%'}} inputMode="decimal" pattern="[0-9]{1,12}([.,][0-9]{1,2})?" value={form[k]} onChange={e=>field(k,e.target.value)}/></label>)}
 <label>Bemerkung<textarea style={{width:'100%'}} rows={3} maxLength={5000} value={form.notes} onChange={e=>field('notes',e.target.value)}/></label><button className="btn btn-primary" type="submit" disabled={!!selected&&!dirty}>Speichern</button></fieldset><button type="button" className="btn" disabled={busy} onClick={()=>choose()}>Schließen / zurücksetzen</button>{selected?.status==='Archiviert'&&<p className="muted">Archivierte Police ist gegen Änderungen gesperrt.</p>}{party.profile.archived&&<p className="muted">Kontakt archiviert: bestehende Policen können weiter gepflegt werden; neue Policen erst nach Aktivierung des Kontakts.</p>}</form>}
 {history&&<section><h3>Pflegeverlauf · {history.title}</h3><button className="btn" onClick={()=>setHistory(undefined)}>Schließen</button><p className="muted">Bis zu 100 Änderungen.</p>{history.items.map((h:any)=><details key={h.id}><summary>{new Date(h.createdAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})} · {h.action==='CONTACT_INSURANCE_CREATE'?'Angelegt':'Geändert'}</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{[['Vorher',h.meta?.before],['Nachher',h.meta?.after]].map(([label,row]:any)=><div key={label}><strong>{label}</strong>{row?Object.entries(labels).map(([k,name])=><p key={k}>{name}: {k.endsWith('Until')||k==='validFrom'?row[k]?.slice(0,10)||'—':row[k]??'—'}</p>):<p>—</p>}</div>)}</div></details>)}</section>}
 </section>;
}
