import React from 'react';import {Link} from 'react-router-dom';import {useProject} from '../../store/useProject';import {officeAddonRequest as request} from './OfficeAddons';
const fmt=(v:any)=>new Date(v).toLocaleString('de-DE',{timeZone:'Europe/Berlin'});
export default function ContactCommunication({party,onBusyChange}:{party:any;onBusyChange:(v:boolean)=>void}){
 const {getSelectedProject}=useProject(),project=getSelectedProject(),projectId=String(project?.id||''),base='/api/business-contacts/'+encodeURIComponent(party.id)+'/communication';
 const [data,setData]=React.useState<any>(),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[archived,setArchived]=React.useState(false),[query,setQuery]=React.useState(''),[candidates,setCandidates]=React.useState<any>(),[candidate,setCandidate]=React.useState(''),[candidateBusy,setCandidateBusy]=React.useState(false),[detail,setDetail]=React.useState<any>(),[history,setHistory]=React.useState<any>();
 const live=React.useRef(true),generation=React.useRef(0),candidateGeneration=React.useRef(0),detailGeneration=React.useRef(0),historyGeneration=React.useRef(0),guard=React.useRef(false);
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);setError('');try{const d=await request(base+'?includeArchived=true');if(live.current&&n===generation.current)setData(d);}catch(e:any){if(live.current&&n===generation.current){setData(undefined);setDetail(undefined);setHistory(undefined);setError(e.message);}}finally{if(live.current&&n===generation.current)setBusy(false);}},[base]);
 React.useEffect(()=>{live.current=true;void load();return()=>{live.current=false;generation.current++;candidateGeneration.current++;detailGeneration.current++;historyGeneration.current++;};},[load]);
 React.useEffect(()=>{setCandidates(undefined);setCandidate('');setCandidateBusy(false);candidateGeneration.current++;},[projectId]);
 React.useEffect(()=>{onBusyChange(busy);return()=>onBusyChange(false);},[busy,onBusyChange]);
 async function loadCandidates(){if(!projectId)return;const n=++candidateGeneration.current;setCandidateBusy(true);setCandidates(undefined);setCandidate('');setError('');try{const d=await request(base+'/candidates?projectId='+encodeURIComponent(projectId));if(live.current&&n===candidateGeneration.current)setCandidates(d);}catch(e:any){if(live.current&&n===candidateGeneration.current)setError(e.message);}finally{if(live.current&&n===candidateGeneration.current)setCandidateBusy(false);}}
 async function mutate(path:string,body:any,method='POST'){if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');try{await request(path,{method,body:JSON.stringify(body)});if(!live.current)return;detailGeneration.current++;historyGeneration.current++;candidateGeneration.current++;setDetail(undefined);setHistory(undefined);setCandidates(undefined);setCandidate('');setCandidateBusy(false);await load();if(live.current)setMessage('Kontaktzuordnung gespeichert.');}catch(e:any){if(live.current)setError(e.message);}finally{guard.current=false;if(live.current)setBusy(false);}}
 function associate(){const c=candidates?.items.find((x:any)=>x.id===candidate);if(!c)return;void mutate(base,{threadId:c.id,...(c.link?.archived?{revision:c.link.revision}:{})});}
 function unlink(x:any){if(window.confirm('Kontaktzuordnung entfernen? Konversation, Nachrichten und Dokumente bleiben in der Projektkommunikation erhalten.'))void mutate(base+'/'+encodeURIComponent(x.threadId),{revision:x.revision},'DELETE');}
 async function open(x:any){const n=++detailGeneration.current;setDetail(undefined);setError('');try{const d=await request(base+'/'+encodeURIComponent(x.threadId));if(live.current&&n===detailGeneration.current)setDetail(d);}catch(e:any){if(live.current&&n===detailGeneration.current)setError(e.message);}}
 async function showHistory(x:any){const n=++historyGeneration.current;setHistory(undefined);setError('');try{const d=await request(base+'/'+encodeURIComponent(x.threadId)+'/history');if(live.current&&n===historyGeneration.current)setHistory(d);}catch(e:any){if(live.current&&n===historyGeneration.current)setError(e.message);}}
 const rows=(data?.items||[]).filter((x:any)=>(archived||!x.archived)&&(!query||[x.thread.subject,x.thread.project.code,x.thread.project.name,...x.thread.participants].join(' ').toLowerCase().includes(query.toLowerCase())));
 function csv(){const cell=(v:any)=>{const s=String(v??'');return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';};const body=[['Projekt','Betreff','Teilnehmer','Nachrichten','Anhänge','Aktualisiert','Kontaktzuordnung'],...rows.map((x:any)=>[x.thread.project.code+' · '+x.thread.project.name,x.thread.subject,x.thread.participants.join(', '),x.thread._count.messages,x.thread._count.attachments,fmt(x.thread.updatedAt),x.archived?'Entfernt':'Aktiv'])].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+body],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Kontaktkommunikation.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="card" style={{marginTop:16}}><h2>Kommunikationshistorie · {party.name}</h2><p className="muted">Bewusst zugeordnete Projektkonversationen aus Ihren freigegebenen Projekten. Die Ansicht liest bestehende Nachrichten; Zuordnungen versenden keine Nachrichten und ändern keinen Lesestatus.</p><div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><input placeholder="Betreff / Projekt / Teilnehmer suchen" aria-label="Kontaktkommunikation suchen" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Entfernte Zuordnungen anzeigen</label><button className="btn" disabled={busy} onClick={()=>void load()}>Aktualisieren</button><button className="btn" disabled={busy||!rows.length} onClick={csv}>CSV</button><Link className="btn" to="/buro/kommunikation">Projektkommunikation öffnen</Link></div>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {data?.canEdit&&<div className="card" style={{marginTop:12}}><h3>Konversation zuordnen</h3><p>Ausgewähltes Projekt: {[project?.code,project?.name].filter(Boolean).join(' · ')||'Bitte Projekt auswählen'}</p><button className="btn" disabled={busy||candidateBusy||!projectId||party.profile.archived} onClick={()=>void loadCandidates()}>{candidateBusy?'Wird geladen …':'Projektkonversationen laden'}</button><select aria-label="Konversation auswählen" value={candidate} disabled={busy||candidateBusy||party.profile.archived} onChange={e=>setCandidate(e.target.value)}><option value="">Konversation auswählen</option>{candidates?.items.map((x:any)=><option key={x.id} value={x.id} disabled={x.link&&!x.link.archived}>{x.subject||'Ohne Betreff'} · {x._count.messages} Nachrichten{x.link?(x.link.archived?' · Zuordnung wiederherstellen':' · bereits zugeordnet'):''}</option>)}</select><button className="btn btn-primary" disabled={busy||candidateBusy||!candidate||party.profile.archived} onClick={associate}>Zuordnen / wiederherstellen</button>{candidates&&!candidates.items.length&&<p>Keine Konversationen im ausgewählten Projekt.</p>}{party.profile.archived&&<p className="muted">Neue Zuordnungen erst nach Aktivierung des Kontakts.</p>}</div>}
 <div style={{overflowX:'auto',marginTop:12}}><table style={{width:'100%'}}><thead><tr>{['Projekt','Betreff / Teilnehmer','Nachrichten / Anhänge','Aktualisiert','Zuordnung / Aktion'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((x:any)=><tr key={x.threadId}><td>{x.thread.project.code}<div>{x.thread.project.name}</div></td><td>{x.thread.subject||'Ohne Betreff'}<div>{x.thread.participants.join(', ')}</div></td><td>{x.thread._count.messages} / {x.thread._count.attachments}</td><td>{fmt(x.thread.updatedAt)}</td><td>{x.archived?'Entfernt':'Aktiv'} <button className="btn" disabled={busy} onClick={()=>void open(x)}>Lesen</button><button className="btn" disabled={busy} onClick={()=>void showHistory(x)}>Zuordnungsverlauf</button>{data.canEdit&&!x.archived&&<button className="btn" disabled={busy} onClick={()=>unlink(x)}>Zuordnung entfernen</button>}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>{busy?'Wird geladen …':'Keine zugeordneten Konversationen in Ihren freigegebenen Projekten.'}</td></tr>}</tbody></table></div>
 {detail&&<section className="card" style={{marginTop:12}}><h3>{detail.thread.subject||'Ohne Betreff'} · {detail.thread.project.code}</h3><button className="btn" onClick={()=>{detailGeneration.current++;setDetail(undefined);}}>Schließen</button><p className="muted">{detail.messages.length} von {detail.thread._count.messages} Nachrichten, höchstens die letzten 100. Vollständige Pflege in der Projektkommunikation.</p>{detail.messages.map((m:any)=><article key={m.id} style={{padding:'12px 0',borderBottom:'1px solid var(--border,#e2e8f0)'}}><strong>{m.fromName}</strong> · {fmt(m.createdAt)}<div>An: {m.toList.join(', ')}{m.ccList.length?' · CC: '+m.ccList.join(', '):''}</div>{m.subject&&<p><strong>{m.subject}</strong></p>}<div style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:400,overflow:'auto'}}>{m.body}</div>{m.bodyTruncated&&<p className="muted">Text auf 20.000 Zeichen gekürzt; vollständige Nachricht in der Projektkommunikation.</p>}</article>)}<h4>Anhänge ({detail.attachments.length} von {detail.thread._count.attachments}, höchstens 100)</h4>{detail.attachments.map((a:any)=><p key={a.id}>{a.name}{!a.documentAvailable?' · Kein verfügbares Projektdokument':''}</p>)}</section>}
 {history&&<section className="card"><h3>Zuordnungsverlauf</h3><button className="btn" onClick={()=>{historyGeneration.current++;setHistory(undefined);}}>Schließen</button><p className="muted">Bis zu 100 Zuordnungsänderungen.</p>{history.items.map((h:any)=><p key={h.id}>{fmt(h.createdAt)} · {({CONTACT_COMMUNICATION_LINK:'Zugeordnet',CONTACT_COMMUNICATION_UNLINK:'Zuordnung entfernt',CONTACT_COMMUNICATION_RESTORE:'Zuordnung wiederhergestellt'} as any)[h.action]} · Version {h.meta?.after?.revision}</p>)}</section>}
 </section>;
}
