import React from 'react';import {Link} from 'react-router-dom';import {officeAddonRequest as request} from './OfficeAddons';import {useMasterCatalog} from './useMasterCatalog';
export default function DiaryTimeExport({projectId,month}:{projectId:string;month:string}){
 const catalog=useMasterCatalog('TIME_TYPE'),[timeTypeId,setType]=React.useState(''),[data,setData]=React.useState<any>(),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[open,setOpen]=React.useState(false);
 const seq=React.useRef(0),guard=React.useRef(false),key=projectId+'|'+month+'|'+timeTypeId,owner=React.useRef(key);owner.current=key;
 React.useEffect(()=>{setData(undefined);setError('');seq.current++;},[key]);
 React.useEffect(()=>()=>{seq.current++;},[]);
 const query='projectId='+encodeURIComponent(projectId)+'&month='+encodeURIComponent(month)+'&timeTypeId='+encodeURIComponent(timeTypeId);
 async function preview(){if(guard.current)return;guard.current=true;setBusy(true);setError('');setData(undefined);const n=++seq.current,k=key;try{const d=await request('/api/diary-time-export?'+query);if(n===seq.current&&owner.current===k)setData({...d,key:k});}catch(e:any){if(n===seq.current&&owner.current===k)setError(e.message);}finally{guard.current=false;setBusy(false);}}
 async function csv(){if(guard.current||data?.key!==key)return;guard.current=true;setBusy(true);setError('');const k=key;try{const d=await request('/api/diary-time-export/csv?'+query+'&expectedFingerprint='+encodeURIComponent(data.fingerprint));if(owner.current!==k)return;const url=URL.createObjectURL(new Blob([d.csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=d.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){if(owner.current===k){setError(e.message);setData(undefined);}}finally{guard.current=false;setBusy(false);}}
 const current=data?.key===key?data:undefined;
 return <section className="card" style={{padding:14}}><button className="btn" aria-expanded={open} onClick={()=>setOpen(!open)}>Zeiterfassung · CSV-Export {open?'schließen':'öffnen'}</button>{open&&<><p className="muted">Nur freigegebene Tagesberichte. Die gewählte Zeitart gilt für alle exportierten Personalzeilen; sie verändert die Originalberichte nicht. Keine automatische Zeitbuchung oder Lohnabrechnung. Namen und IDs stammen aus der Quelle und müssen vor dem Import geprüft werden.</p><div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><label>Zeitart <select disabled={busy} value={timeTypeId} onChange={e=>setType(e.target.value)}><option value="">Zeitart auswählen</option>{catalog.items.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.label}</option>)}</select></label><Link className="btn" to="/buro/stammdaten?art=TIME_TYPE">Zeitarten pflegen</Link><button className="btn" disabled={busy||!timeTypeId||!projectId} onClick={()=>void preview()}>{busy?'Wird geprüft …':'Vorschau prüfen'}</button><button className="btn" disabled={busy||!current?.canExport} onClick={()=>void csv()}>CSV herunterladen</button></div>{catalog.error&&<p role="alert">{catalog.error}</p>}{error&&<p role="alert">{error}</p>}{current&&<><p>{current.reportCount} freigegebene Berichte · {current.rows.length} Personalzeilen · {current.totalMinutes} Netto-Minuten. {current.issues.length?'Export gesperrt: Zeitzeilen prüfen.':''}</p><p className="muted">Netto-Stunden ohne Uhrzeiten werden auf ganze Minuten gerundet. Fließtext und reine Maschinenzeilen werden nicht als Personalzeiten exportiert. Das CSV ist ein allgemeines Austauschformat; der Import muss zur Zielsoftware passen.</p>{current.issues.map((x:any,i:number)=><p role="alert" key={'e'+i}>{x.report} / {x.line?'Zeile '+x.line:'Bericht'}: {x.error}</p>)}{current.skipped.map((x:any,i:number)=><p className="muted" key={'s'+i}>{x.report}{x.line?' / Zeile '+x.line:''}: {x.reason}</p>)}<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Datum','Mitarbeiter','Beginn / Ende','Pause','Netto Min.','Zeitart','Quelle'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{current.rows.map((r:any,i:number)=><tr key={i}><td>{r.date}</td><td>{r.employee}</td><td>{r.start||'–'} / {r.end||'–'}</td><td>{r.breakMinutes}</td><td>{r.netMinutes}</td><td>{r.timeType}</td><td>{r.report} / {r.line}</td></tr>)}</tbody></table></div></>}</>}</section>;
}
