import React from "react";
import {Link} from "react-router-dom";
import {officeAddonRequest as request} from "./OfficeAddons";
const labels:Record<string,string>={ABGELAUFEN:"Überfällig",BALD_FAELLIG:"Innerhalb von 30 Tagen",GUELTIG:"Später fällig",OHNE_DATUM:"Termin fehlt"};
export default function MachineDeadlines(){
 const [items,setItems]=React.useState<any[]>([]),[busy,setBusy]=React.useState(false),[error,setError]=React.useState("");
 const [query,setQuery]=React.useState(""),[status,setStatus]=React.useState(""),[kind,setKind]=React.useState("");
 const generation=React.useRef(0);
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);setError("");try{const data=await request("/api/resource-costs/machine-deadlines");if(n===generation.current)setItems(data.items||[]);}catch(e:any){if(n===generation.current)setError(e.message);}finally{if(n===generation.current)setBusy(false);}},[]);
 React.useEffect(()=>{void load();return()=>{generation.current++;};},[load]);
 const visible=items.filter(x=>(!status||x.expiry.status===status)&&(!kind||(kind==="TERMIN"?x.kind.startsWith("TERMIN:"):x.kind===kind))&&[x.machineName,x.serial,x.location,x.projectId,x.title].join(" ").toLowerCase().includes(query.toLowerCase()));
 const kindLabel=(x:any)=>x.kind==="SERVICE"?"Service":x.kind==="PRUEFUNG"?"Prüfung":x.title||"Geplanter Termin";
 function csv(){const cell=(v:any)=>{const s=String(v??"");return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":"")+s.replace(/"/g,'""')+'"';};const rows=[["Gerät","Seriennummer","Projekt","Terminart","Datum","Friststatus","Quelle","Prüfergebnis"],...visible.map(x=>[x.machineName,x.serial,x.projectId,kindLabel(x),x.date,labels[x.expiry.status],x.source,x.inspectionResult])];const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(r=>r.map(cell).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="Maschinen-Fristen.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="card"><div className="rlc-page-toolbar" style={{flexWrap:"wrap"}}><strong>Service- und Prüftermine</strong><input className="rlc-page-toolbar__search" aria-label="Geräte suchen" placeholder="Gerät, Seriennummer oder Standort …" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Friststatus" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle Fristen</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Terminart" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Alle Terminarten</option><option value="SERVICE">Service</option><option value="PRUEFUNG">Prüfung</option><option value="TERMIN">Geplant / offen</option></select><button className="btn" disabled={busy} onClick={()=>void load()}>Aktualisieren</button><button className="btn" disabled={!visible.length} onClick={csv}>CSV exportieren</button></div>
 {error&&<div className="card" role="alert">{error}</div>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:10,padding:12}}>{Object.entries(labels).map(([v,l])=><button className="card" key={v} onClick={()=>setStatus(status===v?"":v)}><strong>{items.filter(x=>x.expiry.status===v).length}</strong><div>{l}</div></button>)}</div>
 <p className="muted">Servicetermin aus dem Maschinenstamm, Prüftermin aus dem letzten abgeschlossenen Prüfnachweis. Geplante und offene Vorgänge werden separat angezeigt. Termin fehlt bedeutet, dass kein Datum hinterlegt ist. Die Anzeige ist keine Freigabe zum Betrieb.</p>
 <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Gerät","Termin","Datum / Frist","Prüfergebnis","Vorgang"].map(s=><th key={s} style={{textAlign:"left",padding:10}}>{s}</th>)}</tr></thead><tbody>{visible.map(x=><tr key={x.id}><td style={{padding:10}}><strong>{x.machineName}</strong><div className="muted">{x.serial} · {x.location}</div></td><td style={{padding:10}}>{kindLabel(x)}<div className="muted">{x.source}</div></td><td style={{padding:10}}>{x.date||"–"}<div>{labels[x.expiry.status]}{x.invalidDate?" · Bestandsdatum ungültig":""}</div></td><td style={{padding:10}}>{x.inspectionResult||"–"}{x.evidenceLocked&&<div className="muted">Nachweis gesperrt</div>}</td><td style={{padding:10}}><Link className="btn" to={"/buro/maschinenverwaltung?bereich="+(x.recordId?"wartung&maintenanceId="+encodeURIComponent(x.recordId):"maschinen")}>Öffnen</Link></td></tr>)}</tbody></table>{!visible.length&&<div className="rlc-page-empty">{busy?"Termine werden geladen …":"Keine Termine für diese Auswahl."}</div>}</div></div>;
}
