import React from 'react';import {Link,useSearchParams} from 'react-router-dom';import {officeAddonRequest as request} from './OfficeAddons';
const kinds:Record<string,string>={UNIT:'Einheiten',LICENSE_CLASS:'Führerscheintypen',HAZARD_CLASS:'Gefahrenklassen',COST_CENTER_AREA:'Kostenstellenbereiche',TIME_TYPE:'Zeitarten'};
const blank=()=>({code:'',label:'',symbol:'',notes:''});
export default function MasterCatalog(){
 const [params,setParams]=useSearchParams();const kind=params.get('art')&&kinds[params.get('art')!]?params.get('art')!:'UNIT';
 const [data,setData]=React.useState<any>(),[selected,setSelected]=React.useState<any>(),[form,setForm]=React.useState(blank()),[dirty,setDirty]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[history,setHistory]=React.useState<any>(),[query,setQuery]=React.useState(''),[archived,setArchived]=React.useState(false);
 const generation=React.useRef(0),guard=React.useRef(false),historyGeneration=React.useRef(0),latestKind=React.useRef(kind);latestKind.current=kind;
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);try{const d=await request('/api/master-catalog?kind='+kind+'&includeInactive=true');if(n===generation.current)setData({...d,kind});}catch(e:any){if(n===generation.current){setData(undefined);setError(e.message);}}finally{if(n===generation.current)setBusy(false);}},[kind]);
 React.useEffect(()=>{setData(undefined);setSelected(undefined);setForm(blank());setDirty(false);setHistory(undefined);setError('');setMessage('');void load();return()=>{generation.current++;historyGeneration.current++;};},[load]);
 React.useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 const current=data?.kind===kind?data:undefined;
 const visible=(current?.items||[]).filter((x:any)=>(archived||x.active)&&[x.code,x.label,x.symbol,x.notes].join(' ').toLocaleLowerCase('de-DE').includes(query.toLocaleLowerCase('de-DE')));
 function choose(row?:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setSelected(row);setForm(row?{code:row.code,label:row.label,symbol:row.symbol||'',notes:row.notes||''}:blank());setDirty(false);setHistory(undefined);historyGeneration.current++;setError('');setMessage('');}
 async function write(fn:()=>Promise<any>,after:(d:any)=>void){if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');const owner=kind;try{const d=await fn();if(latestKind.current===owner){after(d);await load();setMessage('Katalogeintrag gespeichert.');}}catch(e:any){if(latestKind.current===owner)setError(e.message);}finally{guard.current=false;setBusy(false);}}
 function save(e:React.FormEvent){e.preventDefault();void write(()=>request('/api/master-catalog'+(selected?'/'+encodeURIComponent(selected.id):''),{method:selected?'PUT':'POST',body:JSON.stringify({...form,kind,...(selected?{expectedUpdatedAt:selected.updatedAt}:{})})}),d=>{setSelected(d.item);setForm({code:d.item.code,label:d.item.label,symbol:d.item.symbol||'',notes:d.item.notes||''});setDirty(false);});}
 function archive(row:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;if(!window.confirm(row.active?'Eintrag archivieren? Bestehende Daten bleiben erhalten.':'Eintrag wieder aktivieren?'))return;void write(()=>request('/api/master-catalog/'+encodeURIComponent(row.id),{method:row.active?'DELETE':'PUT',body:JSON.stringify({expectedUpdatedAt:row.updatedAt,...(!row.active?{active:true}:{})})}),()=>{setSelected(undefined);setForm(blank());setDirty(false);setHistory(undefined);});}
 async function showHistory(row:any){const n=++historyGeneration.current;setError('');try{const d=await request('/api/master-catalog/'+encodeURIComponent(row.id)+'/history');if(n===historyGeneration.current)setHistory({title:row.code,...d});}catch(e:any){if(n===historyGeneration.current)setError(e.message);}}
 function csv(){const cell=(v:any)=>{const s=String(v??'');return '"'+(/^\s*[=+\-@]|^[\t\r\n]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';};const text='\uFEFF'+[['Katalog','Code','Bezeichnung','Symbol','Bemerkung','Status'],...visible.map((x:any)=>[kinds[kind],x.code,x.label,x.symbol,x.notes,x.active?'Aktiv':'Archiviert'])].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Stammdaten-'+kind+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="card"><header className="rlc-page-hero rlc-page-hero--split"><div><div className="rlc-page-hero__eyebrow">Büro & Verwaltung · Firmenstammdaten</div><h1>Stammdaten-Kataloge</h1><p>{kinds[kind]} · gemeinsame Auswahlwerte für die Firma</p></div><button className="rlc-page-hero__button" disabled={busy||!current?.canEdit} onClick={()=>choose()}>+ Eintrag</button></header>
 <div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}>{Object.entries(kinds).map(([k,label])=><button className="btn" key={k} disabled={busy} aria-pressed={k===kind} onClick={()=>{if(k===kind)return;if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setParams({art:k});}}>{label}</button>)}<button className="btn" disabled={busy} onClick={()=>void load()}>Aktualisieren</button><button className="btn" disabled={busy||!current} onClick={csv}>CSV</button></div>
 <p className="muted">Die Firma pflegt ihre eigenen Codes und Bezeichnungen. Einheiten werden in der Materialverwaltung vorgeschlagen, Bereiche im Kostenstellen-Editor. Bestehende Bezeichnungen bleiben erhalten. Führerscheintypen und Gefahrenklassen sind ein manueller Referenzkatalog; eine Einsatzfreigabe oder fachliche Prüfung wird daraus nicht automatisch abgeleitet.</p>
 <div className="rlc-page-toolbar"><Link className="btn" to="/buro/materialverwaltung?bereich=material">Materialverwaltung</Link><Link className="btn" to="/buchhaltung/kostenstellen">Kostenstellen</Link><Link className="btn" to="/buro/personalnachweise">Personalnachweise</Link>{(kind==="LICENSE_CLASS"||kind==="HAZARD_CLASS")&&<Link className="btn" to={"/buro/zuordnungen?art="+kind}>Zuordnungen öffnen</Link>}</div>
 {error&&<div className="card" role="alert">{error}</div>}{message&&<div className="card" role="status">{message}</div>}
 {current?.canEdit&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:12}}>{[['code','Code'],['label','Bezeichnung'],...(kind==='UNIT'?[['symbol','Einheitensymbol']]:[])] .map(([key,label])=><label key={key}>{label}<input style={{width:'100%'}} required={key!=='symbol'} readOnly={key==='code'&&!!selected} value={(form as any)[key]} onChange={e=>{setForm({...form,[key]:e.target.value});setDirty(true);}}/></label>)}<label>Bemerkung<textarea style={{width:'100%'}} rows={2} value={form.notes} onChange={e=>{setForm({...form,notes:e.target.value});setDirty(true);}}/></label></div><div className="rlc-page-toolbar"><button className="btn" type="submit">{selected?'Änderungen speichern':'Eintrag anlegen'}</button><button className="btn" type="button" onClick={()=>choose()}>Abbrechen</button>{selected&&!selected.active&&<span>Eintrag bleibt archiviert bis zur Aktivierung.</span>}</div></fieldset></form>}
 <div className="rlc-page-toolbar"><input placeholder="Code / Bezeichnung suchen" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Archivierte anzeigen</label><span>{visible.length} Einträge</span></div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Code','Bezeichnung','Symbol','Bemerkung','Status','Aktion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((x:any)=><tr key={x.id}><td>{x.code}</td><td>{x.label}</td><td>{x.symbol||'–'}</td><td title={x.notes||''}>{x.notes?x.notes.slice(0,120):'–'}</td><td>{x.active?'Aktiv':'Archiviert'}</td><td>{current?.canEdit&&<><button className="btn" disabled={busy} onClick={()=>choose(x)}>Bearbeiten</button><button className="btn" disabled={busy} onClick={()=>archive(x)}>{x.active?'Archivieren':'Aktivieren'}</button></>}<button className="btn" onClick={()=>void showHistory(x)}>Verlauf</button></td></tr>)}{!visible.length&&<tr><td colSpan={6}>{busy?'Wird geladen …':!current?'Katalog nicht verfügbar.':'Keine Einträge für diesen Filter.'}</td></tr>}</tbody></table></div>
 {history&&<section className="card"><h2>Verlauf · {history.title}</h2><button className="btn" onClick={()=>setHistory(undefined)}>Schließen</button><p className="muted">Bis zu 100 Änderungen.</p>{history.items.map((h:any)=><p key={h.id}>{new Date(h.createdAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})} · {({'MASTER_CATALOG_CREATE':'Angelegt','MASTER_CATALOG_UPDATE':'Geändert','MASTER_CATALOG_ARCHIVE':'Archiviert','MASTER_CATALOG_RESTORE':'Aktiviert'} as any)[h.action]} · {h.meta?.before?.label||'–'} → {h.meta?.after?.label} · {h.meta?.after?.symbol||''}</p>)}</section>}
 </div>;
}
