import React from 'react';
import {Link} from 'react-router-dom';
import {officeAddonRequest as request} from './OfficeAddons';
import {nonWorkingLabels as labels,nonWorkingCSV,nonWorkingICS} from './nonWorkingCalendarExport';
const empty=()=>({date:'',toDate:'',title:'',kind:'FEIERTAG',location:'',notes:''});
export default function NonWorkingDays(){
 const [year,setYear]=React.useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric'}).format(new Date())),[items,setItems]=React.useState<any[]>([]),[canEdit,setCanEdit]=React.useState(false),[selected,setSelected]=React.useState<any>(),[form,setForm]=React.useState(empty()),[dirty,setDirty]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[history,setHistory]=React.useState<any>(),[query,setQuery]=React.useState(''),[location,setLocation]=React.useState(''),[kind,setKind]=React.useState(''),[archived,setArchived]=React.useState(false);
 const generation=React.useRef(0),guard=React.useRef(false),historyGeneration=React.useRef(0);
 const load=React.useCallback(async()=>{const n=++generation.current;setBusy(true);try{const d=await request('/api/calendar/non-working-days?year='+encodeURIComponent(year)+'&includeArchived=true');if(n===generation.current){setItems(d.items||[]);setCanEdit(d.canEdit);return d;}}catch(e:any){if(n===generation.current){setItems([]);setCanEdit(false);setError(e.message);}}finally{if(n===generation.current)setBusy(false);}},[year]);
 React.useEffect(()=>{setItems([]);setCanEdit(false);setError('');setHistory(undefined);void load();return()=>{generation.current++;historyGeneration.current++;};},[load]);
 React.useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 function choose(row?:any){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setSelected(row);setForm(row?{date:row.date,toDate:'',title:row.title,kind:row.kind,location:row.location,notes:row.notes}:empty());setDirty(false);setHistory(undefined);historyGeneration.current++;setError('');setMessage('');}
 async function write(fn:()=>Promise<any>,success:(d:any)=>void){if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');try{const d=await fn();success(d);await load();setMessage(d.items?`${d.items.length} Kalendereinträge gespeichert.`:'Kalendereintrag gespeichert.');}catch(e:any){setError(e.message);}finally{guard.current=false;setBusy(false);}}
 function save(e:React.FormEvent){e.preventDefault();void write(()=>request('/api/calendar/non-working-days'+(selected?'/'+encodeURIComponent(selected.id):''),{method:selected?'PUT':'POST',body:JSON.stringify({...form,toDate:selected||!form.toDate?undefined:form.toDate,...(selected?{expectedUpdatedAt:selected.updatedAt}:{})})}),d=>{const row=d.item||d.items[0];setSelected(row);setForm({date:row.date,toDate:'',title:row.title,kind:row.kind,location:row.location,notes:row.notes});setDirty(false);});}
 function archive(row:any){if(!window.confirm(row.active?'Ruhetag archivieren? Bestehende Einsätze bleiben erhalten.':'Ruhetag wieder aktivieren?'))return;if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;void write(()=>request('/api/calendar/non-working-days/'+encodeURIComponent(row.id),{method:row.active?'DELETE':'PUT',body:JSON.stringify({expectedUpdatedAt:row.updatedAt,...(!row.active?{active:true}:{})})}),()=>{setSelected(undefined);setForm(empty());setDirty(false);setHistory(undefined);});}
 async function showHistory(row:any){const n=++historyGeneration.current;setError('');try{const d=await request('/api/calendar/non-working-days/'+encodeURIComponent(row.id)+'/history');if(n===historyGeneration.current)setHistory({title:row.title,...d});}catch(e:any){if(n===historyGeneration.current)setError(e.message);}}
 const visible=items.filter(x=>x.date.startsWith(year+"-")&&(archived||x.active)&&(!kind||x.kind===kind)&&(!location||x.location===location)&&[x.date,x.title,x.location,x.notes].join(' ').toLocaleLowerCase('de-DE').includes(query.toLocaleLowerCase('de-DE')));
 const locations=[...new Set<string>(items.map(x=>x.location).filter(Boolean))].sort();
 function download(content:string,mime:string,name:string){const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function csv(){download(nonWorkingCSV(visible),'text/csv;charset=utf-8','Ruhetage-'+year+'.csv');}
 function ics(){download(nonWorkingICS(visible),'text/calendar;charset=utf-8','Ruhetage-'+year+'.ics');}
 return <div className="card"><header className="rlc-page-hero rlc-page-hero--split"><div><div className="rlc-page-hero__eyebrow">Büro & Verwaltung · Stammdaten</div><h1>Feiertage & Betriebsruhetage</h1><p>Firmenkalender für Feiertage und geplante Betriebsschließungen</p></div><button className="rlc-page-hero__button" disabled={busy||!canEdit} onClick={()=>choose()}>+ Ruhetag</button></header>
 <div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><Link className="btn" to="/buro/ressourcenplanung">Einsatzplanung</Link><label>Jahr <select value={year} disabled={busy} onChange={e=>{if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setDirty(false);setSelected(undefined);setForm(empty());setYear(e.target.value);}}>{Array.from({length:300},(_,i)=>String(1900+i)).map(y=><option key={y}>{y}</option>)}</select></label><button className="btn" disabled={busy} onClick={()=>void load()}>Aktualisieren</button><button className="btn" disabled={busy||!!error} onClick={csv}>CSV</button><button className="btn" disabled={busy||!!error} onClick={ics}>Kalenderdatei (.ics)</button></div>
 <p className="muted">Die Firma legt Datum und Geltungsbereich selbst fest. Ein leerer Geltungsbereich bedeutet firmenweit; regionale oder standortbezogene Einträge werden mit ihrer Bezeichnung angezeigt. Die Planung zeigt Hinweise und behält bestehende Einsätze bei. Stunden, Vergütung und Zuschläge werden hier nicht berechnet.</p>
 {error&&<div role="alert" className="card">{error}</div>}{message&&<div role="status" className="card">{message}</div>}
 {canEdit?<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:12}}>{[['date','Datum'],...(!selected?[['toDate','Bis einschließlich (optional)']]:[]),['title','Bezeichnung'],['location','Geltungsbereich / Standort']] .map(([key,label])=><label key={key}>{label}<input style={{width:'100%'}} type={key==='date'||key==='toDate'?'date':'text'} required={key==='date'||key==='title'} value={(form as any)[key]} onChange={e=>{setForm({...form,[key]:e.target.value});setDirty(true);}}/></label>)}<label>Art<select value={form.kind} onChange={e=>{setForm({...form,kind:e.target.value});setDirty(true);}}>{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Bemerkung<input style={{width:'100%'}} value={form.notes} onChange={e=>{setForm({...form,notes:e.target.value});setDirty(true);}}/></label></div><div className="rlc-page-toolbar"><button className="btn" type="submit">{selected?'Änderungen speichern':'Ruhetag / Zeitraum anlegen'}</button><button className="btn" type="button" onClick={()=>choose()}>Abbrechen</button>{selected&&!selected.active&&<span className="muted">Dieser Eintrag bleibt archiviert, bis er wieder aktiviert wird.</span>}</div></fieldset></form>:<p className="muted">Änderungen am Firmenkalender sind Administratoren vorbehalten.</p>}
 <div className="rlc-page-toolbar" style={{flexWrap:'wrap'}}><input placeholder="Suchen" value={query} onChange={e=>setQuery(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">Alle Arten</option>{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">Alle Geltungsbereiche</option>{locations.map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Archivierte anzeigen</label><span>{visible.length} Einträge</span></div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Datum','Bezeichnung','Art','Geltungsbereich','Status','Bemerkung','Aktion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(x=><tr key={x.id}><td>{x.date}</td><td>{x.title}</td><td>{labels[x.kind]}</td><td>{x.location||'Firmenweit'}</td><td>{x.active?'Aktiv':'Archiviert'}</td><td title={x.notes}>{x.notes?x.notes.slice(0,120):'–'}</td><td>{canEdit&&<><button className="btn" disabled={busy} onClick={()=>choose(x)}>Bearbeiten</button><button className="btn" disabled={busy} onClick={()=>archive(x)}>{x.active?'Archivieren':'Aktivieren'}</button></>}<button className="btn" onClick={()=>void showHistory(x)}>Verlauf</button></td></tr>)}{!visible.length&&<tr><td colSpan={7}>{busy?'Wird geladen …':error?'Kalender nicht verfügbar.':'Keine Einträge für diesen Filter.'}</td></tr>}</tbody></table></div>
 {history&&<section className="card"><h2>Verlauf · {history.title}</h2><button className="btn" onClick={()=>setHistory(undefined)}>Schließen</button><p className="muted">Bis zu 100 Änderungen.</p>{history.items.map((h:any)=><p key={h.id}>{new Date(h.createdAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})} · {({'NON_WORKING_DAY_CREATE':'Angelegt','NON_WORKING_DAY_UPDATE':'Geändert','NON_WORKING_DAY_ARCHIVE':'Archiviert','NON_WORKING_DAY_RESTORE':'Aktiviert'} as any)[h.action]} · {h.meta?.after?.date} · {h.meta?.after?.title}</p>)}</section>}
 </div>;
}
