import React from "react";
import {Link,useSearchParams} from "react-router-dom";
import {officeAddonRequest as request} from "./OfficeAddons";
const labels:Record<string,string>={ABGELAUFEN:"Abgelaufen",BALD_FAELLIG:"Innerhalb von 30 Tagen",GUELTIG:"Datum gültig",OHNE_DATUM:"Ohne Ablaufdatum"};
export default function PersonnelQualifications(){
 const [params]=useSearchParams();
 const [items,setItems]=React.useState<any[]>([]),[employees,setEmployees]=React.useState<any[]>([]),[selected,setSelected]=React.useState<any>();
 const [employeeId,setEmployeeId]=React.useState(""),[name,setName]=React.useState(""),[date,setDate]=React.useState("");
 const [busy,setBusy]=React.useState(false),[dirty,setDirty]=React.useState(false),[error,setError]=React.useState(""),[message,setMessage]=React.useState(""),[history,setHistory]=React.useState<any[]>([]);
 const [query,setQuery]=React.useState(""),[status,setStatus]=React.useState(""),[filterEmployee,setFilterEmployee]=React.useState("");
 const guard=React.useRef(false),generation=React.useRef(0);
 function populate(row?:any){setSelected(row);setEmployeeId(row?.employeeId||"");setName(row?.name||"");setDate(row?.validUntil?.slice(0,10)||"");setDirty(false);}
 const load=React.useCallback(async()=>{
  const n=++generation.current;setBusy(true);
  try{const d=await request("/api/personal/qualifications");if(n!==generation.current)return;setItems(d.items||[]);setEmployees(d.employees||[]);return d;}
  catch(e:any){if(n===generation.current)setError(e.message);}finally{if(n===generation.current)setBusy(false);}
 },[]);
 React.useEffect(()=>{let live=true;void load().then(d=>{if(live&&d){const id=params.get("certificateId");if(id)populate(d.items.find((x:any)=>x.id===id));}});return()=>{live=false;generation.current++;};},[load,params]);
 React.useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",f);return()=>window.removeEventListener("beforeunload",f);},[dirty]);
 React.useEffect(()=>{let live=true;setHistory([]);if(selected)request("/api/personal/qualifications/"+encodeURIComponent(selected.id)+"/history").then(d=>{if(live)setHistory(d.items||[]);}).catch(()=>{if(live)setHistory([{id:"error",error:true}]);});return()=>{live=false;};},[selected?.id,selected?.updatedAt]);
 function choose(row?:any){if(dirty&&!window.confirm("Ungespeicherte Änderungen verwerfen?"))return;populate(row);setError("");setMessage("");}
 async function save(e:React.FormEvent){
  e.preventDefault();if(guard.current||busy)return;guard.current=true;setBusy(true);setError("");setMessage("");
  try{const d=await request("/api/personal/"+encodeURIComponent(employeeId)+"/certificates"+(selected?"/"+encodeURIComponent(selected.id):""),{method:selected?"PUT":"POST",body:JSON.stringify({name,validUntil:date||null,...(selected?{expectedUpdatedAt:selected.updatedAt}:{})})});
   populate({...d.item,employee:employees.find(x=>x.id===employeeId)});await load();setMessage("Nachweis gespeichert.");
  }catch(e:any){setError(e.message);}finally{guard.current=false;setBusy(false);}
 }
 const visible=items.filter(x=>(!status||x.expiry.status===status)&&(!filterEmployee||x.employeeId===filterEmployee)&&[x.name,x.employee?.name,...(x.employee?.projects||[])].join(" ").toLowerCase().includes(query.toLowerCase()));
 function csv(){const cell=(v:any)=>{const s=String(v??"");return '"'+(/^[=+\-@\t\r]/.test(s)?"'":"")+s.replace(/"/g,'""')+'"';};const rows=[["Mitarbeiter","Nachweis","Gültig bis","Datumsstatus","Tage","Projekte"],...visible.map(x=>[x.employee?.name,x.name,x.validUntil?.slice(0,10),labels[x.expiry.status],x.expiry.days,x.employee?.projects?.join(", ")])];
  const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(r=>r.map(cell).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="Personal-Nachweise.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 return <div className="card"><header className="rlc-page-hero rlc-page-hero--split"><div><div className="rlc-page-hero__eyebrow">Büro & Verwaltung · Personal</div><h1>Nachweise & Fristen</h1><p>Attestationen und Qualifikationen aus der bestehenden Personalakte</p></div><button className="rlc-page-hero__button" disabled={busy} onClick={()=>choose()}>+ Nachweis</button></header>
 <div className="rlc-page-toolbar" style={{flexWrap:"wrap"}}><Link className="btn" to="/buro/personalverwaltung">Personalverwaltung</Link><Link className="btn" to={"/buro/zuordnungen?art=LICENSE_CLASS"+(employeeId?"&targetId="+encodeURIComponent(employeeId):"")}>Führerscheine &amp; Fristen</Link><input className="rlc-page-toolbar__search" aria-label="Nachweise suchen" placeholder="Mitarbeiter, Nachweis oder Projekt …" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Datumsstatus" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle Fristen</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Mitarbeiterfilter" value={filterEmployee} onChange={e=>setFilterEmployee(e.target.value)}><option value="">Alle Mitarbeiter</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn" disabled={busy} onClick={()=>{if(dirty&&!window.confirm("Ungespeicherte Änderungen verwerfen?"))return;populate();void load();}}>Aktualisieren</button><button className="btn" disabled={!visible.length} onClick={csv}>CSV exportieren</button></div>
 {error&&<div className="card" role="alert">{error}</div>}{message&&<div className="card" role="status">{message}</div>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,padding:14}}>{Object.entries(labels).map(([v,l])=><button className="card" key={v} onClick={()=>setStatus(status===v?"":v)}><strong>{items.filter(x=>x.expiry.status===v).length}</strong><div>{l}</div></button>)}</div>
 <p className="muted" style={{padding:"0 14px"}}>Fristen nach Kalendertag in Deutschland; ein Nachweis gilt am Ablaufdatum noch als datumsseitig gültig. Die Datumsanzeige bestätigt keine fachliche Prüfung. {employees.filter(e=>!items.some(x=>x.employeeId===e.id)).length} Mitarbeiter ohne erfassten Nachweis.</p>
 <div className="rlc-page-workspace" style={{gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,340px),1fr))",alignItems:"start"}}><section className="rlc-page-list"><div className="rlc-page-list-head">{visible.length} Nachweise</div><div className="rlc-page-list-scroll">{visible.map(x=><button className={"rlc-page-document"+(selected?.id===x.id?" is-active":"")} key={x.id} disabled={busy} onClick={()=>choose(x)}><strong>{x.employee?.name} · {x.name}</strong><div className="rlc-page-document-meta">{labels[x.expiry.status]} · {x.validUntil?.slice(0,10)||"Kein Datum"}</div></button>)}{!visible.length&&<div className="rlc-page-empty">{busy?"Wird geladen …":"Keine Nachweise für diese Auswahl."}</div>}</div></section>
 <section className="rlc-page-detail"><div className="rlc-page-detail-head"><h2>{selected?"Nachweis bearbeiten":"Neuer Nachweis"}</h2></div><form onSubmit={save} style={{padding:18,display:"grid",gap:14}}><fieldset disabled={busy} style={{border:0,padding:0,display:"grid",gap:14}}><label style={{display:"grid",gap:6}}>Mitarbeiter<select required disabled={!!selected} value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setDirty(true);}}><option value="">Mitarbeiter auswählen</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label style={{display:"grid",gap:6}}>Bezeichnung<input required maxLength={250} value={name} onChange={e=>{setName(e.target.value);setDirty(true);}}/></label><label style={{display:"grid",gap:6}}>Gültig bis<input type="date" value={date} onChange={e=>{setDate(e.target.value);setDirty(true);}}/></label><button className="btn btn-primary" disabled={!!selected&&!dirty}>Speichern</button></fieldset>
 {employeeId&&<Link className="btn" to={"/buro/personalverwaltung?bereich=mitarbeiter&employeeId="+encodeURIComponent(employeeId)}>Personalakte und Dokumente öffnen</Link>}<p className="muted">Dokumente und Aufbewahrungsregeln werden in der Personalakte gepflegt.</p></form>
 {selected&&<section style={{padding:18,borderTop:"1px solid var(--border,#e2e8f0)"}}><h3>Verlauf</h3>{history.map(h=><div key={h.id} style={{padding:"8px 0"}}>{h.error?<p role="alert">Verlauf nicht verfügbar.</p>:<><strong>{h.meta?.after?.name}</strong> · {new Date(h.createdAt).toLocaleString("de-DE")}<div className="muted">{h.meta?.after?.validUntil?.slice(0,10)||"Ohne Ablaufdatum"} · {h.userId}</div></>}</div>)}{!history.length&&<p className="muted">Für ältere Einträge beginnt der Verlauf mit der nächsten Änderung.</p>}</section>}
 </section></div></div>;
}
