import React from 'react';
import {apiUrl} from '../../lib/apiBase';
async function request(path:string,body:any){let token='';try{token=localStorage.getItem('rlc_token')||JSON.parse(localStorage.getItem('rlc_auth')||'{}').token||'';}catch{}const res=await fetch(apiUrl('/api/buero/bauzeitenplan/'+path),{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});const d=await res.json();if(!res.ok||d.ok===false)throw new Error(d.error||'Übernahme nicht verfügbar.');return d;}
type Props={projectId:string;task:{id:string;name:string;start:string|null;end:string|null;ressourcen:Record<string,number>};version:string;disabled:boolean;onClose:()=>void};
export default function PlanResourceHandoff({projectId,task,version,disabled,onClose}:Props){
 const [options,setOptions]=React.useState<any>(),[resourceType,setType]=React.useState('EMPLOYEE'),[resourceId,setId]=React.useState(''),[hours,setHours]=React.useState('8'),[from,setFrom]=React.useState(task.start?.slice(0,10)||''),[to,setTo]=React.useState(task.end?.slice(0,10)||''),[weekdays,setWeekdays]=React.useState([1,2,3,4,5]),[exclude,setExclude]=React.useState(true),[requirement,setRequirement]=React.useState(''),[preview,setPreview]=React.useState<any>(),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState('');
 const body={projectId,taskId:task.id,expectedVersion:version,resourceType,resourceId,hours:Number(hours),from,to,weekdays,excludeNonWorking:exclude,requirement};const signature=JSON.stringify(body),current=React.useRef(signature),guard=React.useRef(false);current.current=signature;
 React.useEffect(()=>{let live=true;setBusy(true);request('resource-options',{projectId}).then(d=>{if(live)setOptions(d);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;current.current='';};},[projectId]);
 React.useEffect(()=>{setPreview(undefined);setMessage('');},[signature]);
 async function run(commit:boolean){if(disabled||busy||guard.current)return;guard.current=true;setBusy(true);setError('');const captured=signature;
 try{const result=await request(commit?'resource-commit':'resource-preview',{...body,...(commit?{fingerprint:preview?.fingerprint}:{})});if(current.current!==captured)return;if(commit){setMessage(`${result.createdCount} neue Einsätze erstellt. Vorhandene Einsätze bleiben erhalten.`);setPreview(undefined);}else setPreview(result);}catch(e:any){if(current.current===captured)setError(e.message);}finally{guard.current=false;setBusy(false);}}
 const resources=resourceType==='EMPLOYEE'?options?.employees:options?.machines;const statuses:Record<string,string>={new:'Neu',existing:'Vorhanden – bleibt erhalten',weekday:'Wochentag ausgeschlossen',nonworking:'Ruhetag ausgeschlossen',overcapacity:'Mehr als 24 Planstunden',deleted:'Frühere Übernahme gelöscht – prüfen',moved:'Frühere Übernahme verschoben – prüfen'};
 return <section className="card" style={{marginTop:12}}><h3>Einsatz aus Bauzeitenplan</h3><p className="muted">{task.name} · Eine Person oder Maschine bewusst zuordnen. Bedarfsmengen sind keine Stunden. Die Übernahme erzeugt Tagesplanungen; spätere Planänderungen verändern diese nicht automatisch.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <fieldset disabled={disabled||busy||!options} style={{border:0,padding:0,margin:0,minWidth:0}}><div style={{display:'grid',gap:10}}>
 <label>Planbedarf <select value={requirement} onChange={e=>setRequirement(e.target.value)}><option value="">Freie Zuordnung</option>{Object.entries(task.ressourcen).map(([name,count])=><option key={name} value={name}>{name} · Bedarf {count}</option>)}</select></label>
 <label>Ressourcenart <select value={resourceType} onChange={e=>{setType(e.target.value);setId('');}}><option value="EMPLOYEE">Person</option><option value="MACHINE">Maschine</option></select></label>
 <label>Ressource <select value={resourceId} onChange={e=>setId(e.target.value)}><option value="">Bitte auswählen</option>{(resources||[]).map((r:any)=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>
 <label>Von <input type="date" value={from} min={task.start?.slice(0,10)} max={task.end?.slice(0,10)} onChange={e=>setFrom(e.target.value)}/></label><label>Bis <input type="date" value={to} min={task.start?.slice(0,10)} max={task.end?.slice(0,10)} onChange={e=>setTo(e.target.value)}/></label>
 <label>Planstunden pro Tag <input type="number" min="0.01" max="24" step="0.01" value={hours} onChange={e=>setHours(e.target.value)}/></label>
 <div>{['So','Mo','Di','Mi','Do','Fr','Sa'].map((label,n)=><label key={n} style={{marginRight:8}}><input type="checkbox" checked={weekdays.includes(n)} onChange={e=>setWeekdays(v=>e.target.checked?[...v,n]:v.filter(x=>x!==n))}/>{label}</label>)}</div>
 <label><input type="checkbox" checked={exclude} onChange={e=>setExclude(e.target.checked)}/> Eingetragene Firmenruhetage ausschließen</label><p className="muted">Alle eingetragenen Ruhetage werden berücksichtigt. Geltungsbereich und Baustelle in der Vorschau prüfen.</p>
 <button className="btn" onClick={()=>void run(false)} disabled={!resourceId||!from||!to}>Vorschau prüfen</button>
 </div></fieldset>
 {preview&&<><p>{preview.newCount} neue Tage · {preview.existingCount} vorhandene Tage</p><div style={{maxHeight:260,overflow:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Datum</th><th>Status</th><th>Stunden</th></tr></thead><tbody>{preview.days.map((d:any)=><tr key={d.date}><td>{d.date}</td><td>{statuses[d.status]}{d.nonWorking.length>0&&<div>{d.nonWorking.map((x:any)=>[x.title,x.location].filter(Boolean).join(' · ')).join('; ')}</div>}</td><td>{d.existingHours??d.requestedHours} · Gesamt bisher {d.totalHours}</td></tr>)}</tbody></table></div><button className="btn btn-primary" disabled={disabled||busy||preview.blocked||preview.newCount===0} onClick={()=>void run(true)}>Neue Einsätze übernehmen</button></>}
 <div style={{marginTop:10}}><button className="btn" disabled={busy} onClick={onClose}>Schließen</button> <a className="btn" href="/buro/ressourcenplanung">Einsatzplanung öffnen</a>{busy&&<span role="status"> Wird geprüft…</span>}</div></section>;
}
