import { RLC_PREIS_BIBLIOTHEK } from "../kalkulation/rlcPreisBibliothek";

/*
 * This audit intentionally does NOT compare a family price with a catalog row
 * generated by that same family. That only proves a circular copy is coherent.
 */
const counts = new Map<string, number>();
for (const item of RLC_PREIS_BIBLIOTHEK) {
  const origin = item.priceOrigin || "LEGACY_UNVERIFIED";
  counts.set(origin, (counts.get(origin) || 0) + 1);
}

const verified = counts.get("LIST_PRICE_VERIFIED") || 0;
const company = counts.get("COMPANY_CALIBRATION") || 0;
const derived = counts.get("DERIVED_FAMILY") || 0;
const legacy = counts.get("LEGACY_UNVERIFIED") || 0;
const auditable = verified + company;

console.log(
  [
    "TIEFBAU_PRICE_PROVENANCE",
    "ENTRIES=" + RLC_PREIS_BIBLIOTHEK.length,
    "LIST_PRICE_VERIFIED=" + verified,
    "COMPANY_CALIBRATION=" + company,
    "DERIVED_FAMILY=" + derived,
    "LEGACY_UNVERIFIED=" + legacy,
    "AUDITABLE_PRICE_SOURCES=" + auditable,
  ].join("|")
);

if (derived > 0) {
  console.error("PRICE_SOURCE_WARNING|DERIVED_FAMILY entries are search coverage only and cannot validate family prices.");
}
if (auditable === 0) {
  console.error("PRICE_SOURCE_GAP|No externally documented list-price or company-calibration entries are available yet.");
  process.exitCode = 1;
}
