import { calculateAutonomousUrkalkulation } from "../kalkulation/autonomous/autonomousUrkalkulationEngine";
const ctx:any={projectType:"Tiefbau",trade:"Tiefbau",difficulty:"medium",logisticsRisk:"medium",trafficRisk:"medium",durationRisk:"medium",marketFactor:1,distanceFactor:1,confidence:0.9,warnings:[]};
type R={lb:string,group:string,text:string,unit:string};
const rows:R[]=[
{lb:"000",group:"Allgemeine Baustelleneinrichtung",text:"Baustelle einrichten und räumen",unit:"psch"},
{lb:"000",group:"Hebezeuge/Transportgeräte",text:"Mobilkran Baustelle 60 t bereitstellen und vorhalten",unit:"Wo"},
{lb:"000",group:"Sozial-/Büroeinrichtungen",text:"Bürocontainer Baustelle aufstellen und vorhalten",unit:"Monat"},
{lb:"000",group:"Verkehrsflächen/Transportwege",text:"Baustraße 4 m breit herstellen und unterhalten",unit:"m"},
{lb:"000",group:"Medienversorgung",text:"Baustromversorgung herstellen und vorhalten",unit:"Wo"},
{lb:"000",group:"Baustellensicherung",text:"Bauzaun 2,0 m hoch liefern aufstellen und abbauen",unit:"m"},
{lb:"000",group:"Schutz vorhandener Bausubstanz",text:"Vorhandenes Bauwerk während Tiefbauarbeiten schützen",unit:"psch"},

{lb:"002",group:"Baugelände vorbereiten",text:"Baugelände freimachen und Oberflächenbewuchs entfernen",unit:"m2"},
{lb:"002",group:"Oberboden",text:"Oberboden 30 cm abtragen und seitlich lagern",unit:"m2"},
{lb:"002",group:"Baugrube",text:"Baugrube 3,0 m tief ausheben und laden",unit:"m3"},
{lb:"002",group:"Bodenbewegung",text:"Boden lösen fördern und einbauen 100 m",unit:"m3"},
{lb:"002",group:"Planum",text:"Planum profilgerecht herstellen und verdichten",unit:"m2"},
{lb:"002",group:"Bodenverbesserung",text:"Bodenverbesserung mit Kalk 3 Prozent herstellen",unit:"m2"},
{lb:"002",group:"Graben",text:"Leitungsgraben 1,5 m tief herstellen",unit:"m"},
{lb:"002",group:"Kopfloch",text:"Kopfloch für Leitungsanschluss herstellen",unit:"St"},
{lb:"002",group:"Gründungssohle",text:"Gründungssohle nachverdichten",unit:"m2"},
{lb:"002",group:"Suchgraben",text:"Suchgraben 1,5 m tief herstellen",unit:"m"},
{lb:"002",group:"Trassenmessung",text:"Trassenmessung Achse und Höhen durchführen",unit:"m"},
{lb:"002",group:"Bestandsleitung sichern",text:"Bestandsleitung im Graben sichern und unterfangen",unit:"m"},
{lb:"002",group:"Hindernis Boden",text:"Findling 1 m3 im Graben aufnehmen und entsorgen",unit:"St"},
{lb:"002",group:"Erosionsschutz",text:"Erosionsschutzmatte Böschung liefern und verlegen",unit:"m2"},

{lb:"003",group:"Vorbereitende Landschaftsbauarbeiten",text:"Vegetationsfläche für Landschaftsbau vorbereiten",unit:"m2"},
{lb:"003",group:"Vegetationstechnik",text:"Rasenansaat Gebrauchsrasen herstellen",unit:"m2"},
{lb:"003",group:"Ingenieurbiologische Sicherung",text:"Faschinen Böschung liefern und einbauen",unit:"m"},
{lb:"003",group:"Artenschutz",text:"Amphibienschutzzaun temporär aufstellen und vorhalten",unit:"m"},
{lb:"003",group:"Seen/Teiche/Wasserläufe",text:"Teichprofil herstellen und Böschung modellieren",unit:"m3"},
{lb:"003",group:"Sportplatzbau",text:"Sportplatz Tragschicht und Planum herstellen",unit:"m2"},
{lb:"003",group:"Beregnung",text:"Beregnungsleitung PE DN50 Landschaftsbau verlegen",unit:"m"},
{lb:"003",group:"Spielplatz",text:"Fallschutzkies 30 cm auf Spielplatz einbauen",unit:"m2"},
{lb:"003",group:"Ausstattung",text:"Sitzbank Landschaftsbau liefern und aufstellen",unit:"St"},
{lb:"003",group:"Zaun/Tor",text:"Stabgitterzaun 2 m hoch liefern und montieren",unit:"m"},
{lb:"003",group:"Trockenmauer/Gabione",text:"Gabione 1,0 m hoch herstellen",unit:"m2"},
{lb:"003",group:"Dachbegrünung",text:"Extensive Dachbegrünung 12 cm herstellen",unit:"m2"},
{lb:"003",group:"Pflege",text:"Entwicklungspflege Rasen durchführen",unit:"m2"},
{lb:"003",group:"Baumkontrolle",text:"Baumkontrolle nach FLL durchführen",unit:"St"},
{lb:"003",group:"Abbruch",text:"Alten Landschaftszaun abbauen und entsorgen",unit:"m"},

{lb:"004",group:"Kletterpflanzen",text:"Kletterpflanze Clematis liefern und pflanzen",unit:"St"},
{lb:"004",group:"Kübelpflanzen",text:"Kübelpflanze liefern und einsetzen",unit:"St"},
{lb:"004",group:"Laubgehölze",text:"Laubbaum Hochstamm 18-20 liefern und pflanzen",unit:"St"},
{lb:"004",group:"Nadelgehölze",text:"Nadelgehölz liefern und pflanzen",unit:"St"},
{lb:"004",group:"Obstgehölze",text:"Obstbaum Hochstamm liefern und pflanzen",unit:"St"},
{lb:"004",group:"Rhododendron/Azalee",text:"Rhododendron liefern und pflanzen",unit:"St"},
{lb:"004",group:"Rosen",text:"Rose Containerware liefern und pflanzen",unit:"St"},
{lb:"004",group:"Stauden/Gräser",text:"Stauden P0,5 liefern und pflanzen",unit:"St"},
{lb:"004",group:"Gebietseigene Gehölze",text:"Gebietseigenes Gehölz liefern und pflanzen",unit:"St"},

{lb:"007",group:"Baustelleneinrichtung Untertage",text:"Baustelleneinrichtung Untertagebau herstellen",unit:"psch"},
{lb:"007",group:"Ausbruch",text:"Tunnelausbruch Fels lösen und fördern",unit:"m3"},
{lb:"007",group:"Sicherung Spritzbeton",text:"Spritzbeton C25/30 20 cm Untertagebau herstellen",unit:"m2"},
{lb:"007",group:"Ausbaubögen",text:"Stahlausbaubogen Untertagebau liefern und einbauen",unit:"t"},
{lb:"007",group:"Verfüllarbeiten",text:"Hohlraum Untertagebau mit Beton verfüllen",unit:"m3"},
{lb:"007",group:"Instandhaltung",text:"Untertagebau Sicherung instandsetzen",unit:"m2"},

{lb:"019",group:"Baustelleneinrichtung Kampfmittel",text:"Baustelleneinrichtung Kampfmittelräumung herstellen",unit:"psch"},
{lb:"019",group:"Sondieren/Freilegen",text:"Kampfmittelräumung vollflächig sondieren und Störpunkte freilegen",unit:"m2"},
{lb:"019",group:"Bergen/Transport",text:"Kampfmittel bergen sichern und zum Übergabepunkt transportieren",unit:"St"},
{lb:"019",group:"Dokumentation",text:"Dokumentation Kampfmittelräumung erstellen",unit:"psch"},
{lb:"019",group:"Temporäre Verrohrung",text:"Temporäre Verrohrung Bohrung Kampfmittel DN150 herstellen",unit:"m"},
{lb:"019",group:"Bohrlochsondierung",text:"Bohrlochsondierung Kampfmittel Dreiachsmagnetometer durchführen",unit:"m"},

{lb:"005",group:"Baustelleneinrichtung Brunnenbau",text:"Baustelleneinrichtung Brunnenbau herstellen",unit:"psch"},
{lb:"005",group:"Bohrarbeiten",text:"Brunnenbohrung DN300 20 m tief herstellen",unit:"m"},
{lb:"005",group:"Bohrlöcher verfüllen/verpressen",text:"Bohrloch DN200 mit Suspension verfüllen und verpressen",unit:"m"},
{lb:"005",group:"Sperrrohre",text:"Stahl Sperrrohr Brunnen DN200 einbauen",unit:"m"},
{lb:"005",group:"Brunnenrohre",text:"PVC-U Brunnenfilterrohr DN150 liefern und einbauen",unit:"m"},
{lb:"005",group:"Filtersand/Filterkies",text:"Filterkies Brunnen 2/4 liefern und einbauen",unit:"m3"},
{lb:"005",group:"Pumpeneinbau/-ausbau",text:"Unterwasserpumpe Brunnen einbauen",unit:"St"},
{lb:"005",group:"Pumpversuch",text:"Pumpversuch Brunnen 24 h durchführen",unit:"St"},
{lb:"005",group:"Brunnenkopf/Schacht",text:"Brunnenkopf DN150 herstellen",unit:"St"},
{lb:"005",group:"Erdwärmesonden",text:"Erdwärmesonde Doppel-U 100 m einbauen",unit:"m"},
{lb:"005",group:"Beobachtung/Messung",text:"Grundwassermessstelle DN50 8 m tief herstellen",unit:"St"},

{lb:"006",group:"Grabenverbau",text:"Grabenverbau 2,5 m tief herstellen und rückbauen",unit:"m2"},
{lb:"006",group:"Spundwand",text:"Spundwand AZ Profil 8 m tief herstellen",unit:"m2"},
{lb:"006",group:"Trägerbohlwand",text:"Trägerbohlwand 6 m tief mit Holzausfachung herstellen",unit:"m2"},
{lb:"006",group:"Anker",text:"Litzzuganker 500 kN 12 m herstellen",unit:"St"},
{lb:"006",group:"Bohrpfähle",text:"Bohrpfahl DN880 14 m herstellen",unit:"m"},
{lb:"006",group:"Bohrpfahlwand",text:"Bohrpfahlwand DN880 überschnitten herstellen",unit:"m2"},
{lb:"006",group:"Schlitzwand",text:"Schlitzwand 80 cm C30/37 herstellen",unit:"m2"},
{lb:"006",group:"Injektion",text:"Zementinjektion Boden 50 kg/m3 ausführen",unit:"m3"},
{lb:"006",group:"Düsenstrahlverfahren",text:"HDI Säule DN1200 herstellen",unit:"m"},
{lb:"006",group:"Mikropfähle",text:"Mikropfahl GEWI DN200 15 m herstellen",unit:"m"},
{lb:"006",group:"Verdrängungspfähle",text:"Vollverdrängungsbohrpfahl DN500 herstellen",unit:"m"},
{lb:"006",group:"Bodenmischverfahren",text:"Mixed-in-Place Bodenmischsäule DN600 herstellen",unit:"m"},
{lb:"006",group:"Tiefenverdichtung",text:"Rüttelstopfsäule DN800 herstellen",unit:"m"},
{lb:"006",group:"Bodenvernagelung",text:"Bodennagel 8 m herstellen",unit:"St"},

{lb:"008",group:"Grundwasserabsenkung",text:"Grundwasserabsenkung mit Vakuumlanzen herstellen",unit:"m"},
{lb:"008",group:"Pumpensumpf",text:"Pumpensumpf 1,0x1,0x1,0 m herstellen",unit:"St"},
{lb:"008",group:"Sickerleitung",text:"Sickerleitung DN100 Wasserhaltung verlegen",unit:"m"},
{lb:"008",group:"Brunnen",text:"Filterbrunnen DN300 10 m tief herstellen",unit:"St"},
{lb:"008",group:"Beobachtungsrohr",text:"Beobachtungsrohr DN50 6 m tief herstellen",unit:"St"},
{lb:"008",group:"Wasserförderanlage",text:"Tauchmotorpumpe 20 m3/h Wasserhaltung betreiben",unit:"Wo"},
{lb:"008",group:"Messvorrichtung",text:"Durchflussmessgerät Wasserhaltung installieren",unit:"St"},
{lb:"008",group:"Absetzbecken",text:"Absetzbecken 10 m3 Wasserhaltung aufstellen",unit:"St"},
{lb:"008",group:"Kiesfilter",text:"Kiesfilter Wasserhaltung herstellen",unit:"m3"},
{lb:"008",group:"Aktivkohle",text:"Grundwasserreinigungsanlage Aktivkohle 20 m3/h betreiben",unit:"Wo"},
{lb:"008",group:"Ionenaustausch",text:"Grundwasserreinigungsanlage Ionenaustausch 20 m3/h betreiben",unit:"Wo"},
{lb:"008",group:"Neutralisation",text:"Neutralisationsanlage 20 m3/h betreiben",unit:"Wo"},

{lb:"009",group:"Entwässerungskanäle",text:"Kanalrohr PP DN300 SN16 liefern und verlegen",unit:"m"},
{lb:"009",group:"Schächte/Bauwerke",text:"Betonschacht DN1200 mit Gerinne liefern und setzen",unit:"St"},
{lb:"009",group:"Schachtabdeckung",text:"Schachtabdeckung DN625 D400 liefern und setzen",unit:"St"},
{lb:"009",group:"Abläufe/Rinnen",text:"Straßenablauf 500x500 D400 liefern und setzen",unit:"St"},
{lb:"009",group:"Reinigung",text:"Kanalreinigung DN300 Hochdruckspülung durchführen",unit:"m"},
{lb:"009",group:"Inspektion",text:"TV-Inspektion Kanal DN300 durchführen",unit:"m"},
{lb:"009",group:"Sanierung",text:"UV Schlauchliner Kanal DN300 einbauen",unit:"m"},
{lb:"009",group:"Dichtheitsprüfung",text:"Dichtheitsprüfung Kanal DN300 Luft durchführen",unit:"m"},
{lb:"009",group:"Abbruch",text:"Kanalrohr Beton DN300 abbrechen und entsorgen",unit:"m"},

{lb:"010",group:"Drängraben",text:"Drängraben 60 cm breit herstellen",unit:"m"},
{lb:"010",group:"Dränrohr",text:"Drainagerohr DN100 verlegen",unit:"m"},
{lb:"010",group:"Spülschacht",text:"Spülschacht Drainage DN315 liefern und setzen",unit:"St"},
{lb:"010",group:"Sickerschicht",text:"Sickerschicht Rigole 30 cm herstellen",unit:"m2"},
{lb:"010",group:"Speicherelement",text:"Rigolenkörper Speicherelement 1 m3 einbauen",unit:"St"},
{lb:"010",group:"Abbruch",text:"Rigolenanlage ausbauen und entsorgen",unit:"m3"},

{lb:"011",group:"Leichtflüssigkeitsabscheider",text:"Leichtflüssigkeitsabscheider NS10 mit Koaleszenzeinsatz liefern und setzen",unit:"St"},
{lb:"011",group:"Fettabscheider",text:"Fettabscheider NS4 liefern und setzen",unit:"St"},
{lb:"011",group:"Kleinkläranlage",text:"Kleinkläranlage 8 EW liefern und setzen",unit:"St"},

{lb:"043",group:"PE-Druckrohr",text:"Druckrohr PE100-RC DN110 SDR11 Trinkwasser verlegen",unit:"m"},
{lb:"043",group:"PE-X-Druckrohr",text:"Druckrohr PE-X DN63 SDR7,4 Trinkwasser verlegen",unit:"m"},
{lb:"043",group:"PVC-U-Druckrohr",text:"Druckrohr PVC-U DN110 SDR21 Trinkwasser verlegen",unit:"m"},
{lb:"043",group:"Stahl-Druckrohr",text:"Druckrohr Stahl DN150 PN40 Trinkwasser verlegen",unit:"m"},
{lb:"043",group:"Formstück",text:"GPE-F-Stück DN100 für PE-Druckrohr montieren",unit:"St"},
{lb:"043",group:"Mehrbereichskupplung",text:"Mehrbereichskupplung zugfest Trinkwasser Druckrohr DN200 montieren",unit:"St"},
{lb:"043",group:"Armatur",text:"Absperrschieber DN150 PN16 liefern und einbauen",unit:"St"},
{lb:"043",group:"Hydrant",text:"Unterflurhydrant DN80 PN16 liefern und setzen",unit:"St"},
{lb:"043",group:"Straßenkappe",text:"Straßenkappe für Schieber liefern und setzen",unit:"St"},
{lb:"043",group:"Rohrschnitt",text:"Rohrschnitt Druckrohr Guss DN150 herstellen",unit:"St"},
{lb:"043",group:"Anschrägen",text:"Rohrende DN150 anschrägen",unit:"St"},
{lb:"043",group:"Schweißverbindung",text:"Schweißverbindung Stahl Druckrohr DN150 herstellen",unit:"St"},
{lb:"043",group:"Druckprüfung",text:"Druckprüfung Druckrohr Wasser DN150 durchführen",unit:"m"},
{lb:"043",group:"Spülen/Entkeimen",text:"Druckrohr Trinkwasser DN150 mit Chlor spülen und entkeimen",unit:"m"},

{lb:"051",group:"Vorbereitung",text:"Kabeltrasse freimachen und vorbereiten",unit:"m"},
{lb:"051",group:"Kabelgraben",text:"Kabelgraben 0,8 m tief herstellen",unit:"m"},
{lb:"051",group:"Schutzrohr",text:"PE-HD Kabelschutzrohr DN110 SDR17 liefern und verlegen",unit:"m"},
{lb:"051",group:"Kabelkanal",text:"Beton Kabelkanaltrog B 300 mm mit Deckel verlegen",unit:"m"},
{lb:"051",group:"Kabelschacht",text:"Kabelschacht groß liefern und setzen",unit:"St"},
{lb:"051",group:"Kabelhaus",text:"Begehbares Kabelhaus aufstellen",unit:"St"},
{lb:"051",group:"Mediendurchführung",text:"Kabeldurchführung Wand DN110 druckwasserdicht herstellen",unit:"St"},
{lb:"051",group:"Sockel/Pfosten",text:"Kabelsockel Beton herstellen",unit:"St"},
{lb:"051",group:"Kabel",text:"NAYY-J 4x150 mm2 im Kabelgraben verlegen",unit:"m"},
{lb:"051",group:"Abdichtung",text:"Kabelschutzrohr DN110 wasserdicht verschließen",unit:"St"},
{lb:"051",group:"Abbruch",text:"Kabelschacht abbrechen und entsorgen",unit:"St"},

{lb:"080",group:"Schicht ohne Bindemittel",text:"Schottertragschicht 0/32 30 cm herstellen",unit:"m2"},
{lb:"080",group:"Asphalt",text:"Asphaltdeckschicht AC11 D 4 cm herstellen",unit:"m2"},
{lb:"080",group:"Betonbauweise",text:"Betonfahrbahn C30/37 24 cm herstellen",unit:"m2"},
{lb:"080",group:"Bord/Rinne",text:"Betonbordstein 15x30 liefern und setzen",unit:"m"},
{lb:"080",group:"Pflaster",text:"Betonpflaster 10 cm herstellen",unit:"m2"},
{lb:"080",group:"Platten",text:"Betonplatten 40x40x8 verlegen",unit:"m2"},
{lb:"080",group:"Begrünbarer Belag",text:"Rasengittersteine 12 cm herstellen",unit:"m2"},
{lb:"080",group:"Bankett",text:"Bankett 1,0 m breit herstellen",unit:"m"},
{lb:"080",group:"Straßeneinbauten",text:"Poller herausnehmbar liefern und setzen",unit:"St"},
{lb:"080",group:"Verkehrseinrichtung",text:"Leitpfosten liefern und setzen",unit:"St"},
{lb:"080",group:"Wellstahl",text:"Wellstahlbauwerk Spannweite 3 m herstellen",unit:"m"},
{lb:"080",group:"Gabione",text:"Gabione 1,0 m hoch herstellen",unit:"m2"},
{lb:"080",group:"Lärmschutzwand",text:"Lärmschutzwand Aluminium 3 m hoch herstellen",unit:"m2"},
{lb:"080",group:"Kontrollprüfung",text:"Mischgutprobe Asphalt entnehmen und prüfen",unit:"St"},
{lb:"080",group:"Bohrkern",text:"Bohrkern Asphalt entnehmen und prüfen",unit:"St"},

{lb:"084",group:"Abbruch Kanal",text:"Kanalrohr Steinzeug DN200 abbrechen und entsorgen",unit:"m"},
{lb:"084",group:"Abbruch Schacht",text:"Betonschacht DN1000 abbrechen und entsorgen",unit:"St"},
{lb:"084",group:"Abbruch Straße",text:"Asphaltfläche 12 cm abbrechen und entsorgen",unit:"m2"},
{lb:"084",group:"Trennschnitt",text:"Trennschnitt Betonstützmauer herstellen",unit:"m"},

{lb:"085",group:"Baustelleneinrichtung",text:"Baustelleneinrichtung Rohrvortrieb herstellen",unit:"psch"},
{lb:"085",group:"Start-/Zielgrube",text:"Startgrube Rohrvortrieb 6 m tief herstellen",unit:"St"},
{lb:"085",group:"Rohrvortrieb",text:"Rohrvortrieb Stahlbeton DN600 herstellen",unit:"m"},
{lb:"085",group:"Microtunneling",text:"Microtunneling DN800 herstellen",unit:"m"},
{lb:"085",group:"Inspektion",text:"TV-Inspektion Vortriebsrohr DN800 durchführen",unit:"m"},
{lb:"085",group:"Dichtheitsprüfung",text:"Dichtheitsprüfung Vortriebsrohr DN800 durchführen",unit:"m"},
{lb:"085",group:"Vermessung",text:"Vermessung Rohrvortrieb Achse und Höhe durchführen",unit:"m"},
{lb:"085",group:"Beweissicherung",text:"Beweissicherung Rohrvortrieb vor und nach Bau durchführen",unit:"St"},

{lb:"087",group:"Bodenentsorgung",text:"Boden BM-F2 laden transportieren und entsorgen 20 km",unit:"t"},
{lb:"087",group:"Asphaltentsorgung",text:"Ausbauasphalt teerfrei laden und entsorgen",unit:"t"},
{lb:"087",group:"Betonentsorgung",text:"Betonbruch RC laden und verwerten",unit:"t"},

{lb:"089",group:"Verkehrssicherung",text:"Verkehrssicherung halbseitige Sperrung innerorts einrichten",unit:"psch"},
{lb:"089",group:"Beschilderung",text:"Verkehrszeichen Baustelle aufstellen und vorhalten",unit:"StWo"},
{lb:"089",group:"Lichtsignalanlage",text:"Mobile Lichtsignalanlage Baustelle aufstellen und vorhalten",unit:"Wo"},

{lb:"090",group:"Personenorientiert",text:"Baulogistik Personenkoordination durchführen",unit:"Monat"},
{lb:"090",group:"Fahrzeugorientiert",text:"Baulogistik Lieferverkehr koordinieren",unit:"Monat"},
{lb:"090",group:"Flächenorientiert",text:"Baulogistik Lagerflächenmanagement durchführen",unit:"Monat"},
{lb:"090",group:"Logistikhandbuch",text:"Baulogistik Logistikhandbuch erstellen",unit:"St"},
{lb:"090",group:"Winterdienst",text:"Baulogistik Winterdienst Baustelle durchführen",unit:"Monat"},
];
const generic=new Set(["Kanalbauleistung","Wasserleitungsbau","Oberflächenwiederherstellung","Oberflächenbau","Erdbau/Schüttgut","Sonderbauverfahren","Grabenloser Leitungsbau","Sicherungsleistung","Dokumentationsleistung","Entsorgungsleistung","Prüfleistung","Logistikleistung","Gasleitungsbau","Fernwärmebau","Glasfaser-Kabelbau","Kabelbau","Leitungskreuzung"]);
let fail=0,zero=0,mismatch=0;
for(let i=0;i<rows.length;i++){
 const r=rows[i], row:any={posNr:`STLB.${r.lb}.${String(i+1).padStart(3,"0")}`,kurztext:r.text,langtext:r.text,einheit:r.unit,menge:1};
 const x:any=calculateAutonomousUrkalkulation(row,ctx,[row]); const ep=Number(x?.unitPrice||0);
 const pb=(x?.costLines||[]).reduce((s:number,l:any)=>s+Number(l.unitPrice||0),0);
 const bad=!x || generic.has(String(x?.leistungsart||""));
 if(bad){fail++;console.log(["STLB_GAP",r.lb,r.group,r.text,x?.trade||"NULL",x?.leistungsart||"NULL",ep].join("|"));}
 if(!(ep>0)){zero++; console.log(["STLB_ZERO",r.lb,r.group,r.text].join("|"));}
 if(ep>0 && Math.abs(pb*1.23-ep)>0.20 && Math.abs(pb-ep)>0.20){mismatch++;console.log(["STLB_MISMATCH",r.lb,r.group,r.text,ep,pb].join("|"));}
}
const lbs=[...new Set(rows.map(r=>r.lb))];
console.log(`STLB_MATRIX|LBS=${lbs.length}|GROUPS=${rows.length}|FAIL=${fail}|ZERO=${zero}|MISMATCH=${mismatch}`);
if(fail||zero||mismatch) process.exitCode=1;
