import assert from 'node:assert/strict';import express from 'express';import http from 'http';import fs from 'fs';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_bid_print_validation_20261010';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),router=require('../routes/officeAddons').default,{preisspiegelPdf}=require('../services/pdf/preisspiegelPdf'),{bidComparisonSnapshot}=require('../services/bidComparisonSnapshot');
async function main(){
 await prisma.company.createMany({data:[{id:'bp-a',code:'BP-A',name:'Fiktive Bau GmbH'},{id:'bp-b',code:'BP-B',name:'Andere Firma'}]});await prisma.user.create({data:{id:'bp-user',companyId:'bp-a',email:'bid-print@test.invalid',password:'test'}});
 await prisma.project.createMany({data:[{id:'bp-p',companyId:'bp-a',code:'BP-P',name:'Fiktives Bauprojekt'},{id:'bp-hidden',companyId:'bp-a',code:'BP-H',name:'Hidden'},{id:'bp-foreign',companyId:'bp-b',code:'BP-B-P',name:'B'}]});await prisma.projectMember.create({data:{projectId:'bp-p',userId:'bp-user',role:'KALKULATOR'}});
 const lines=Array.from({length:35},(_,i)=>({position:'01.'+String(i+1).padStart(4,'0'),title:i===0?('Langer deutscher Ausschreibungstext für Straßenbau, Böschung und Entwässerung. '.repeat(12)+'ENDE_LANGTEXT'):'Fiktive Leistung '+(i+1),unit:'m2',quantity:'12.345678',unitPrice:i===0?'0.1234':'10.1234'}));
 for(let n=0;n<5;n++)await prisma.projectBid.create({data:{id:'bp-'+n,companyId:'bp-a',projectId:'bp-p',title:n===0?'Basisangebot':'Angebot '+n,supplier:n===1?'Überlanger Anbietername '.repeat(10):'Fiktiver Anbieter '+n,packageKey:'Straßenbau',kind:'LV',status:n===4?'Entwurf':'Eingereicht',discountPercent:'2.5',positions:n===3?lines.slice(1):lines.map((r:any)=>({...r,...(n===2?{quantity:'14',title:r.title+' geändert'}:{})})),awardedAt:n===1?new Date('2026-10-10T12:00Z'):null}});
 await prisma.projectBid.createMany({data:[{id:'bp-other',companyId:'bp-b',projectId:'bp-foreign',title:'Foreign',supplier:'Foreign',packageKey:'Straßenbau',kind:'LV',status:'Eingereicht',discountPercent:'0',positions:lines},{id:'bp-h',companyId:'bp-a',projectId:'bp-hidden',title:'Hidden',supplier:'Hidden',packageKey:'Straßenbau',kind:'LV',status:'Eingereicht',discountPercent:'0',positions:lines}]});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'bp-user',companyId:req.headers['x-company']||'bp-a',companyRole:req.headers['x-role']||'KALKULATOR'};next();});app.use('/addons',router);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path:string,body:any=undefined,headers:any={}){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+'/addons'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});const isPdf=res.headers.get('Content-Type')?.includes('application/pdf');return {status:res.status,data:isPdf?Buffer.from(await res.arrayBuffer()):await res.json() as any,headers:res.headers};}
 try{
 const original=JSON.stringify(await prisma.projectBid.findMany({orderBy:{id:'asc'}})),audits=await prisma.auditLog.count();
 const c=await call('/bids/compare/bp-0');assert.equal(c.status,200);assert.equal(c.data.offers.length,5);assert.equal(c.data.ranking.length,3);assert.match(c.data.snapshot.fingerprint,/^[a-f0-9]{64}$/);
 const b={fingerprint:c.data.snapshot.fingerprint};
 assert.equal((await call('/bids/compare/bp-0/pdf',b,{'x-company':'bp-b'})).status,404);assert.equal((await call('/bids/compare/bp-h/pdf',b)).status,404);assert.equal((await call('/bids/compare/bp-0/pdf',b,{'x-role':'GAST'})).status,403);assert.equal((await call('/bids/compare/bp-0/pdf',b,{'x-no-user':'1'})).status,401);
 assert.equal((await call('/bids/compare/bp-0/pdf',{})).status,400);assert.equal((await call('/bids/compare/bp-0/pdf',{fingerprint:'0'.repeat(64)})).status,409);
 const pdf=await call('/bids/compare/bp-0/pdf',b);assert.equal(pdf.status,200);assert.equal(pdf.headers.get('Content-Disposition'),'attachment; filename="Preisspiegel.pdf"');assert.match(pdf.headers.get('Cache-Control')||'',/no-store/);assert.equal(pdf.data.subarray(0,5).toString(),'%PDF-');
 const {PDFDocument}=require('pdf-lib');const parsed=await PDFDocument.load(pdf.data);assert.ok(parsed.getPageCount()>2);for(const page of parsed.getPages()){assert.ok(page.getWidth()>page.getHeight());}
 fs.writeFileSync('/tmp/rlc-bid-print-qa.pdf',pdf.data);
 const parse=require('pdf-parse');const extraction=await parse(pdf.data);assert.match(extraction.text,/ENDE_LANGTEXT/);assert.match(extraction.text,/0,1234 EUR/);assert.match(extraction.text,/Menge abweichend/);assert.match(extraction.text,/Text abweichend/);assert.match(extraction.text,/Nicht vergleichbar/);assert.match(extraction.text,/Ausgewählt/);assert.match(extraction.text,/Anbietergruppe 2\/2/);
 assert.equal(JSON.stringify(await prisma.projectBid.findMany({orderBy:{id:'asc'}})),original);assert.equal(await prisma.auditLog.count(),audits);assert.equal(await prisma.projectTask.count(),0);assert.equal(await prisma.ledgerEntry.count(),0);
 await prisma.projectBid.update({where:{id:'bp-2'},data:{revision:{increment:1},notes:'changed'}});assert.equal((await call('/bids/compare/bp-0/pdf',b)).status,409);
 const fresh=await call('/bids/compare/bp-0');assert.notEqual(fresh.data.snapshot.fingerprint,b.fingerprint);
 const view=await bidComparisonSnapshot(prisma,'bp-a','bp-0');await assert.rejects(preisspiegelPdf({...view,comparison:{...view.comparison,positions:Array(501).fill(lines[0])}}));await assert.rejects(preisspiegelPdf({...view,comparison:{...view.comparison,offers:Array(21).fill(view.comparison.offers[0])}}));
 await prisma.projectBid.update({where:{id:'bp-0'},data:{status:'Archiviert',revision:{increment:1}}});assert.equal((await call('/bids/compare/bp-0')).status,404);assert.equal((await call('/bids/compare/bp-0/pdf',{fingerprint:fresh.data.snapshot.fingerprint})).status,404);
 console.log('PASS bid comparison PDF: two fictional firms and scoped roles/projects, saved snapshot fingerprint, stale and archived source refusal, same computed totals/discounts/ranks, no business/audit writes, incomplete and draft offers, 4-decimal EP, multi-group landscape pages, complete long text and explicit deviations, bounded output. QA PDF pages '+parsed.getPageCount());
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
