import assert from 'node:assert/strict';import express from 'express';import http from 'node:http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_assignment_validation_20261009';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),router=require('../routes/catalogAssignments').default,catalogRouter=require('../routes/masterCatalog').default;
async function main(){
 await prisma.company.createMany({data:[{id:'as-a',name:'Fiktiv A',code:'AS-A'},{id:'as-b',name:'Fiktiv B',code:'AS-B'}]});
 await prisma.user.create({data:{id:'as-user',companyId:'as-a',email:'assignment@test.invalid',password:'test'}});
 await prisma.project.createMany({data:[{id:'as-p',companyId:'as-a',code:'AS-P',name:'Authorized'},{id:'as-hidden',companyId:'as-a',code:'AS-HIDDEN',name:'Hidden'}]});await prisma.projectMember.create({data:{userId:'as-user',projectId:'as-p',role:'BAULEITER'}});
 await prisma.companyEmployee.createMany({data:[{id:'as-employee',companyId:'as-a',name:'Employee A',hourlyRate:'123.45',phone:'private',projects:['as-hidden']},{id:'as-inactive',companyId:'as-a',name:'Inactive',active:false},{id:'as-foreign-employee',companyId:'as-b',name:'FOREIGN EMPLOYEE'}]});await prisma.companyEmployeeCertificate.create({data:{id:'as-cert',employeeId:'as-employee',name:'Unchanged Certificate',validUntil:new Date('2030-01-01T12:00Z')}});
 await prisma.companyMaterial.createMany({data:[{id:'as-material',companyId:'as-a',name:'Material A',projectId:'AS-P',unit:'Stk',stock:5,priceNet:'100'},{id:'as-global',companyId:'as-a',name:'Global material'},{id:'as-hidden-material',companyId:'as-a',name:'Hidden material',projectId:'as-hidden'},{id:'as-foreign-material',companyId:'as-b',name:'FOREIGN MATERIAL'}]});
 await prisma.companyMasterCatalog.createMany({data:[{id:'as-license',companyId:'as-a',kind:'LICENSE_CLASS',code:'B',label:'Manual class B'},{id:'as-hazard',companyId:'as-a',kind:'HAZARD_CLASS',code:'H1',label:'Manual hazard'},{id:'as-license2',companyId:'as-a',kind:'LICENSE_CLASS',code:'C',label:'Manual C'},{id:'as-unit',companyId:'as-a',kind:'UNIT',code:'STK',label:'Stück'},{id:'as-foreign',companyId:'as-b',kind:'LICENSE_CLASS',code:'B',label:'FOREIGN LICENSE'}]});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'as-user',companyId:req.headers['x-company']||'as-a',companyRole:req.headers['x-role']||'ADMIN'};next();});app.use('/assignment',router);app.use('/catalog',catalogRouter);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path='',method='GET',body:any=undefined,headers:any={},prefix='/assignment'){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+prefix+path,{method,headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,data:await res.json() as any};}
 const base={kind:'LICENSE_CLASS',employeeId:'as-employee',catalogId:'as-license',validUntil:'2030-01-01',checkedAt:'2026-01-01',notes:'Manual test'};
 try{
 assert.equal((await call('?kind=LICENSE_CLASS','GET',undefined,{'x-no-user':'1'})).status,403);assert.equal((await call('?kind=UNIT')).status,400);
 for(const role of ['BUCHHALTUNG','CAPOCANTIERE','KALKULATOR','MITARBEITER','GAST'])for(const path of ['?kind=LICENSE_CLASS','/resources?kind=LICENSE_CLASS'])assert.equal((await call(path,'GET',undefined,{'x-role':role})).status,403);
 assert.equal((await call('','POST',base,{'x-role':'BUCHHALTUNG'})).status,403);
 const resources=await call('/resources?kind=LICENSE_CLASS','GET',undefined,{'x-role':'BAULEITER'});assert.equal(resources.status,200);assert.equal(resources.data.targets.length,1);assert.equal(JSON.stringify(resources.data).includes('123.45'),false);assert.equal(JSON.stringify(resources.data).includes('private'),false);
 const scoped=await call('/resources?kind=HAZARD_CLASS','GET',undefined,{'x-role':'BAULEITER'});assert.deepEqual(scoped.data.targets.map((x:any)=>x.id).sort(),['as-global','as-material']);assert.equal((await call('/resources?kind=HAZARD_CLASS')).data.targets.length,3);
 for(const patch of [{kind:'UNIT'},{employeeId:'as-inactive'},{employeeId:'as-foreign-employee'},{catalogId:'as-foreign'},{catalogId:'as-unit'},{materialId:'as-material'},{validUntil:'2026-02-30'},{checkedAt:'2999-01-01'},{notes:true},{active:'true'}])assert.ok([400,404].includes((await call('','POST',{...base,...patch})).status));
 const creates=await Promise.all([call('','POST',base),call('','POST',base)]);assert.deepEqual(creates.map(x=>x.status).sort(),[201,409]);let row=creates.find(x=>x.status===201)!.data.item;assert.equal(row.expiry.status,'GUELTIG');assert.equal(row.labelSnapshot,'Manual class B');
 assert.equal((await call('/'+row.id,'PUT',{notes:'No version'})).status,400);assert.equal((await call('/'+row.id,'DELETE',{})).status,400);
 for(const patch of [{catalogId:'as-license2'},{kind:'HAZARD_CLASS'},{employeeId:'as-inactive'},{codeSnapshot:'Z'},{labelSnapshot:'Rewrite'}])assert.equal((await call('/'+row.id,'PUT',{...patch,expectedUpdatedAt:row.updatedAt})).status,400);
 const updates=await Promise.all([call('/'+row.id,'PUT',{notes:'Changed A',validUntil:'2020-01-01',expectedUpdatedAt:row.updatedAt}),call('/'+row.id,'PUT',{notes:'Changed B',validUntil:'2020-01-01',expectedUpdatedAt:row.updatedAt})]);assert.deepEqual(updates.map(x=>x.status).sort(),[200,409]);row=updates.find(x=>x.status===200)!.data.item;assert.equal(row.expiry.status,'ABGELAUFEN');
 for(const path of ['/'+row.id+'/history']){assert.equal((await call(path,'GET',undefined,{'x-role':'BUCHHALTUNG'})).status,403);assert.equal((await call(path,'GET',undefined,{'x-company':'as-b'})).status,404);}
 assert.equal((await call('?kind=LICENSE_CLASS','GET',undefined,{'x-company':'as-b'})).data.items.length,0);
 const catalog=await prisma.companyMasterCatalog.findUnique({where:{id:'as-license'}});assert.equal((await call('/as-license','PUT',{label:'New catalogue name',expectedUpdatedAt:catalog.updatedAt.toISOString()}, {},'/catalog')).status,200);assert.equal((await call('?kind=LICENSE_CLASS')).data.items[0].labelSnapshot,'Manual class B');assert.equal((await call('?kind=LICENSE_CLASS')).data.items[0].catalog.label,'New catalogue name');
 let changed=await prisma.companyMasterCatalog.findUnique({where:{id:'as-license'}});assert.equal((await call('/as-license','DELETE',{expectedUpdatedAt:changed.updatedAt.toISOString()}, {},'/catalog')).status,200);assert.equal((await call('?kind=LICENSE_CLASS')).data.items.length,1);
 row=(await call('/'+row.id,'DELETE',{expectedUpdatedAt:row.updatedAt})).data.item;assert.equal((await call('?kind=LICENSE_CLASS')).data.items.length,0);assert.equal((await call('?kind=LICENSE_CLASS&includeInactive=true')).data.items.length,1);assert.equal((await call('','POST',base)).status,404);assert.equal((await call('/'+row.id,'PUT',{active:true,expectedUpdatedAt:row.updatedAt})).status,409);
 changed=await prisma.companyMasterCatalog.findUnique({where:{id:'as-license'}});assert.equal((await call('/as-license','PUT',{active:true,expectedUpdatedAt:changed.updatedAt.toISOString()}, {},'/catalog')).status,200);assert.equal((await call('','POST',base)).status,409);row=(await call('/'+row.id,'PUT',{active:true,expectedUpdatedAt:row.updatedAt})).data.item;assert.equal(row.active,true);assert.equal((await call('/'+row.id+'/history')).data.items.length,4);
 const hazard={kind:'HAZARD_CLASS',materialId:'as-material',catalogId:'as-hazard',checkedAt:'2026-01-01'};assert.equal((await call('','POST',{...hazard,validUntil:'2030-01-01'})).status,400);assert.equal((await call('','POST',{...hazard,materialId:'as-hidden-material'},{'x-role':'BAULEITER'})).status,404);assert.equal((await call('','POST',{...hazard,materialId:'as-foreign-material'})).status,404);assert.equal((await call('','POST',hazard,{'x-role':'MITARBEITER'})).status,403);
 const h=await call('','POST',hazard,{'x-role':'BAULEITER'});assert.equal(h.status,201);let hr=h.data.item;assert.equal(hr.expiry,null);assert.equal((await call('?kind=HAZARD_CLASS','GET',undefined,{'x-role':'MITARBEITER'})).data.canEdit,false);
 const hidden=await call('','POST',{...hazard,materialId:'as-hidden-material'});assert.equal(hidden.status,201);assert.equal((await call('?kind=HAZARD_CLASS','GET',undefined,{'x-role':'BAULEITER'})).data.items.length,1);assert.equal((await call('/'+hidden.data.item.id+'/history','GET',undefined,{'x-role':'BAULEITER'})).status,404);assert.equal((await call('/'+hidden.data.item.id,'PUT',{notes:'Forbidden',expectedUpdatedAt:hidden.data.item.updatedAt},{'x-role':'BAULEITER'})).status,404);
 await prisma.companyMaterial.update({where:{id:'as-material'},data:{active:false}});assert.equal((await call('/'+hr.id,'PUT',{notes:'No active target',expectedUpdatedAt:hr.updatedAt})).status,404);hr=(await call('/'+hr.id,'DELETE',{expectedUpdatedAt:hr.updatedAt})).data.item;assert.equal(hr.active,false);assert.equal((await call('/'+hr.id,'PUT',{active:true,expectedUpdatedAt:hr.updatedAt})).status,404);
 const before=await prisma.companyCatalogAssignment.findUnique({where:{id:row.id}}),audits=await prisma.auditLog.count(),count=await prisma.companyCatalogAssignment.count();await prisma.$executeRawUnsafe('ALTER TABLE "AuditLog" RENAME TO "_AssignmentAuditUnavailable"');try{assert.equal((await call('/'+row.id,'PUT',{notes:'Rollback',expectedUpdatedAt:row.updatedAt})).status,500);assert.equal((await call('','POST',{...base,catalogId:'as-license2'})).status,500);}finally{await prisma.$executeRawUnsafe('ALTER TABLE "_AssignmentAuditUnavailable" RENAME TO "AuditLog"');}const after=await prisma.companyCatalogAssignment.findUnique({where:{id:row.id}});assert.equal(after.notes,before.notes);assert.equal(after.updatedAt.toISOString(),before.updatedAt.toISOString());assert.equal(await prisma.auditLog.count(),audits);assert.equal(await prisma.companyCatalogAssignment.count(),count);
 await assert.rejects(()=>prisma.companyCatalogAssignment.create({data:{id:'bad',companyId:'as-a',catalogId:'as-license2',kind:'LICENSE_CLASS',materialId:'as-global',codeSnapshot:'C',labelSnapshot:'Bad'}}));
 const employee=await prisma.companyEmployee.findUnique({where:{id:'as-employee'}});assert.equal(String(employee.hourlyRate),'123.45');assert.equal(employee.phone,'private');assert.deepEqual(employee.projects,['as-hidden']);const cert=await prisma.companyEmployeeCertificate.findUnique({where:{id:'as-cert'}});assert.equal(cert.name,'Unchanged Certificate');assert.equal(cert.validUntil.toISOString(),'2030-01-01T12:00:00.000Z');const mat=await prisma.companyMaterial.findUnique({where:{id:'as-material'}});assert.equal(mat.unit,'Stk');assert.equal(mat.stock,5);assert.equal(String(mat.priceNet),'100');assert.equal(await prisma.ledgerEntry.count(),0);assert.equal(await prisma.companyMaterialMove.count(),0);
 console.log('PASS catalog assignments PostgreSQL: two company scopes, personnel role protection/minimal data, canonical and legacy material project scopes, validation/dates, unique concurrent create, mandatory concurrent revisions, immutable identities and snapshots, archive/restore/inactive targets, 100-entry scoped history, atomic audit rollback and DB target check; certificates/rates/material stock/prices/accounting preserved.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
