import assert from 'node:assert/strict';import express from 'express';import http from 'http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_plan_validation_20261009';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),router=require('../routes/buero/bauzeitenplan').default,{planInput}=require('../domain/constructionPlan');
const task=(id:string,deps:string[]=[])=>({id,name:'Vorgang '+id,dauerTage:2,start:'2026-10-12',end:'2026-10-13',progress:10,notes:'Existing',assignee:'Fiktiv',milestone:false,deps,ressourcen:{Bagger:1}});
async function main(){await prisma.company.createMany({data:[{id:'pl-a',code:'PL-A',name:'Fiktiv A'},{id:'pl-b',code:'PL-B',name:'Fiktiv B'}]});await prisma.user.create({data:{id:'pl-user',companyId:'pl-a',email:'plan@test.invalid',password:'test'}});await prisma.project.createMany({data:[{id:'pl-p',companyId:'pl-a',code:'PL-P',name:'A'},{id:'pl-hidden',companyId:'pl-a',code:'PL-HIDDEN',name:'Hidden'},{id:'pl-foreign',companyId:'pl-b',code:'PL-B-P',name:'B'}]});await prisma.projectMember.create({data:{projectId:'pl-p',userId:'pl-user',role:'BAULEITER'}});await prisma.planTask.create({data:{id:'foreign-task',projectId:'pl-foreign',name:'Foreign original',dauerTage:3,depsJson:'[]',ressJson:'{}'}});await prisma.companyMaterial.create({data:{id:'pl-mat',companyId:'pl-a',name:'Existing',stock:11}});await prisma.companyEmployee.create({data:{id:'pl-emp',companyId:'pl-a',name:'Existing',hourlyRate:'23.45'}});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'pl-user',companyId:req.headers['x-company']||'pl-a',companyRole:req.headers['x-role']||'ADMIN'};next();});app.use('/plan',router);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(endpoint='/load',body:any={projectId:'pl-p'},headers:any={}){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+'/plan'+endpoint,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});return {status:res.status,data:await res.json() as any};}
 const base={projectId:'pl-p',start:'2026-10-12',tasks:[task('t1'),task('t2',['t1'])],capacity:{Bagger:2}};
 try{
 let loaded=(await call()).data;assert.equal(loaded.tasks.length,0);assert.equal(loaded.canEdit,true);assert.equal(loaded.version.length,64);assert.equal((await call('/load',{projectId:'PL-P'})).data.version,loaded.version);
 for(const role of ['MITARBEITER','GAST','CAPOCANTIERE','BUCHHALTUNG']){const r=await call('/load',{projectId:'pl-p'},{'x-role':role});assert.equal(r.status,200);assert.equal(r.data.canEdit,false);assert.equal((await call('/save',{...base,expectedVersion:loaded.version},{'x-role':role})).status,403);}
 assert.equal((await call('/load',{projectId:'pl-p'},{'x-no-user':'1'})).status,403);assert.equal((await call('/load',{projectId:'pl-p'},{'x-company':'pl-b'})).status,403);assert.equal((await call('/load',{projectId:'pl-hidden'},{'x-role':'BAULEITER'})).status,403);
 assert.equal((await call('/save',base)).status,400);const save=await call('/save',{...base,expectedVersion:loaded.version},{'x-role':'BAULEITER'});assert.equal(save.status,200);loaded=save.data;assert.equal(loaded.start,'2026-10-12');assert.equal(loaded.tasks.length,2);assert.equal(loaded.capacity.Bagger,2);assert.equal(await prisma.planSnapshot.count({where:{projectId:'pl-p'}}),1);assert.equal(await prisma.auditLog.count(),1);assert.equal((await call()).data.version,loaded.version);
 for(const patch of [{start:'2026-02-30'},{tasks:null},{capacity:[]},{capacity:{Bagger:-1}},{capacity:{Bagger:'2'}},{tasks:[task('same'),task('same')]},{tasks:[task('a',['missing'])]},{tasks:[task('a',['a'])]},{tasks:[task('a',['b']),task('b',['a'])]},{tasks:[{...task('a'),progress:1.5}]},{tasks:[{...task('a'),end:'2026-10-11'}]},{tasks:[{...task('a'),end:null}]},{tasks:[{...task('a'),milestone:true}]},{tasks:[{...task('a'),dauerTage:3}]},{tasks:[{...task('a'),ressourcen:{constructor:1}}]},{tasks:[{...task('a'),start:'2026-02-30',end:'2026-03-01'}]}])assert.equal((await call('/save',{...base,...patch,expectedVersion:loaded.version})).status,400);
 assert.equal((await call('/save',{...base,tasks:[task('foreign-task')],expectedVersion:loaded.version})).status,409);assert.equal((await prisma.planTask.findUnique({where:{id:'foreign-task'}})).name,'Foreign original');assert.equal((await call()).data.version,loaded.version);
 const simultaneous=await Promise.all([call('/save',{...base,capacity:{Bagger:3},expectedVersion:loaded.version}),call('/save',{...base,capacity:{Bagger:4},expectedVersion:loaded.version})]);assert.deepEqual(simultaneous.map(x=>x.status).sort(),[200,409]);loaded=simultaneous.find(x=>x.status===200)!.data;
 assert.equal((await call('/save',{...base,expectedVersion:save.data.version})).status,409);let history=await call('/history');assert.equal(history.data.items.length,2);assert.equal((await call('/history',{projectId:'pl-p'},{'x-company':'pl-b'})).status,403);
 const before=JSON.stringify((await call()).data),snapshots=await prisma.planSnapshot.count(),audits=await prisma.auditLog.count();await prisma.$executeRawUnsafe('ALTER TABLE "AuditLog" RENAME TO "_PlanAuditUnavailable"');try{assert.equal((await call('/save',{...base,start:'2026-11-01',tasks:[task('new')],capacity:{Bagger:9},expectedVersion:loaded.version})).status,503);}finally{await prisma.$executeRawUnsafe('ALTER TABLE "_PlanAuditUnavailable" RENAME TO "AuditLog"');}assert.equal(JSON.stringify((await call()).data),before);assert.equal(await prisma.planSnapshot.count(),snapshots);assert.equal(await prisma.auditLog.count(),audits);
 await prisma.$executeRawUnsafe('ALTER TABLE "ResourceCapacity" RENAME TO "_PlanCapacityUnavailable"');try{assert.equal((await call()).status,503);}finally{await prisma.$executeRawUnsafe('ALTER TABLE "_PlanCapacityUnavailable" RENAME TO "ResourceCapacity"');}
 const clear=await call('/save',{...base,tasks:[],capacity:{},expectedVersion:loaded.version});assert.equal(clear.status,200);assert.equal(clear.data.tasks.length,0);assert.deepEqual(clear.data.capacity,{});assert.equal((await call()).data.start,'2026-10-12');
 assert.equal((await prisma.companyMaterial.findUnique({where:{id:'pl-mat'}})).stock,11);assert.equal(String((await prisma.companyEmployee.findUnique({where:{id:'pl-emp'}})).hourlyRate),'23.45');assert.equal(await prisma.ledgerEntry.count(),0);assert.equal(await prisma.projectTask.count(),0);assert.equal(await prisma.officeCalendarEvent.count(),0);
 console.log('PASS construction plan PostgreSQL: tenant/project/roles, canonical code resolution, strict calendars/numbers/resources, duplicate/dangling/cyclic graph checks, milestone dates, foreign IDs preserved, atomic tasks/capacity/start/snapshot/audit, mandatory simultaneous revisions, history scopes, rollback on audit failure, unavailable reads not empty and explicit empty-plan save; existing resource/accounting/calendar/task data unchanged.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
