import assert from 'node:assert/strict';import express from 'express';import http from 'http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_contact_comm_validation_20261010';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),contacts=require('../routes/businessContacts').default,communication=require('../routes/communication').default,{FileKind}=require('@prisma/client');
async function main(){
 await prisma.company.createMany({data:[{id:'cc-a',code:'CC-A',name:'Fiktive Firma A'},{id:'cc-b',code:'CC-B',name:'Fiktive Firma B'}]});
 await prisma.user.create({data:{id:'cc-user',companyId:'cc-a',email:'contact-comm@test.invalid',password:'test'}});
 await prisma.party.createMany({data:[{id:'cc-party',companyId:'cc-a',type:'SUPPLIER',name:'Kontakt A'},{id:'cc-other',companyId:'cc-a',type:'CUSTOMER',name:'Kontakt B'},{id:'cc-foreign',companyId:'cc-b',type:'SUPPLIER',name:'Fremdkontakt'}]});
 await prisma.project.createMany({data:[{id:'cc-p',companyId:'cc-a',code:'CC-P',name:'Mitgliedsprojekt'},{id:'cc-private',companyId:'cc-a',code:'CC-PRIVATE',name:'Privates Projekt'},{id:'cc-foreign-p',companyId:'cc-b',code:'CC-B-P',name:'Fremdprojekt'}]});
 await prisma.projectMember.create({data:{projectId:'cc-p',userId:'cc-user',role:'BAULEITER'}});
 await prisma.communicationThread.createMany({data:[{id:'cc-thread',companyId:'cc-a',projectId:'cc-p',subject:'Fiktive Abstimmung',participants:['contact@test.invalid'],unreadCount:7},{id:'cc-empty',companyId:'cc-a',projectId:'cc-p',subject:'Leere Konversation',participants:[]},{id:'cc-hidden',companyId:'cc-a',projectId:'cc-private',subject:'Vertrauliches Projekt',participants:[]},{id:'cc-foreign-thread',companyId:'cc-b',projectId:'cc-foreign-p',subject:'Fremde Kommunikation',participants:[]}]});
 await prisma.communicationMessage.createMany({data:Array.from({length:120},(_,i)=>({id:'cc-m-'+String(i).padStart(3,'0'),threadId:'cc-thread',fromName:'Fiktiver Absender',toList:['contact@test.invalid'],ccList:[],body:i===119?'X'.repeat(20001):'<img src=x onerror=alert(1)> Nachricht '+i,createdAt:new Date(Date.UTC(2026,0,1,0,0,i))}))});
 await prisma.document.createMany({data:[{id:'cc-doc',projectId:'cc-p',kind:Object.values(FileKind)[0] as any,name:'Nachweis.pdf'},{id:'cc-deleted-doc',projectId:'cc-p',kind:Object.values(FileKind)[0] as any,name:'Gelöschter Nachweis.pdf',deletedAt:new Date()},{id:'cc-foreign-doc',projectId:'cc-foreign-p',kind:Object.values(FileKind)[0] as any,name:'FOREIGN_SECRET.pdf'}]});
 await prisma.communicationAttachment.createMany({data:[...Array.from({length:101},(_,i)=>({id:'cc-a-'+String(i).padStart(3,'0'),threadId:'cc-thread',name:'Historischer Anhang '+i,createdAt:new Date(Date.UTC(2026,0,1,0,0,i))})),{id:'cc-doc-a',threadId:'cc-thread',documentId:'cc-doc',name:'Nachweis',createdAt:new Date('2026-02-01')},{id:'cc-doc-d',threadId:'cc-thread',documentId:'cc-deleted-doc',name:'Gelöscht',createdAt:new Date('2026-02-02')},{id:'cc-doc-f',threadId:'cc-thread',documentId:'cc-foreign-doc',name:'Rogue fixture',createdAt:new Date('2026-02-03')}]});
 const models=['communicationThread','communicationMessage','communicationAttachment','document','party','contractCertificate','partyInsurancePolicy','invoice','vendorBill','payment','ledgerEntry'];
 async function original(){return JSON.stringify(await Promise.all(models.map(m=>prisma[m].findMany({orderBy:{id:'asc'}}))));}const before=await original();
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'cc-user',companyId:req.headers['x-company']||'cc-a',companyRole:req.headers['x-role']||'ADMIN'};next();});app.use('/contacts',contacts);app.use('/communication',communication);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path:string,body:any=undefined,method='GET',headers:any={}){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+path,{method,headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,data:await res.json() as any};}
 const base='/contacts/cc-party/communication',body={threadId:'cc-thread'};
 try{
 assert.equal((await call(base,undefined,'GET',{'x-no-user':'1'})).status,401);assert.equal((await call(base,undefined,'GET',{'x-role':'GAST'})).status,403);
 assert.equal((await call('/communication?projectId=cc-p',undefined,'GET',{'x-role':'BAULEITER'})).status,200);assert.equal((await call('/communication?projectId=cc-private',undefined,'GET',{'x-role':'BAULEITER'})).status,400);
 assert.equal((await call('/communication/cc-hidden/attachments',{documentId:'cc-doc'},'POST',{'x-role':'BAULEITER'})).status,404);
 assert.equal((await call('/communication/cc-thread/attachments',{documentId:'cc-foreign-doc'},'POST')).status,404);
 for(const role of ['BAULEITER','KALKULATOR'])assert.equal((await call(base,body,'POST',{'x-role':role})).status,403);
 assert.equal((await call(base+'/candidates')).status,400);assert.equal((await call(base+'/candidates?projectId=cc-foreign-p')).status,404);assert.equal((await call(base+'/candidates?projectId=cc-private',undefined,'GET',{'x-role':'BUCHHALTUNG'})).status,404);
 assert.equal((await call(base,{threadId:'cc-foreign-thread'},'POST')).status,404);assert.equal((await call(base,{threadId:'cc-hidden'},'POST',{'x-role':'BUCHHALTUNG'})).status,404);assert.equal((await call(base,{},'POST')).status,400);
 const made=await call(base,body,'POST');assert.equal(made.status,201,JSON.stringify(made.data));assert.equal(made.data.item.revision,1);assert.equal((await call(base,body,'POST')).status,409);
 const pair=await Promise.all([call(base,{threadId:'cc-empty'},'POST'),call(base,{threadId:'cc-empty'},'POST')]);assert.deepEqual(pair.map(x=>x.status).sort(),[201,409]);
 assert.equal((await call(base,{threadId:'cc-hidden'},'POST')).status,201);
 assert.equal((await call(base)).data.items.length,3);
 for(const role of ['BAULEITER','KALKULATOR','BUCHHALTUNG']){const read=await call(base,undefined,'GET',{'x-role':role});assert.equal(read.status,200);assert.equal(read.data.items.length,2);assert.ok(read.data.items.every((x:any)=>x.thread.project.id==='cc-p'));assert.equal((await call(base+'/cc-hidden',undefined,'GET',{'x-role':role})).status,404);assert.equal((await call(base+'/cc-hidden/history',undefined,'GET',{'x-role':role})).status,404);}
 assert.equal((await call(base,undefined,'GET',{'x-company':'cc-b'})).status,404);assert.equal((await call('/contacts/cc-other/communication/cc-thread')).status,404);
 const candidate=await call(base+'/candidates?projectId=cc-p');assert.equal(candidate.data.items.find((x:any)=>x.id==='cc-thread').link.archived,false);
 const detail=await call(base+'/cc-thread',undefined,'GET',{'x-role':'BAULEITER'});assert.equal(detail.status,200);assert.equal(detail.data.messages.length,100);assert.equal(detail.data.thread._count.messages,120);assert.equal(detail.data.messages[0].id,'cc-m-020');assert.equal(detail.data.messages[0].body,'<img src=x onerror=alert(1)> Nachricht 20');assert.equal(detail.data.messages[99].body.length,20000);assert.equal(detail.data.messages[99].bodyTruncated,true);assert.equal(detail.data.attachments.length,100);assert.equal(detail.data.thread._count.attachments,104);assert.ok(!JSON.stringify(detail.data).includes('FOREIGN_SECRET'));assert.equal(detail.data.attachments.find((x:any)=>x.id==='cc-doc-d').documentAvailable,false);assert.equal(detail.data.attachments.find((x:any)=>x.id==='cc-doc-a').name,'Nachweis.pdf');
 const removes=await Promise.all([call(base+'/cc-thread',{revision:1},'DELETE'),call(base+'/cc-thread',{revision:1},'DELETE')]);assert.deepEqual(removes.map(x=>x.status).sort(),[200,409]);
 assert.equal((await call(base)).data.items.length,2);assert.equal((await call(base+'?includeArchived=true')).data.items.length,3);assert.equal((await call(base,{...body,revision:1},'POST')).status,409);assert.equal((await call(base,{...body,revision:2},'POST')).status,201);
 const count=await prisma.auditLog.count();const linkBefore=JSON.stringify(await prisma.partyCommunicationLink.findUnique({where:{partyId_threadId:{partyId:'cc-party',threadId:'cc-thread'}}}));
 await prisma.$executeRawUnsafe("CREATE FUNCTION public.reject_contact_comm_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='CONTACT_COMMUNICATION_UNLINK' THEN RAISE EXCEPTION 'Isolated contact communication rollback test'; END IF; RETURN NEW; END $$");await prisma.$executeRawUnsafe('CREATE TRIGGER reject_contact_comm_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION public.reject_contact_comm_audit()');
 try{assert.equal((await call(base+'/cc-thread',{revision:3},'DELETE')).status,503);assert.equal(JSON.stringify(await prisma.partyCommunicationLink.findUnique({where:{partyId_threadId:{partyId:'cc-party',threadId:'cc-thread'}}})),linkBefore);assert.equal(await prisma.auditLog.count(),count);}
 finally{await prisma.$executeRawUnsafe('DROP TRIGGER reject_contact_comm_audit ON "AuditLog"');await prisma.$executeRawUnsafe('DROP FUNCTION public.reject_contact_comm_audit()');}
 assert.equal((await call('/communication/cc-empty',undefined,'DELETE')).status,409);assert.equal((await call(base+'/cc-empty',{revision:1},'DELETE')).status,200);assert.equal((await call('/communication/cc-empty',undefined,'DELETE')).status,409);
 const contact=(await call('/contacts?includeArchived=true')).data.items.find((x:any)=>x.id==='cc-party');assert.equal((await call('/contacts/cc-party/archive',{expectedVersion:contact.version},'POST')).status,200);assert.equal((await call(base+'/cc-thread',{revision:3},'DELETE')).status,200);assert.equal((await call(base,{...body,revision:4},'POST')).status,409);
 assert.equal((await call('/contacts/cc-other/communication',body,'POST')).status,201);assert.equal((await call('/contacts/cc-other/communication/cc-thread')).status,200);
 const hist=await call(base+'/cc-thread/history');assert.equal(hist.data.items.length,4);assert.ok(hist.data.items.some((x:any)=>x.action==='CONTACT_COMMUNICATION_RESTORE'));
 await assert.rejects(prisma.party.delete({where:{id:'cc-party'}}));await assert.rejects(prisma.communicationThread.delete({where:{id:'cc-empty'}}));
 assert.equal(await original(),before);
 console.log('PASS contact communication: existing project membership lookup corrected; explicit multi-contact thread links, tenant/project/member scope including history and accounting membership, readonly bounded 100-message/attachment snapshots, literal text and unavailable/foreign-document metadata masking, unread/message/document/accounting rows unchanged, duplicate and concurrent link/unlink version checks, restoration and archived-contact guard, atomic audit rollback, preserved removal history and linked empty-thread deletion refusal.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
