import assert from 'node:assert/strict';import fs from 'fs';import os from 'os';import path from 'path';import crypto from 'crypto';import express from 'express';import http from 'http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_diary_validation_20261009';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';const root=fs.mkdtempSync(path.join(os.tmpdir(),'rlc-diary-test-'));process.env.PROJECTS_ROOT=root;
const {prisma}=require('../lib/prisma'),router=require('../routes/diaryTimeExport').default,{diaryTimeRows,diaryMonth,normalizeDiaryReport,diaryTimeCsv}=require('../domain/diaryTimeExport'),{approvedDiarySources}=require('../services/diaryTimeExport');
const line={mitarbeiter:'Worker A',von:'08:00',bis:'16:30',pauseMin:30,stunden:'8',taetigkeit:'=FORMULA',ort:'Office'};const make=(id:string,date='2026-10-08',lines:any[]=[line])=>({id,sourceDocId:id,projectId:'diary-p',date,workflowStatus:'FREIGEGEBEN',reportType:'TAGESBERICHT',lines});const type={code:'ARBEIT',label:'Arbeit'};
async function main(){
 await prisma.company.createMany({data:[{id:'diary-a',code:'DIARY-A',name:'Fiktiv A'},{id:'diary-b',code:'DIARY-B',name:'Fiktiv B'}]});await prisma.user.create({data:{id:'diary-user',companyId:'diary-a',email:'diary@test.invalid',password:'test'}});await prisma.project.createMany({data:[{id:'diary-p',companyId:'diary-a',code:'DIARY-P',name:'Project A'},{id:'diary-hidden',companyId:'diary-a',code:'DIARY-HIDDEN',name:'Hidden'},{id:'diary-foreign',companyId:'diary-b',code:'DIARY-FOREIGN',name:'Foreign'}]});await prisma.projectMember.create({data:{projectId:'diary-p',userId:'diary-user',role:'BAULEITER'}});await prisma.companyMasterCatalog.createMany({data:[{id:'diary-type',companyId:'diary-a',kind:'TIME_TYPE',code:'ARBEIT',label:'Arbeit'},{id:'diary-inactive',companyId:'diary-a',kind:'TIME_TYPE',code:'ALT',label:'Alt',active:false},{id:'diary-unit',companyId:'diary-a',kind:'UNIT',code:'STK',label:'Stück'},{id:'diary-foreign-type',companyId:'diary-b',kind:'TIME_TYPE',code:'ARBEIT',label:'Foreign'}]});await prisma.companyMaterial.create({data:{id:'diary-mat',companyId:'diary-a',name:'Preserved',stock:17,priceNet:'12.34'}});await prisma.companyEmployee.create({data:{id:'diary-employee',companyId:'diary-a',name:'Existing',hourlyRate:'32.10'}});
 const dir=path.join(root,'diary-p','tagesbericht');fs.mkdirSync(dir,{recursive:true});const original=JSON.stringify({id:'source-1',sourceDocId:'source-1',projectId:'diary-p',date:'2026-10-08',workflowStatus:'FREIGEGEBEN',reportId:'001',rows:[{...make('source-1'),workflowStatus:'EINGEREICHT',notes:'Preserved',lines:[line]}],evidenceLock:{hash:'existing-hash'}});const official=path.join(dir,'Tagesbericht_2026-10-08_001.json');fs.writeFileSync(official,original);fs.writeFileSync(path.join(dir,'Tagesbericht_2026-10-08_002.json'),JSON.stringify({...make('rejected'),workflowStatus:'ABGELEHNT'}));fs.writeFileSync(path.join(dir,'Tagesbericht_2026-09-08_001.json'),JSON.stringify(make('last-month','2026-09-08',[{...line,mitarbeiter:'Worker B'}])));fs.mkdirSync(path.join(root,'diary-p','eingangspruefung','tagesbericht'),{recursive:true});fs.writeFileSync(path.join(root,'diary-p','eingangspruefung','tagesbericht','draft.json'),JSON.stringify({...make('draft'),workflowStatus:'EINGEREICHT'}));
 const app=express();app.use((req:any,_res,next)=>{req.auth={companyId:req.headers['x-company']||'diary-a',sub:req.headers['x-no-user']?'':'diary-user',companyRole:req.headers['x-role']||'ADMIN'};next();});app.use('/export',router);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 const query='?projectId=diary-p&month=2026-10&timeTypeId=diary-type';async function call(q=query,h:any={}){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+'/export'+q,{headers:h});return {status:res.status,data:await res.json() as any};}
 try{
 assert.equal(require('../domain/masterCatalog').catalogInput({kind:'TIME_TYPE',code:' ARBEIT ',label:'Arbeit'}).kind,'TIME_TYPE');assert.equal(diaryMonth('2026-10'),'2026-10');for(const v of ['2026-00','2026-13','26-10',null])assert.throws(()=>diaryMonth(v));
 let r=diaryTimeRows([make('x')],type);assert.equal(r.totalMinutes,480);assert.equal(r.issues.length,0);assert.equal(r.rows[0].breakMinutes,30);
 for(const patch of [{mitarbeiter:''},{von:'25:00'},{bis:''},{pauseMin:'0.5'},{pauseMin:600},{stunden:'-1'},{stunden:'7.5'},{stunden:'NaN'},{stunden:25},{von:'22:00',bis:'06:00'},{von:'08:00',bis:'16:00',overnight:true},{stunden:{value:8}}])assert.ok(diaryTimeRows([make('x','2026-10-08',[{...line,...patch}])],type).issues.length);
 assert.equal(diaryTimeRows([make('x','2026-02-30')],type).issues.length,1);r=diaryTimeRows([make('x','2026-10-08',[{mitarbeiter:'Night',von:'22:00',bis:'06:00',overnight:true,stunden:8,pauseMin:0}])],type);assert.equal(r.totalMinutes,480);assert.equal(r.issues.length,0);
 r=diaryTimeRows([make('x','2026-10-08',[{mitarbeiter:'Rounded',stunden:'0,33'}])],type);assert.equal(r.totalMinutes,20);assert.ok(r.rows[0].basis.includes('gerundet'));assert.equal(diaryTimeRows([make('x','2026-10-08',[{mitarbeiter:'Rounded',stunden:1,pauseMin:10}])],type).issues.length,1);
 r=diaryTimeRows([make('x','2026-10-08',[{maschine:'Excavator',stunden:2}])],type);assert.equal(r.rows.length,0);assert.equal(r.skipped.length,1);assert.equal(r.issues.length,0);assert.equal(diaryTimeRows([make('x','2026-10-08',[])],type).skipped.length,1);
 assert.ok(diaryTimeRows([make('x'),make('x')],type).issues.some((x:any)=>x.error.includes('mehrfach')));assert.ok(diaryTimeRows([make('x'),make('y')],type).issues.some((x:any)=>x.error.includes('überschneidung')));assert.equal(diaryTimeRows([make('x'),make('y','2026-10-09')],type).issues.length,0);
 r=diaryTimeRows([make('x','2026-10-08',[{mitarbeiter:'Night',von:'22:00',bis:'06:00',overnight:true,stunden:8,pauseMin:0}]),make('y','2026-10-09',[{mitarbeiter:'Night',von:'05:00',bis:'07:00',stunden:2,pauseMin:0}])],type);assert.ok(r.issues.some((x:any)=>x.error.includes('überschneidung')));
 assert.throws(()=>diaryTimeRows(Array.from({length:11},(_,i)=>make('limit-'+i,'2026-10-08',Array.from({length:1000},()=>({mitarbeiter:'Test',stunden:1})))),type),/Zu viele Zeitzeilen/);
 const normalized=normalizeDiaryReport(JSON.parse(original),'test.json');assert.equal(normalized.workflowStatus,'FREIGEGEBEN');assert.equal(normalized.lines.length,1);assert.equal(normalized.evidenceLock.hash,'existing-hash');
 for(const role of ['BUCHHALTUNG','KALKULATOR','CAPOCANTIERE','MITARBEITER','GAST'])assert.equal((await call(query,{'x-role':role})).status,403);assert.equal((await call(query,{'x-no-user':'1'})).status,403);assert.equal((await call(query,{'x-company':'diary-b'})).status,403);assert.equal((await call(query.replace('diary-p','diary-hidden'),{'x-role':'BAULEITER'})).status,403);
 for(const id of ['diary-inactive','diary-unit','diary-foreign-type'])assert.equal((await call(query.replace('diary-type',id))).status,400);
 const preview=await call(query,{'x-role':'BAULEITER'});assert.equal(preview.status,200);assert.equal(preview.data.rows.length,1);assert.equal(preview.data.reportCount,1);assert.equal(preview.data.canExport,true);assert.equal(preview.data.totalMinutes,480);assert.equal((await call(query.replace('diary-p','DIARY-P'))).status,200);assert.equal((await call('/csv'+query)).status,409);
 const download=await call('/csv'+query+'&expectedFingerprint='+preview.data.fingerprint);assert.equal(download.status,200);assert.ok(download.data.csv.startsWith('\uFEFF'));assert.ok(download.data.csv.includes('"\'=FORMULA"'));assert.equal(JSON.stringify(preview.data).includes('32.10'),false);assert.equal(JSON.stringify(preview.data).includes('ABGELEHNT'),false);
 await prisma.companyMasterCatalog.update({where:{id:'diary-type'},data:{label:'Changed'}});assert.equal((await call('/csv'+query+'&expectedFingerprint='+preview.data.fingerprint)).status,409);let latest=(await call()).data;assert.equal(latest.timeType.label,'Changed');
 fs.writeFileSync(official,JSON.stringify({...JSON.parse(original),notes:'Source changed'}));assert.equal((await call('/csv'+query+'&expectedFingerprint='+latest.fingerprint)).status,409);fs.writeFileSync(official,original);
 const invalidFile=path.join(dir,'Tagesbericht_2026-10-09_001.json');fs.writeFileSync(invalidFile,JSON.stringify(make('invalid','2026-10-09',[{...line,stunden:1}])));latest=(await call()).data;assert.equal(latest.canExport,false);assert.equal((await call('/csv'+query+'&expectedFingerprint='+latest.fingerprint)).status,422);fs.writeFileSync(invalidFile,'broken-json');assert.equal((await call()).status,503);fs.writeFileSync(invalidFile,JSON.stringify(make('wrong-date','2026-10-08')));assert.equal((await call()).status,409);fs.writeFileSync(invalidFile,JSON.stringify({...make('foreign','2026-10-09'),projectId:'diary-foreign'}));assert.equal((await call()).status,409);fs.unlinkSync(invalidFile);
 const legacy=path.join(root,'DIARY-HIDDEN','tagesbericht');fs.mkdirSync(legacy,{recursive:true});fs.writeFileSync(path.join(legacy,'Tagesbericht_2026-10-08_001.json'),JSON.stringify({...make('legacy'),projectId:'diary-hidden'}));assert.equal((await call(query.replace('diary-p','diary-hidden'))).status,200);assert.equal(fs.existsSync(path.join(root,'diary-hidden')),false);await prisma.project.create({data:{id:'diary-duplicate-code',companyId:'diary-b',code:'DIARY-HIDDEN',name:'Duplicate'}});assert.equal((await call(query.replace('diary-p','diary-hidden'))).status,409);
 assert.equal(fs.readFileSync(official,'utf8'),original);assert.equal(await prisma.auditLog.count(),0);assert.equal(await prisma.workflowDoc.count(),0);assert.equal(await prisma.ledgerEntry.count(),0);assert.equal((await prisma.companyMaterial.findUnique({where:{id:'diary-mat'}})).stock,17);assert.equal(String((await prisma.companyEmployee.findUnique({where:{id:'diary-employee'}})).hourlyRate),'32.1');
 console.log('PASS diary time export: two-company/project/personnel scopes, approved-only and wrapped sources, strict dates/minutes/pauses/overnight/overlap, visible skips and blocked invalid rows, CSV formula protection, source/catalog revision checks, legacy ambiguity, source failure not empty, unchanged reports/payroll/inventory/accounting and no writes.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();fs.rmSync(root,{recursive:true,force:true});}
}
main().catch(e=>{console.error(e);fs.rmSync(root,{recursive:true,force:true});process.exitCode=1;});
