import assert from 'node:assert/strict';import express from 'express';import http from 'node:http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_catalog_validation_20261009';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),router=require('../routes/masterCatalog').default;
async function main(){
 await prisma.company.createMany({data:[{id:'cat-a',name:'Fiktiv A',code:'CAT-A'},{id:'cat-b',name:'Fiktiv B',code:'CAT-B'}]});await prisma.user.create({data:{id:'cat-user',email:'catalog@test.invalid',password:'test',companyId:'cat-a'}});
 await prisma.project.create({data:{id:'cat-project',name:'Existing',code:'CAT-PROJECT',companyId:'cat-a'}});await prisma.companyMaterial.create({data:{id:'cat-material',companyId:'cat-a',name:'Existing material',unit:'Stk',stock:5,priceNet:100}});await prisma.projectCostCenter.create({data:{id:'cat-cost',companyId:'cat-a',projectId:'cat-project',code:'EXISTING',description:'Existing',mainArea:'Alte Gruppe',budget:123.45}});await prisma.companyEmployee.create({data:{id:'cat-employee',companyId:'cat-a',name:'Existing employee'}});await prisma.companyEmployeeCertificate.create({data:{id:'cat-cert',employeeId:'cat-employee',name:'Existing certificate'}});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'cat-user',companyId:req.headers['x-company']||'cat-a',companyRole:req.headers['x-role']||'ADMIN'};next();});app.use('/catalog',router);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path='',method='GET',body:any=undefined,headers:any={}){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+'/catalog'+path,{method,headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,data:await res.json() as any};}
 const base={kind:'UNIT',code:' m2 ',label:'Quadratmeter',symbol:'m²',notes:'Fiktiver Test'};
 try{
  assert.equal((await call('?kind=UNIT','GET',undefined,{'x-no-user':'1'})).status,403);assert.equal((await call('?kind=bad')).status,400);
  for(const role of ['BAULEITER','BUCHHALTUNG','KALKULATOR','MITARBEITER']){assert.equal((await call('','POST',base,{'x-role':role})).status,403);assert.equal((await call('?kind=UNIT','GET',undefined,{'x-role':role})).status,200);assert.equal((await call('?kind=UNIT','GET',undefined,{'x-role':role})).data.canEdit,false);}
  for(const patch of [{code:''},{code:'a'.repeat(41)},{code:'A B'},{label:true},{label:' '},{kind:'OTHER'},{kind:'LICENSE_CLASS',symbol:'m²'},{active:'true'}])assert.equal((await call('','POST',{...base,...patch})).status,400);
  const made=await call('','POST',base);assert.equal(made.status,201);let row=made.data.item;assert.equal(row.code,'M2');assert.equal(await prisma.auditLog.count(),1);
  assert.equal((await call('','POST',{...base,code:'M2',label:'Overwrite'})).status,409);assert.equal((await prisma.companyMasterCatalog.findUnique({where:{id:row.id}})).label,'Quadratmeter');assert.equal(await prisma.auditLog.count(),1);
  const pair=await Promise.all([call('/'+row.id,'PUT',{label:'Area A',expectedUpdatedAt:row.updatedAt}),call('/'+row.id,'PUT',{label:'Area B',expectedUpdatedAt:row.updatedAt})]);assert.deepEqual(pair.map(x=>x.status).sort(),[200,409]);row=pair.find(x=>x.status===200)!.data.item;
  assert.equal((await call('/'+row.id,'PUT',{label:'No version'})).status,400);assert.equal((await call('/'+row.id,'PUT',{code:'OTHER',expectedUpdatedAt:row.updatedAt})).status,400);assert.equal((await call('/'+row.id,'PUT',{kind:'LICENSE_CLASS',expectedUpdatedAt:row.updatedAt})).status,400);
  const foreign=await call('','POST',{...base,label:'FOREIGN'}, {'x-company':'cat-b'});assert.equal(foreign.status,201);assert.equal((await call('/'+foreign.data.item.id+'/history')).status,404);assert.equal((await call('/'+foreign.data.item.id,'DELETE',{expectedUpdatedAt:foreign.data.item.updatedAt})).status,404);assert.equal(JSON.stringify((await call('?kind=UNIT')).data).includes('FOREIGN'),false);
  const archived=await call('/'+row.id,'DELETE',{expectedUpdatedAt:row.updatedAt});assert.equal(archived.status,200);assert.equal((await call('?kind=UNIT')).data.items.length,0);assert.equal((await call('?kind=UNIT&includeInactive=true')).data.items.length,1);assert.equal((await call('','POST',base)).status,409);
  assert.equal((await call('/'+row.id,'PUT',{active:true,expectedUpdatedAt:row.updatedAt})).status,409);row=archived.data.item;const restored=await call('/'+row.id,'PUT',{active:true,expectedUpdatedAt:row.updatedAt});assert.equal(restored.status,200);row=restored.data.item;
  const history=await call('/'+row.id+'/history');assert.equal(history.data.items.length,4);assert.ok(history.data.items.some((x:any)=>x.action==='MASTER_CATALOG_RESTORE'));
  for(const kind of ['LICENSE_CLASS','HAZARD_CLASS','COST_CENTER_AREA'])assert.equal((await call('','POST',{kind,code:'CUSTOM-01',label:'Manueller Test'})).status,201);
  assert.equal((await call('?kind=LICENSE_CLASS')).data.items.length,1);assert.equal((await call('?kind=UNIT')).data.items.length,1);
  const creates=await Promise.all([call('','POST',{...base,code:'STK'}),call('','POST',{...base,code:'stk'})]);assert.deepEqual(creates.map(x=>x.status).sort(),[201,409]);assert.equal(await prisma.companyMasterCatalog.count({where:{companyId:'cat-a',kind:'UNIT',code:'STK'}}),1);
  const before=await prisma.companyMasterCatalog.findUnique({where:{id:row.id}}),audits=await prisma.auditLog.count();await prisma.$executeRawUnsafe('ALTER TABLE "AuditLog" RENAME TO "_CatalogAuditUnavailable"');try{assert.equal((await call('/'+row.id,'PUT',{label:'Must rollback',expectedUpdatedAt:row.updatedAt})).status,500);}finally{await prisma.$executeRawUnsafe('ALTER TABLE "_CatalogAuditUnavailable" RENAME TO "AuditLog"');}const after=await prisma.companyMasterCatalog.findUnique({where:{id:row.id}});assert.equal(after.label,before.label);assert.equal(after.updatedAt.toISOString(),before.updatedAt.toISOString());assert.equal(await prisma.auditLog.count(),audits);
  assert.equal(await prisma.companyMaterial.count(),1);const material=await prisma.companyMaterial.findUnique({where:{id:'cat-material'}});assert.equal(material.unit,'Stk');assert.equal(material.stock,5);assert.equal(String(material.priceNet),'100');assert.equal(await prisma.projectCostCenter.count(),1);const cost=await prisma.projectCostCenter.findUnique({where:{id:'cat-cost'}});assert.equal(cost.mainArea,'Alte Gruppe');assert.equal(String(cost.budget),'123.45');assert.equal(await prisma.companyEmployeeCertificate.count(),1);assert.equal((await prisma.companyEmployeeCertificate.findUnique({where:{id:'cat-cert'}})).name,'Existing certificate');assert.equal(await prisma.ledgerEntry.count(),0);
  console.log('PASS master catalog PostgreSQL: tenant/admin/read scopes, strict text/kind/code normalization, duplicate protection, mandatory concurrent revisions, immutable kind/code, archive/restore/history, kinds separated, concurrent create and atomic audit rollback, no changes to material/cost/personnel/accounting records.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
