import assert from 'node:assert/strict';import express from 'express';import http from 'node:http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_nonworking_validation_20261009';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),router=require('../routes/officeCalendar').default,{berlinMidnight,nonWorkingRange}=require('../domain/nonWorkingDay');
async function main(){
 assert.equal((berlinMidnight('2026-03-30').getTime()-berlinMidnight('2026-03-29').getTime())/3600000,23);assert.equal((berlinMidnight('2026-10-26').getTime()-berlinMidnight('2026-10-25').getTime())/3600000,25);assert.equal(nonWorkingRange('2028-02-28','2028-03-01').length,3);assert.throws(()=>nonWorkingRange('2026-02-30'));assert.throws(()=>nonWorkingRange('2026-01-01','2027-01-02'));
 await prisma.company.createMany({data:[{id:'nw-a',name:'Fiktiv A',code:'NW-A'},{id:'nw-b',name:'Fiktiv B',code:'NW-B'}]});await prisma.user.create({data:{id:'nw-user',email:'nonworking@test.invalid',password:'test',companyId:'nw-a'}});
 await prisma.project.createMany({data:[{id:'nw-pa',name:'A',code:'NW-PA',companyId:'nw-a'},{id:'nw-hidden',name:'Hidden',code:'NW-HIDDEN',companyId:'nw-a'},{id:'nw-pb',name:'B',code:'NW-PB',companyId:'nw-b'}]});await prisma.projectMember.create({data:{projectId:'nw-pa',userId:'nw-user',role:'BAULEITER'}});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'nw-user',companyId:req.headers['x-company']||'nw-a',companyRole:req.headers['x-role']||'ADMIN'};next();});app.use('/calendar',router);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path:string,method='GET',body:any=undefined,headers:any={}){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+'/calendar'+path,{method,headers:{'Content-Type':'application/json',...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:res.status,data:await res.json() as any};}
 const base={date:'2026-10-25',title:'Test shutdown',kind:'BETRIEBSRUHE',location:'',notes:'Test only'},endpoint='/non-working-days';
 try{
  assert.equal((await call(endpoint+'?year=2026','GET',undefined,{'x-no-user':'1'})).status,403);for(const role of ['BAULEITER','BUCHHALTUNG','KALKULATOR','MITARBEITER'])assert.equal((await call(endpoint,'POST',base,{'x-role':role})).status,403);
  for(const date of ['2026-02-30','2026-2-02','bad','2026-10-25T00:00:00Z',null])assert.equal((await call(endpoint,'POST',{...base,date})).status,400);
  assert.equal((await call(endpoint,'POST',{...base,kind:'OTHER'})).status,400);assert.equal((await call(endpoint,'POST',{...base,title:true})).status,400);
  const made=await call(endpoint,'POST',base);assert.equal(made.status,201);let row=made.data.items[0];assert.equal(row.date,'2026-10-25');const stored=await prisma.officeCalendarEvent.findUnique({where:{id:row.id}});assert.equal((stored.end.getTime()-stored.start.getTime())/3600000,25);assert.equal(await prisma.auditLog.count(),1);
  assert.equal((await call(endpoint,'POST',base)).status,409);assert.equal(await prisma.auditLog.count(),1);
  const updates=await Promise.all([call(endpoint+'/'+row.id,'PUT',{title:'A',expectedUpdatedAt:row.updatedAt}),call(endpoint+'/'+row.id,'PUT',{title:'B',expectedUpdatedAt:row.updatedAt})]);assert.deepEqual(updates.map(x=>x.status).sort(),[200,409]);row=updates.find(x=>x.status===200)!.data.item;
  assert.equal((await call(endpoint+'/'+row.id,'PUT',{title:'No version'})).status,400);
  assert.equal((await call('/'+row.id,'PUT',{title:'Bypass'})).status,409);assert.equal((await call('/'+row.id,'DELETE')).status,409);
  assert.equal((await call('','POST',{title:'Bypass',start:'2026-10-25',end:'2026-10-26',projectId:'NW-PA',sourceType:'COMPANY_NON_WORKING_DAY'}, {'x-role':'BAULEITER'})).status,409);
  const companyB=await call(endpoint,'POST',{...base,title:'FOREIGN'}, {'x-company':'nw-b'});const foreign=companyB.data.items[0];assert.equal((await call(endpoint+'/'+foreign.id+'/history')).status,404);assert.equal((await call(endpoint+'/'+foreign.id,'DELETE',{expectedUpdatedAt:foreign.updatedAt})).status,404);assert.equal(JSON.stringify((await call(endpoint+'?year=2026')).data).includes('FOREIGN'),false);
  const regular=await call('','POST',{title:'Normal project meeting',start:'2026-10-25T09:00:00Z',end:'2026-10-25T10:00:00Z',projectId:'NW-PA'},{'x-role':'BAULEITER'});assert.equal(regular.status,200);
  const view=await call('?projectId=NW-PA&rangeStart=2026-10-25&rangeEnd=2026-10-26','GET',undefined,{'x-role':'BAULEITER'});assert.equal(view.status,200);assert.ok(view.data.items.some((x:any)=>x.id===row.id));assert.ok(view.data.items.some((x:any)=>x.id===regular.data.item.id));assert.equal((await call('?projectId=NW-HIDDEN','GET',undefined,{'x-role':'BAULEITER'})).status,404);
  const archive=await call(endpoint+'/'+row.id,'DELETE',{expectedUpdatedAt:row.updatedAt});assert.equal(archive.status,200);row=archive.data.item;assert.equal((await call(endpoint+'?year=2026')).data.items.length,0);assert.equal((await call(endpoint+'?year=2026&includeArchived=true')).data.items.length,1);assert.ok(!(await call('?projectId=NW-PA','GET',undefined,{'x-role':'BAULEITER'})).data.items.some((x:any)=>x.id===row.id));assert.ok((await call('','GET',undefined,{'x-role':'BAULEITER'})).data.items.some((x:any)=>x.id===regular.data.item.id));
  const restore=await call(endpoint+'/'+row.id,'PUT',{active:true,expectedUpdatedAt:row.updatedAt});assert.equal(restore.status,200);row=restore.data.item;
  const duplicatePair=await Promise.all([call(endpoint,'POST',{...base,date:'2026-03-29'}),call(endpoint,'POST',{...base,date:'2026-03-29'})]);assert.deepEqual(duplicatePair.map(x=>x.status).sort(),[201,409]);
  const counts=await prisma.officeCalendarEvent.count();assert.equal((await call(endpoint,'POST',{...base,date:'2026-10-24',toDate:'2026-10-26'})).status,409);assert.equal(await prisma.officeCalendarEvent.count(),counts);assert.equal((await call(endpoint,'POST',{...base,date:'2026-12-28',toDate:'2026-12-30'})).data.items.length,3);
  const h=await call(endpoint+'/'+row.id+'/history');assert.equal(h.status,200);assert.equal(h.data.items.length,4);assert.ok(h.data.items.some((x:any)=>x.action==='NON_WORKING_DAY_RESTORE'));
  const before=await prisma.officeCalendarEvent.findUnique({where:{id:row.id}}),audits=await prisma.auditLog.count();await prisma.$executeRawUnsafe('ALTER TABLE "AuditLog" RENAME TO "_NonWorkingAuditUnavailable"');try{assert.equal((await call(endpoint+'/'+row.id,'PUT',{title:'Must roll back',expectedUpdatedAt:row.updatedAt})).status,500);}finally{await prisma.$executeRawUnsafe('ALTER TABLE "_NonWorkingAuditUnavailable" RENAME TO "AuditLog"');}const after=await prisma.officeCalendarEvent.findUnique({where:{id:row.id}});assert.equal(after.title,before.title);assert.equal(after.updatedAt.toISOString(),before.updatedAt.toISOString());assert.equal(await prisma.auditLog.count(),audits);
  const yearRange=await call(endpoint,'POST',{...base,date:'2028-01-01',toDate:'2028-12-31',location:'Test annual closure'});assert.equal(yearRange.status,201);assert.equal(yearRange.data.items.length,366);assert.equal((await call(endpoint+'?year=2028')).data.items.length,366);assert.equal((await call(endpoint+'?year=2199')).status,200);assert.equal((await call(endpoint+'?year=2026','GET',undefined,{'x-role':'BAULEITER'})).data.canEdit,false);
  assert.equal(await prisma.resourceAssignment.count(),0);assert.equal(await prisma.ledgerEntry.count(),0);assert.equal(await prisma.accountingRoot.count(),0);
  console.log('PASS non-working calendar PostgreSQL: tenant/admin/read scopes, strict dates, leap year and Berlin 23/25h days, duplicate/concurrent create/update, mandatory revision, archive/restore/history, atomic range/audit rollback, protected calendar integration and normal events retained, no planning/accounting writes.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
