import assert from 'node:assert/strict';import express from 'express';import http from 'http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_plan_resource_validation_20261010';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';process.env.COMPANIES_ROOT='/tmp/rlc-plan-resource-test';
const {prisma}=require('../lib/prisma'),router=require('../routes/buero/bauzeitenplan').default,assignments=require('../routes/resources.costs').default;
async function main(){
 await prisma.company.createMany({data:[{id:'pr-a',code:'PR-A',name:'Fiktiv A'},{id:'pr-b',code:'PR-B',name:'Fiktiv B'}]});await prisma.user.create({data:{id:'pr-user',companyId:'pr-a',email:'plan-resource@test.invalid',password:'test'}});await prisma.project.createMany({data:[{id:'pr-p',companyId:'pr-a',code:'PR-P',name:'A'},{id:'pr-hidden',companyId:'pr-a',code:'PR-HIDDEN',name:'Hidden'},{id:'pr-foreign',companyId:'pr-b',code:'PR-B-P',name:'B'}]});await prisma.projectMember.create({data:{projectId:'pr-p',userId:'pr-user',role:'BAULEITER'}});
 await prisma.companyEmployee.createMany({data:[{id:'pr-e',companyId:'pr-a',name:'Fiktiv A',hourlyRate:'23.45'},{id:'pr-foreign-e',companyId:'pr-b',name:'Fiktiv B'}]});await prisma.companyMachine.createMany({data:[{id:'pr-m',companyId:'pr-a',name:'Fiktive Maschine',hours:10,hourlyRate:'42.00'},{id:'pr-hidden-m',companyId:'pr-a',name:'Hidden machine',projectId:'pr-hidden'}]});await prisma.companyMaterial.create({data:{id:'pr-material',companyId:'pr-a',name:'Existing',stock:11}});
 const {berlinMidnight,nextCalendarDay,NON_WORKING_DAY}=require('../domain/nonWorkingDay');await prisma.officeCalendarEvent.create({data:{companyId:'pr-a',title:'Fiktiver Ruhetag',start:berlinMidnight('2026-10-13'),end:berlinMidnight(nextCalendarDay('2026-10-13')),allDay:true,attendees:[],sourceType:NON_WORKING_DAY}});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'pr-user',companyId:req.headers['x-company']||'pr-a',companyRole:req.headers['x-role']||'BAULEITER'};next();});app.use('/plan',router);app.use('/resources',assignments);app.use((e:any,_req:any,res:any,_next:any)=>res.status(503).json({error:e.message}));const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path:string,body:any=undefined,headers:any={},method=body===undefined?'GET':'POST'){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+path,{method,headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,data:await res.json() as any};}
 try{
 let v=(await call('/plan/load',{projectId:'pr-p'})).data.version;const planBody={projectId:'pr-p',expectedVersion:v,start:'2026-10-12',capacity:{Bagger:1},tasks:[{id:'pr-t',name:'Fiktiver Vorgang',dauerTage:7,start:'2026-10-12',end:'2026-10-18',progress:0,notes:'Original',assignee:'Fiktiv',milestone:false,deps:[],ressourcen:{Bagger:1}}]};let saved=await call('/plan/save',planBody);assert.equal(saved.status,200);v=saved.data.version;
 const options=(await call('/plan/resource-options',{projectId:'PR-P'})).data;assert.deepEqual(options.employees.map((r:any)=>r.id),['pr-e']);assert.deepEqual(options.machines.map((r:any)=>r.id),['pr-m']);assert.equal(options.employees[0].hourlyRate,undefined);
 let body={projectId:'pr-p',taskId:'pr-t',expectedVersion:v,resourceType:'EMPLOYEE',resourceId:'pr-e',from:'2026-10-12',to:'2026-10-18',hours:8,weekdays:[1,2,3,4,5],excludeNonWorking:true,requirement:'Bagger'};
 for(const h of [{'x-company':'pr-b'},{'x-role':'GAST'},{'x-no-user':'1'}])assert.equal((await call('/plan/resource-preview',body,h)).status,403);
 assert.equal((await call('/plan/resource-preview',{...body,projectId:'pr-hidden'})).status,403);assert.equal((await call('/plan/resource-preview',{...body,resourceId:'pr-foreign-e'})).status,403);
 for(const patch of [{from:'2026-02-30'},{from:'2026-10-11'},{to:'2026-10-19'},{weekdays:[]},{weekdays:[1,1]},{hours:25},{hours:0},{hours:1.001},{hours:'8'},{requirement:'missing'},{excludeNonWorking:'true'}])assert.equal((await call('/plan/resource-preview',{...body,...patch})).status,400);
 let preview=await call('/plan/resource-preview',body);assert.equal(preview.status,200);assert.equal(preview.data.newCount,4);assert.equal(preview.data.days.filter((r:any)=>r.status==='nonworking').length,1);assert.equal(preview.data.days.filter((r:any)=>r.status==='weekday').length,2);assert.equal(await prisma.resourceAssignment.count(),0);
 const pair=await Promise.all([call('/plan/resource-commit',{...body,fingerprint:preview.data.fingerprint}),call('/plan/resource-commit',{...body,fingerprint:preview.data.fingerprint})]);assert.deepEqual(pair.map(r=>r.status),[200,200]);assert.deepEqual(pair.map(r=>r.data.createdCount).sort(),[0,4]);assert.equal(await prisma.resourceAssignment.count(),4);assert.equal(await prisma.auditLog.count({where:{action:'PLAN_RESOURCE_HANDOFF'}}),1);
 const first=await prisma.resourceAssignment.findFirst({where:{date:new Date('2026-10-12T12:00Z')}});let edit=await call('/resources/assignments/'+first.id,{hours:6,notes:'Manual target edit',updatedAt:first.updatedAt.toISOString()},{},'PUT');assert.equal(edit.status,200);preview=await call('/plan/resource-preview',body);assert.equal(preview.data.existingCount,4);assert.equal((await call('/plan/resource-commit',{...body,fingerprint:preview.data.fingerprint})).data.createdCount,0);assert.equal((await prisma.resourceAssignment.findUnique({where:{id:first.id}})).notes,'Manual target edit');
 let machine={...body,resourceType:'MACHINE',resourceId:'pr-m',from:'2026-10-12',to:'2026-10-12',excludeNonWorking:false};let mp=await call('/plan/resource-preview',machine);await call('/resources/assignments',{resourceType:'MACHINE',resourceId:'pr-m',projectId:'pr-p',date:'2026-10-12',hours:18});assert.equal((await call('/plan/resource-commit',{...machine,fingerprint:mp.data.fingerprint})).status,409);mp=await call('/plan/resource-preview',machine);assert.equal(mp.data.blocked,true);assert.equal((await call('/plan/resource-commit',{...machine,fingerprint:mp.data.fingerprint})).status,409);
 const concurrent={resourceType:'MACHINE',resourceId:'pr-m',projectId:'pr-p',date:'2026-10-15',hours:16};const capacity=await Promise.all([call('/resources/assignments',concurrent),call('/resources/assignments',concurrent)]);assert.deepEqual(capacity.map(r=>r.status).sort(),[200,409]);
 machine={...machine,from:'2026-10-14',to:'2026-10-14'};mp=await call('/plan/resource-preview',machine);const count=await prisma.resourceAssignment.count();await prisma.$executeRawUnsafe('ALTER TABLE "AuditLog" RENAME TO "_ResourceAuditUnavailable"');try{assert.equal((await call('/plan/resource-commit',{...machine,fingerprint:mp.data.fingerprint})).status,503);assert.equal((await call('/resources/assignments',{...concurrent,date:'2026-10-16'})).status,503);}finally{await prisma.$executeRawUnsafe('ALTER TABLE "_ResourceAuditUnavailable" RENAME TO "AuditLog"');}assert.equal(await prisma.resourceAssignment.count(),count);
 await prisma.$executeRawUnsafe(`CREATE FUNCTION public.reject_plan_resource_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='PLAN_RESOURCE_HANDOFF' THEN RAISE EXCEPTION 'Isolated audit rollback test'; END IF; RETURN NEW; END $$`);
 await prisma.$executeRawUnsafe(`CREATE TRIGGER reject_plan_resource_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION public.reject_plan_resource_audit()`);
 const beforeRollback=await prisma.resourceAssignment.count();try{assert.equal((await call('/plan/resource-commit',{...machine,fingerprint:mp.data.fingerprint})).status,503);assert.equal(await prisma.resourceAssignment.count(),beforeRollback);}finally{await prisma.$executeRawUnsafe('DROP TRIGGER reject_plan_resource_audit ON "AuditLog"');await prisma.$executeRawUnsafe('DROP FUNCTION public.reject_plan_resource_audit()');}
 assert.equal((await call('/resources/assignments',{...concurrent,projectId:'pr-hidden',hours:10},{'x-role':'ADMIN'})).status,409);
 assert.equal((await call('/plan/resource-commit',{...machine,fingerprint:mp.data.fingerprint})).status,200);await prisma.resourceAssignment.delete({where:{id:first.id}});preview=await call('/plan/resource-preview',body);assert.equal(preview.data.blocked,true);assert.equal(preview.data.days[0].status,'deleted');assert.equal((await call('/plan/resource-commit',{...body,fingerprint:preview.data.fingerprint})).status,409);
 const old=v;saved=await call('/plan/save',{...planBody,expectedVersion:v});v=saved.data.version;assert.equal((await call('/plan/resource-preview',body)).status,409);
 assert.equal((await prisma.companyEmployee.findUnique({where:{id:'pr-e'}})).hourlyRate.toString(),'23.45');assert.equal((await prisma.companyMachine.findUnique({where:{id:'pr-m'}})).hours,10);assert.equal((await prisma.companyMaterial.findUnique({where:{id:'pr-material'}})).stock,11);assert.equal(await prisma.ledgerEntry.count(),0);assert.equal(await prisma.machineUsageEntry.count(),0);assert.equal(await prisma.projectTask.count(),0);assert.equal((await call('/plan/load',{projectId:'pr-p'})).data.version,v);
 console.log('PASS plan resource handoff: tenant/project/role and minimal resource scopes, strict dates/hours/weekdays/range, preview without writes, non-working day/weekend exclusions, atomic concurrent replay, manual target edits retained, stale preview and source version conflicts, deleted links not silently recreated, shared cross-project daily cap with concurrent ordinary writes, audit rollback and preserved plan/master/accounting data.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
