import assert from 'node:assert/strict';import express from 'express';import http from 'http';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/rlc_handoff_validation_20261010';process.env.DATABASE_URL=url.toString();process.env.DEV_AUTH='off';
const {prisma}=require('../lib/prisma'),plan=require('../routes/buero/bauzeitenplan').default,tasks=require('../routes/projectTasks').default,calendar=require('../routes/officeCalendar').default;
async function main(){
 await prisma.company.createMany({data:[{id:'ho-a',code:'HO-A',name:'Fiktiv A'},{id:'ho-b',code:'HO-B',name:'Fiktiv B'}]});await prisma.user.create({data:{id:'ho-user',companyId:'ho-a',email:'handoff@test.invalid',password:'test'}});await prisma.project.createMany({data:[{id:'ho-p',companyId:'ho-a',code:'HO-P',name:'A'},{id:'ho-hidden',companyId:'ho-a',code:'HO-HIDDEN',name:'Hidden'},{id:'ho-foreign',companyId:'ho-b',code:'HO-B-P',name:'B'}]});await prisma.projectMember.create({data:{projectId:'ho-p',userId:'ho-user',role:'BAULEITER'}});
 await prisma.companyMaterial.create({data:{id:'ho-mat',companyId:'ho-a',name:'Existing',stock:11}});await prisma.companyEmployee.create({data:{id:'ho-emp',companyId:'ho-a',name:'Existing',hourlyRate:'23.45'}});
 const app=express();app.use(express.json());app.use((req:any,_res,next)=>{req.auth={sub:req.headers['x-no-user']?'':'ho-user',companyId:req.headers['x-company']||'ho-a',companyRole:req.headers['x-role']||'BAULEITER'};next();});app.use('/plan',plan);app.use('/tasks',tasks);app.use('/calendar',calendar);const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 async function call(path:string,body:any=undefined,headers:any={},method=body===undefined?'GET':'POST'){const res=await fetch('http://127.0.0.1:'+(server.address() as any).port+path,{method,headers:{'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,data:await res.json() as any};}
 try{
 const version=(await call('/plan/load',{projectId:'ho-p'})).data.version;
 const planBody={projectId:'ho-p',expectedVersion:version,start:'2026-03-29',capacity:{Bagger:1},tasks:[{id:'ho-t',name:'Fiktiver Meilenstein',dauerTage:1,start:'2026-03-29',end:'2026-03-29',progress:100,notes:'Original',assignee:'Fiktiv',milestone:true,deps:[],ressourcen:{}},{id:'ho-undated',name:'Ohne Datum',dauerTage:2,start:null,end:null,progress:0,notes:'',assignee:'',milestone:false,deps:[],ressourcen:{}}]};
 const saved=await call('/plan/save',planBody);assert.equal(saved.status,200);let v=saved.data.version;
 const body={projectId:'HO-P',expectedVersion:v,taskId:'ho-t',target:'task'};
 for(const h of [{'x-company':'ho-b'},{'x-role':'GAST'},{'x-no-user':'1'}])assert.equal((await call('/plan/handoff',body,h)).status,403);
 assert.equal((await call('/plan/handoff',{...body,projectId:'ho-hidden'})).status,403);assert.equal((await call('/plan/handoff',{...body,expectedVersion:version})).status,409);assert.equal((await call('/plan/handoff',{...body,taskId:'missing'})).status,404);
 const pair=await Promise.all([call('/plan/handoff',body),call('/plan/handoff',body)]);assert.deepEqual(pair.map(r=>r.status),[200,200]);assert.equal(pair.filter(r=>r.data.created).length,1);let task=pair[0].data.item;assert.equal(task.done,false);assert.equal(task.priority,'high');assert.equal(await prisma.projectTask.count(),1);
 assert.equal((await call('/tasks?projectId=HO-P')).status,200);const readonly=await call('/tasks?projectId=ho-p',undefined,{'x-role':'GAST'});assert.equal(readonly.data.canEdit,false);assert.equal((await call('/tasks',{projectId:'ho-p',title:'Forbidden'},{'x-role':'GAST'})).status,403);
 assert.equal((await call('/tasks/'+task.id,{title:'Missing version'}, {},'PUT')).status,409);
 const updates=await Promise.all([call('/tasks/'+task.id,{expectedUpdatedAt:task.updatedAt,title:'Manual edit A'}, {},'PUT'),call('/tasks/'+task.id,{expectedUpdatedAt:task.updatedAt,title:'Manual edit B'}, {},'PUT')]);assert.deepEqual(updates.map(r=>r.status).sort(),[200,409]);task=updates.find(r=>r.status===200)!.data.item;
 assert.equal((await call('/plan/handoff',body)).data.item.title,task.title);assert.equal((await call('/tasks/'+task.id,{expectedUpdatedAt:task.updatedAt,sourceId:'fake'}, {},'PUT')).status,400);
 const calPair=await Promise.all([call('/plan/handoff',{...body,target:'calendar'}),call('/plan/handoff',{...body,target:'calendar'})]);assert.equal(calPair.filter(r=>r.data.created).length,1);assert.equal(await prisma.officeCalendarEvent.count(),1);let event=calPair[0].data.item;assert.equal((Date.parse(event.end)-Date.parse(event.start))/3600000,23);assert.equal(event.allDay,true);
 assert.equal((await call('/calendar',{projectId:'ho-p',title:'Bypass',start:event.start,end:event.end,sourceType:'bauzeitenplan',sourceId:'ho-t'})).status,409);
 const manualCal=await call('/calendar/'+event.id,{title:'Manual calendar edit'}, {},'PUT');assert.equal(manualCal.status,200);assert.equal((await call('/plan/handoff',{...body,target:'calendar'})).data.item.title,'Manual calendar edit');assert.equal((await call('/plan/handoff',{...body,taskId:'ho-undated',target:'calendar'})).status,400);
 const taskCalBody={expectedUpdatedAt:task.updatedAt};const taskPair=await Promise.all([call('/tasks/'+task.id+'/calendar',taskCalBody),call('/tasks/'+task.id+'/calendar',taskCalBody)]);assert.equal(taskPair.filter(r=>r.data.created).length,1);assert.equal(await prisma.officeCalendarEvent.count(),2);
 for(const input of [{title:''},{due:'2026-02-30'},{due:false},{done:'false'},{priority:'garbage'},{tags:['x',3]}])assert.equal((await call('/tasks/'+task.id,{expectedUpdatedAt:task.updatedAt,...input},{},'PUT')).status,400);
 const beforeTask=JSON.stringify(await prisma.projectTask.findUnique({where:{id:task.id}}));await prisma.$executeRawUnsafe('ALTER TABLE "AuditLog" RENAME TO "_HandoffAuditUnavailable"');try{
  assert.equal((await call('/tasks/'+task.id,{expectedUpdatedAt:task.updatedAt,title:'Must roll back'},{},'PUT')).status,503);
  assert.equal((await call('/plan/handoff',{...body,taskId:'ho-undated'})).status,503);
 }finally{await prisma.$executeRawUnsafe('ALTER TABLE "_HandoffAuditUnavailable" RENAME TO "AuditLog"');}
 assert.equal(JSON.stringify(await prisma.projectTask.findUnique({where:{id:task.id}})),beforeTask);assert.equal(await prisma.projectTask.count(),1);
 const {berlinMidnight,nextCalendarDay}=require('../domain/nonWorkingDay');assert.equal((berlinMidnight(nextCalendarDay('2026-10-25')).getTime()-berlinMidnight('2026-10-25').getTime())/3600000,25);
 assert.equal((await call('/tasks?projectId=ho-foreign')).status,403);assert.equal((await call('/tasks/'+task.id+'/calendar',taskCalBody,{'x-company':'ho-b'})).status,404);
 const dup=await prisma.projectTask.create({data:{companyId:'ho-a',projectId:'ho-p',title:'Legacy duplicate',tags:[],sourceType:'bauzeitenplan',sourceId:'ho-t'}});assert.equal((await call('/plan/handoff',body)).status,409);await prisma.projectTask.delete({where:{id:dup.id}});
 assert.equal((await call('/tasks/'+task.id+'/history')).data.items.length,3);assert.equal((await call('/tasks/'+task.id+'/history',undefined,{'x-company':'ho-b'})).status,404);
 const oldv=v;const changed=await call('/plan/save',{...planBody,expectedVersion:v,tasks:planBody.tasks.map(t=>({...t,name:t.name+' Changed'}))});assert.equal(changed.status,200);v=changed.data.version;assert.equal((await call('/plan/handoff',body)).status,409);assert.equal((await call('/plan/handoff',{...body,expectedVersion:v})).data.item.title,task.title);
 assert.equal((await call('/tasks/'+task.id,{expectedUpdatedAt:'wrong'}, {},'DELETE')).status,409);assert.equal((await call('/tasks/'+task.id,{expectedUpdatedAt:task.updatedAt}, {},'DELETE')).status,200);assert.equal(await prisma.officeCalendarEvent.count(),2);
 assert.equal((await prisma.companyMaterial.findUnique({where:{id:'ho-mat'}})).stock,11);assert.equal(String((await prisma.companyEmployee.findUnique({where:{id:'ho-emp'}})).hourlyRate),'23.45');assert.equal(await prisma.ledgerEntry.count(),0);assert.equal((await call('/plan/load',{projectId:'ho-p'})).data.version,v);
 console.log('PASS plan handoff/tasks PostgreSQL: two fictional companies, project/role access, concurrent idempotent handoffs, saved-source versions, immutable links/manual edits retained, strict task values, concurrent task revisions/history/audit rollback, 23h Berlin all-day event, undated rejection and unchanged plan/resource/accounting data.');
 }finally{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
