import assert from "node:assert/strict";
import {bidInput,compareBids,lineCents,total} from "../domain/preisspiegel";
import {InputError} from "../domain/officeAddons";
const line={position:"01.001",title:"Pipe",unit:"m",quantity:"2.5",unitPrice:"10.125"};
assert.equal(lineCents("2.5","10.125"),2531n);
assert.equal(lineCents("0.000001","999999999"),100000n);
assert.equal(total([line],"10"),"22.78");
for(const v of ["NaN","-0.1","1e5","","0.12345"])assert.throws(()=>bidInput({title:"A",supplier:"B",packageKey:"LV",kind:"LV",status:"Entwurf",positions:[{...line,unitPrice:v}]}),InputError);
const body={title:"A",supplier:"B",packageKey:"LV",kind:"LV",status:"Entwurf",positions:[line]};
assert.throws(()=>bidInput({...body,positions:[line,line]}),InputError);
assert.throws(()=>bidInput({...body,discountPercent:"100.01"}),InputError);
assert.throws(()=>bidInput({...body,positions:[{...line,quantity:"999999999",unitPrice:"999999999"}]}),InputError);
const base={id:"base",title:"Base",supplier:"A",status:"Eingereicht",discountPercent:"0",positions:[line]};
const good={...base,id:"good",supplier:"B",positions:[{...line,quantity:"3",unitPrice:"9"}]};
const bad={...base,id:"bad",positions:[{...line,unit:"m2"}]};
const missing={...base,id:"missing",positions:[]};
const extra={...base,id:"extra",positions:[line,{...line,position:"01.002"}]};
const comparison=compareBids([base,good,bad,missing,extra],base.id);
assert.equal(comparison.offers.find(x=>x.id==="good")!.normalizedTotal,"22.50");
assert.equal(comparison.offers.find(x=>x.id==="good")!.offeredTotal,"27.00");
assert.equal(comparison.offers.find(x=>x.id==="good")!.cells[0].quantityDiff,true);
assert.equal(comparison.ranking[0].id,"good");
for(const id of ["bad","missing","extra"])assert.equal(comparison.offers.find(x=>x.id===id)!.comparable,false);
assert.equal(compareBids([{...base,positions:[{...line,unit:"m²"}]},{...good,positions:[{...line,unit:"qm"}]}],base.id).offers[1].comparable,true);
console.log("PASS: decimal arithmetic/rounding, discounts, malformed numbers, duplicate positions, totals overflow, common quantities, missing/extra positions, incompatible units, unit aliases, submitted-offer ranking.");
