import fs from 'fs';
import {checkTechnicalAiScope} from '../kalkulation/autonomous/technicalAiScopeGate';
import {completeRlcAiText} from '../services/ai/rlcAiGateway';
const input=process.argv[2],output=process.argv[3],limit=Math.min(100,Math.max(1,Number(process.argv[4]||4)));
const pilot=JSON.parse(fs.readFileSync(input,'utf8'));
const system=`Du bist ein deutscher Baukalkulator für Tiefbau. Analysiere eine GAEB-LV-Position anhand Kurztext/Langtext/Einheit. Gib ausschließlich JSON zurück, ohne Markdown. Schema: {"mainWork":"string","operation":"supply|install|construct|remove|test|surcharge|unknown","unit":"string","technicalParameters":[{"name":"string","value":"string","evidence":"kurztext|langtext"}],"resourcePlan":[{"type":"material|labour|equipment|transport|disposal|subcontract","task":"string","quantityPerUnit":null,"quantityUnit":"string","reason":"string"}],"missingInputs":["string"],"confidence":0.0,"needsReview":true}. Die Operation MUSS aus dem Verb des Kurztextes folgen: herstellen=construct, liefern=supply, abbrechen=remove. Falls Kurztext herstellen sagt, niemals nur supply zurückgeben. Für jede Bauleistung muss resourcePlan mindestens eine Ressource enthalten. Verwende ausschließlich die sechs vorgegebenen Ressourcentypen. Beschreibe die tatsächliche Hauptleistung und notwendige Ressourcen. Schätze KEINE Preise, Stunden, Geräteproduktivitäten, Materialmengen oder DN; verwende null bei fehlenden Angaben. Kontroll-/Prüfverweise im Langtext nicht als eigenständige Hauptleistung behandeln. Zulage ist nur ein Mehraufwand zur Grundposition. Erfinde keine Normen oder Quellen.`;
function validate(x:any):string[]{const e:string[]=[];if(!x||typeof x!=='object')return ['not_object'];if(typeof x.mainWork!=='string'||!x.mainWork.trim())e.push('main_work_missing');if(!['supply','install','construct','remove','test','surcharge','unknown'].includes(x.operation))e.push('invalid_operation');if(!Array.isArray(x.resourcePlan)||!x.resourcePlan.length)e.push('resource_plan_missing');if(typeof x.unit!=='string'||!x.unit.trim())e.push('invalid_unit');if(!Array.isArray(x.missingInputs))e.push('missing_inputs_invalid');if(typeof x.confidence!=='number'||x.confidence<0||x.confidence>1)e.push('invalid_confidence');if(typeof x.needsReview!=='boolean')e.push('review_flag_missing');if(Array.isArray(x.resourcePlan))for(const r of x.resourcePlan){if(!['material','labour','equipment','transport','disposal','subcontract'].includes(r?.type))e.push('invalid_resource_type');if(r?.quantityPerUnit!==null&&typeof r?.quantityPerUnit!=='number')e.push('invalid_quantity');}return e;}
async function main(){const responses:any[]=[];for(const p of pilot.positions.slice(0,limit)){
 try{const response=await completeRlcAiText({purpose:'classification',responseFormat:'json',maxTokens:900,timeoutMs:50000,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({shortText:p.shortText,longText:p.longText,unit:p.unit})}]});const obj=JSON.parse(response.text);const short=String(p.shortText).toLowerCase();const quality:string[]=[];
 if(/\bherstellen\b/.test(short)&&obj.operation==='supply')quality.push('main_operation_inconsistent_with_shorttext');
 if(/\b(?:abbrechen|rückbauen|ausbauen)\b/.test(short)&&!['remove','dispose'].includes(obj.operation))quality.push('removal_operation_mismatch');
 if(/\b(?:liefern|lieferung)\b/.test(short)&&obj.operation==='remove')quality.push('supply_operation_mismatch');
 if(Array.isArray(obj.resourcePlan)&&obj.resourcePlan.some((r:any)=>r?.quantityPerUnit!==null)&&!obj.needsReview)quality.push('unverified_resource_quantities');
 responses.push({id:p.id,trade:p.trade,position:p.position,provider:response.provider,model:response.model,usage:response.usage,result:obj,validationErrors:[...validate(obj),...quality,...checkTechnicalAiScope(p.shortText,p.longText,p.unit,obj)],reviewRequired:true});}
 catch(error){responses.push({id:p.id,trade:p.trade,position:p.position,error:String(error).slice(0,280),validationErrors:['provider_or_format_failed'],reviewRequired:true});}
 fs.writeFileSync(output,JSON.stringify({totalSelected:pilot.selected,attempted:responses.length,responses},null,2));console.log('PROCESSED',responses.length,'VALID',responses.filter(r=>r.validationErrors.length===0).length,'ERRORS',responses.filter(r=>r.error).length);
 } }
main().catch(e=>{console.error(String(e));process.exit(1)});
